### ISSUE TITLE
Inversing the SX gate gives mixed results depending on the optimization-level.

### ISSUE THREAD

**Issue by Cubemaster1999** [Qiskit/qiskit-terra#10022]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 3.10.6
- **Operating system**: Ubuntu 22.04

### What is happening?

The Inverse of the sx gate seems to add more gates than necessary.  
For my application I need a gate and the minimal inverse of this gate with a given gate set (e.g from a device).
Here I take the inverse of the SX gate which results in apply two rz gates then a sx gate and then two more rz gate. But two rz gates in a row could be simplified by one rz gate.

Note that I use the gate set of the 5-qubit devices.
I provided 3 examples. In the first the sx gate is added to the circuit. Then the inverse of the sx gate is added.
In the second circuit consists of the inverse of the sx gate without optimization.
The third circuit is like the second circuit but optimized with optimization_level 3.

![Screenshot from 2023-04-24 14-58-11](https://user-images.githubusercontent.com/56534984/234003206-e7b4ee30-1e67-4110-a5dd-fd53cb983a83.png)

### How can we reproduce the issue?

```from qiskit import QuantumCircuit, transpile
from numpy import pi

circuit_1 = QuantumCircuit(1)
circuit_1.sx(0)
circuit_1.append(circuit_1.inverse(),[0])
print(transpile(circuit_1,basis_gates=['x','cx','rz','sx'],optimization_level=0))

circuit_2 = QuantumCircuit(1)
circuit_2.sx(0)
circuit_2 = circuit_2.inverse()
print(transpile(circuit_2,basis_gates=['x','cx','rz','sx'],optimization_level=0))

circuit_3 = QuantumCircuit(1)
circuit_3.sx(0)
circuit_3 = circuit_3.inverse()
print(transpile(circuit_3,basis_gates=['x','cx','rz','sx'],optimization_level=3))
```

### What should happen?

It should be expected that without an optimization_level, the inverse is rz(-pi) sx rx(-pi).

**Comment by jakelishman** [comment]
If you transpile at `optimization_level=0`, you're asking for us to do no optimisation, so it seems odd to complain that the resulting circuit is not optimised.  If you use the default optimisation level (1), you'd get the result you're looking for the circuit at a whole.  If you want to specifically control certain gates in the circuit and use `optimization_level=0`, you probably want to directly add the gates you want to the circuit.

The reason it gets translated into 5 gates with no optimisation is just because the equivalence rule that it passes through takes `sxdg` to `s - h - s`, which then gets taken to `rz - (rz - sx - rz) - rz`.  At any optimisation level other than the 0 you've used, we'd then resynthesise that into just three gates.  We can't meaningfully add synthesis rules for every gate for every possible combination of basis gates a backend machine might have, which is why our compiler pipelines are split up like this.

**Comment by Cubemaster1999** [comment]
I think I can close the issue.
But I want to mention that using optimization level 1 on the first circuit does not result in the solution I want. Because the circuit is just the identity gate and optimization level 1 realizes that fact and results in no gates at all.
Ofcause you cannot add synthesis rules for every gate this is not what I wanted to achieve.
Sorry to bother you guys and thanks for the help.
