### ISSUE TITLE
transpiling in level 0 does not work on disjoint/multi-chip devices

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#10276]
### Environment

- **Qiskit Terra version**:'0.25.0.dev0+b36609b
- **Python version**: 3.9
- **Operating system**: MacOS

### What is happening?

On Aprils 20th, 2023 @mtreinish [demoded](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays#apr-20-2023) transpiler support for disjoint/multi-chip devices. When that demo is ran with `optimization_level=0`, this exception raises:

```
TranspilerError: 'Chosen layout is not valid for the target disjoint connectivity'
```

### How can we reproduce the issue?

 * Take the cells 5 to 9 from https://github.com/Qiskit/feedback/blob/main/demo-day-notebooks/2023-04-20/1_terra_0.24.ipynb.

 * Add `optimization_level=0` to the `transpile` call

### What should happen?

it should work as in other optimization levels.

### Any suggestions?

It seems like a problem in the level 0 workflow, which sets a layout prematurely, without considering the disjoint scenario.

**Comment by mtreinish** [comment]
This is working as intended, level 0 does not set a layout it always uses a trivial layout. If you want to use level 0 with a disjoint coupling map you either need to hand lay it out so no connectivity is required across connected components, or set the `layout_method` argument. This behavior was discussed at the time and this was was the consensus on the desired/expected behavior when running with level 0.
