### ISSUE TITLE
SparsePauliOp.paulis setter does not propagate dimension info

### ISSUE THREAD

**Issue by ihincks** [Qiskit/qiskit-terra#10384]
### Environment

- **Qiskit Terra version**: 0.24.1
- **Python version**: any
- **Operating system**: any

### What is happening?

Setting the `paulis` attribute (it has a `@setter`) on a `SparsePauliOp` instance does not update the `BaseOperator` shape attributes.

### How can we reproduce the issue?

```python
import qiskit.quantum_info as qi

pauli_x = qi.SparsePauliOp(["X"], [1])
pauli_x.paulis = ["XX"]
print(pauli_x, pauli_x.dim)
```

### What should happen?

The above snippet produces the output
```
SparsePauliOp(['XX'],
              coeffs=[1.+0.j]) (2, 2)
```
whereas it should produce
```
SparsePauliOp(['XX'],
              coeffs=[1.+0.j]) (4, 4)
```
if changing the dimension is allowed, or raise an exception if it's not allowed.

### Any suggestions?

I haven't looked closely, but it's possible that just updating `_op_shape` will be sufficient to fix the bug.

**Comment by atharva-satpute** [comment]
Looks like value of `num_qubits` gets updated from `PauliList` and up but does not get updated from `SparsePauliOp`.

**Comment by jakelishman** [comment]
Personally I'd argue that those attributes shouldn't be settable by users at all, but I think the ship's sailed on that front.  Given that the setter exists, I think the best solution would be to have it reject attempts to either modify the number of elements (so `len(self._pauli_list)` must not change) because that allows an inconsistency with `self.coeffs`, and also reject any attempt to modify the number of qubits because that just seems inconsistent with the rest of `qiskit.quantum_info`.

**Comment by ikkoham** [comment]
Agree with @jakelishman's comment.
