### ISSUE TITLE
remove warning when no latex

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1041]
WARNING Unable to complile latex. The output from the pdflatex command can be found in latex_error.log

i think we do not need to have this warning and we should fix the spelling. 

I think we just default to latex -> matplotlib -> ascii

**Comment by mtreinish** [comment]
Well part of the issue here (aside from the typo which was my bad) is I think it's not very clear what is happening when you call circuit_drawer() (or plot_circuit()) there is no transparency into what's happening under the covers. So when doing the fallback to matplotlib from latex if you were expecting a latex drawing it would be a a bit jarring without any output to indicate why latex was not used and you got a matplotlib rendered one instead.

What I was looking at doing for the future was to make it an explicit flag what type of visualization you wanted to have. Something like circuit.draw('latex') (or maybe circuit.draw(latex=True)) and just have it raise an exception if it's unable to render the drawing with the mechanism requested.

**Comment by jaygambetta** [comment]
yeah, I agree. I would like the default to be the ascii when we have it (but I know @ajavadia likes latex). and then the latex, matplotlib being inputted as you say.

**Comment by jaygambetta** [comment]
I think this is part of #1049 as you point out. Let's just make it and input and you can make it what you want. I am going to close this and keep it tracked in #1049 as that will fix this warning.
