### ISSUE TITLE
QASM2 exporter when appending empty circuit

### ISSUE THREAD

**Issue by MattePalte** [Qiskit/qiskit-terra#10435]
### Environment

- **Qiskit Terra version**: qiskit==0.43.1
- **Python version**: 3.10
- **Operating system**: Ubuntu 18.04

### What is happening?

The QASM2 exporter creates an invalid qasm when an empty circuit is appended.

### How can we reproduce the issue?

Running this simple snippet, where a circuit is appended to another generates an invalid QASM2:
```python
from qiskit import QuantumCircuit
q_1 = QuantumCircuit(5, name='legit_circuit')
q_2 = QuantumCircuit(name='empty_circuit')
q_1.append(q_2)
q_1.qasm(filename="c1.qasm")
```
Output:
```qasm
OPENQASM 2.0;
include "qelib1.inc";
gate empty_circuit  {  }
qreg q[5];
empty_circuit ;
```
Where we have an empty instruction.
It is incorrect because if cannot be re-imported:
```python
from qiskit import QuantumCircuit
QuantumCircuit().from_qasm_file("c1.qasm")
```
Failing with error: 
```shell
qasm/qasmparser.py", line 397, in p_id_e
    raise QasmError("Expected an ID, received '" + str(program[1].value) + "'")
qiskit.qasm.exceptions.QasmError: "Expected an ID, received '{'"
```

### What should happen?

I would have expected a valid `qasm` file or an error while exporting.

### Any suggestions?

Probably this corner case should be checked when creating custom gates at the QASM level exporter. Either  an error should be thrown when exporting, or ideally all empty instructions should be removed before exporting.

**Comment by 1ucian0** [comment]
I think, according to the OpenQASM 2 grammar, `gate empty_circuit  {  }` is invalid.

I'm actually surprised that `QuantumCircuit(name='empty_circuit')` is valid :-/

**Comment by 1ucian0** [comment]
Other non-valid OpenQASM2 exports:
```
from qiskit import QuantumCircuit
q_1 = QuantumCircuit(5, 1, name='legit_circuit')
q_2 = QuantumCircuit(1, name='with_classical_wire')
q_2.measure_all()
q_1.append(q_2, [0], [0])
print(q_1.qasm())
```

```
OPENQASM 2.0;
include "qelib1.inc";
gate with_classical_wire q0 { barrier q0; measure q0; }
qreg q[5];
creg c[1];
with_classical_wire q[0],c[0];
```

**Comment by jakelishman** [comment]
Luciano: that second example is already a total lost cause in the OQ2 exporter - unknown `Instruction` instances shouldn't be permitted to be exported whether or not they've got classical bits, because an `Instruction` that is not a `Gate` is explicitly saying "you can't rely on me being unitary".  However, I'm fairly sure there are places using OQ2 exports that play loosely with `to_instruction` vs `to_gate`, so at this point it's unlikely to be worth trying to walk that back.

Erroring out when there's a clbit in the `Instruction` is fine, though, as is erroring out if there's no qubits.  Note that there _are_ valid 0q unitary operations (advancing the global phase), but they're not representable in OQ2, which requires all `gate` declarations and uses to involve at least one qubit.
