### ISSUE TITLE
Statevector drawer in Latex / "bra" shows wrong visualisation

### ISSUE THREAD

**Issue by Raghav-Bell** [Qiskit/qiskit-terra#10445]
### Environment

- **Qiskit Terra version**: 0.24.1
- **Python version**: any (3.10.12)
- **Operating system**: any (posix)

### What is happening?

Statevector draws bra notation also like ket. Following screenshot clears it more.
![image](https://github.com/Qiskit/qiskit-terra/assets/83136390/772a56fe-2355-4e34-9d45-550ef07f6bc3)

### How can we reproduce the issue?

Just try to draw any bra Statevector you will get the wrong visualisation.

### What should happen?

Correct output should be <0|.

### Any suggestions?

I found this bug first time while running IBM Quantum QGSS-23 lab 1 and reported to the team on discord too.

**Comment by jakelishman** [comment]
The `Statevector` class only represents pure quantum states; it doesn't represent bras, which mathematically are vectors in the dual of the state space.  Holding a `Statevector` implies that you've got a state (ket) only, and generally, `Statevector` only allows raw vectors or explicit column vectors.

If you want to write an explicit row vector for your bra, the matrix would be `[[1, 0]]` (a nested list), but `Statevector` will reject this, because it's not a valid statevector.

**Comment by jakelishman** [comment]
(That's all expected behaviour: `Statevector` only "represents" bras in the sense that it represents the state that the bra corresponds to.)
