### ISSUE TITLE
Documentation: Impove CASE_DEFAULT documentation

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#10458]
### What should we add?

From https://qiskit.org/documentation/stubs/qiskit.circuit.SwitchCaseOp.html:
> The special value CASE_DEFAULT can be used to represent a default condition.

But it doesn't explain how to import `CASE_DEFAULT` and there is no hyperlink.

**Comment by jakelishman** [comment]
Yeah, it's meant to hyperlink to an entry right underneath [this table of the control-flow ops](https://qiskit.org/documentation/apidoc/circuit.html#control-flow-operations), but I must have screwed up the Sphinx syntax.

I'll fix it tomorrow, because I don't want to put up a new PR right now while we're in a CI concurrency crunch for the 0.25.0rc1 release today (or early tomorrow if we can't get through CI).

**Comment by jakelishman** [comment]
I've made #10484 that hopefully should make a bunch of improvements here.
