### ISSUE TITLE
Strange behavior when `conditional= True` in `random_circuit()`

### ISSUE THREAD

**Issue by raynelfss** [Qiskit/qiskit-terra#10472]
### Environment

- **Qiskit Terra version**:  0.25.0rc1
- **Python version**: 3.11.3
- **Operating system**:  MacOS 13.4.1 (c) 

### What is happening?

There's some very strange behavior happening whenever `random_circuit` with `conditional=True` is called, as it will add several measure gates to the circuit after all the operations are done.

### How can we reproduce the issue?

You can replicate the issue with the following code snippet:
```py3
from qiskit.circuit.random import random_circuit

qc = random_circuit(24, 8, seed=102992833, conditional=True)
qc.draw('mpl', fold=-1)
```

Your output should look somewhat like this:
![image](https://github.com/Qiskit/qiskit-terra/assets/87539502/5071bd7d-ff1a-4df5-9d24-1b43036fe2e5)

### What should happen?

A circuit that looks like this:
![image](https://github.com/Qiskit/qiskit-terra/assets/87539502/db4eeec4-79cb-4f6b-822d-accf8c113f1a)

**Comment by jakelishman** [comment]
When you set `conditional=True`, #10401 made it so that you're guaranteed to have measurements right before the conditional (so there's a chance that the conditional can actually be entered).  Given that, I think the behaviour you're seeing is intended - the measurements aren't actually at the end, they all come before a conditional.

**Comment by raynelfss** [comment]
Oh that makes more sense. I was very confused about the new behavior. Thank you for explaining it.
