### ISSUE TITLE
Update Jupyter Version Table

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/qiskit-terra#10608]
## Background

Today, the [Jupyter Version Table](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/tools/jupyter/version_table.py) includes the following information:

<img width="473" alt="Screenshot 2023-08-10 at 2 36 38 PM" src="https://github.com/Qiskit/qiskit-terra/assets/6241840/238c8d53-d40b-422d-a75e-ebadc3c39766">

## Discussion

There are several items I wanted to open for discussion:

1. **What packages should be there?** I believe we should be adding [qiskit-ibm-runtime](https://github.com/Qiskit/qiskit-ibm-runtime) to this table as it's a package in the "main" tier (and other packages that are in this tier)
2. **What packages should be removed?** For example, there are several "community" items here that we shouldn't have here?
3. **Is it possible to add a toggle for System Information?** There are several places where this Version Table is shown. In most cases, the package versions and the Python version are the only things that are essential to show

## Next Best Alternative

Our enablement (tutorials / courses), can call `get_version_info()` directly:

```python
import qiskit_ibm_runtime

qiskit_ibm_runtime.version.get_version_info()

import qiskit

qiskit.version.get_version_info()

!python --version
```

While this is fine in general, I think the table magic allows us to be consistent easier

CC: @jyu00, @1ucian0, @javabster, @abbycross

**Comment by mtreinish** [comment]
This was updated in #10242 as part of 0.25.0. In the current release it will show any package currently imported that starts with `qiskit` that is imported along with the `qiskit` package version. TBH, I was personally not a fan of keeping the jupyter magic in qiskit, as I think it's utility is very small and it's only because of it's current use in `qiskit-tutorials` that I think we kept it. What you're doing in "Next Best Alternative" is what I normally recommend people do (or just call `qiskit.__version__` and `qiskit_ibm_runtime.__version__` if they want to get the versions of the packages of interest. You can easily build a local magic for custom and consistent formatting, all it's basically doing is just building an html table based on the `__version__` attributes anyway.

**Comment by pandasa123** [comment]
Sounds good! I agree with your thoughts on the Jupyter Magic's place in `qiskit`

Will close this issue today, and have the NBA as the promoted route instead
