### ISSUE TITLE
result.get_memory() command

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1063]
We have many requests to have the random numbers streamed in memory. 

The basic idea is to get something to run like 

```
backend = IBMQ.get_backend('name')
backend.update_settings('memory'=True)
job = backend.run(qobj)
result = job.result()
```
then we go 

```
outcomes = result.get_memory()
``` 
outcomes will be 

```
['010', '100', '111' ...]
```
 
- [ ] make sure the experiment can work with it @taalexander  is doing this
- [ ] pass the api 
- [ ] qiskit function exists to get_memory

**Comment by jaygambetta** [comment]
need to do #1052 first

**Comment by ajavadia** [comment]
But do we agree that the measurement-level that the backend returns is set via `backend.update_settings()`? The other option is to use qobj to ask the backend for a particular level.

I like the update_settings, because this is not part of the payload of the experiment.

But if we agree on this, then we should update the spec/schema so that we do the same for openpulse. Currently, openpulse qobj has a config field `meas_level` which can be 0, 1, 2.. and is a required field.

**Comment by jaygambetta** [comment]
Sure we should update. I think this is how we have to update a configurable backend.

**Comment by ajavadia** [comment]
It gets a bit messy, because the discriminators **are** part of qobj. So it's not a simple post-processing like in the case "memory"/"counts".
