### ISSUE TITLE
The qasm simulator generates different results with/without barrier

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#1138]
### Informations

- **Qiskit Terra version**: 0.7.0 (the newest master branch, the newest commit Oct. 25)
- **Python version**: 3.6.5
- **Operating system**: macOS 10.13

### What is the current behavior?
If I put a barrier after two-qubit gates (like cx, cz), the results with and without barrier are different. (seed is fixed). Not sure it is related to the issue https://github.com/Qiskit/qiskit-terra/issues/850.
Nonetheless, this time, it happened for both cpp and python simulator.

### Steps to reproduce the problem

Here is the code snippet: (rotation angle is put randomly)
```python
from qiskit import IBMQ, Aer
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit import compile as q_compile

def generate_circuits(num_qubits, depth, barrier=False):
    q = QuantumRegister(num_qubits, 'q')
    c = ClassicalRegister(num_qubits, 'c')
    qc = QuantumCircuit(q, c)    
    for i in range(num_qubits):    
        qc.u3(2.256823, 1.6990, -3.22, q[i])
        qc.u1(2.45, q[i])
    for _ in range(depth):
        for i in range(num_qubits):
            for j in range(i+1, num_qubits):
                qc.cz(q[i], q[j])
        for i in range(num_qubits):    
            qc.u3(1.955117, 245.011, 0.21120, q[i])
            qc.u1(32.134, q[i])
    if barrier:
        qc.barrier(q)
    qc.measure(q, c)
    return qc

backend = Aer.get_backend('qasm_simulator')

qc_no_barrier = generate_circuits(2, 2, False)
qc_barrier = generate_circuits(2, 2, True)

qobj_no_b = q_compile(qc_no_barrier, backend, seed=10598, shots=1000)
qobj_b = q_compile(qc_barrier, backend, seed=10598, shots=1000)

job_no_b = backend.run(qobj_no_b)
job_b = backend.run(qobj_b)

result_no_b = job_no_b.result()
result_b = job_b.result()

data_no_b = result_no_b.get_counts(qc_no_barrier)
data_b = result_b.get_counts(qc_barrier)

print(data_no_b)
print(data_b)
```
results:
c++ simulator
```
{'00': 156, '01': 429, '10': 406, '11': 9}
{'00': 170, '01': 419, '10': 402, '11': 9}
```
python simulator
```
{'01': 419, '10': 413, '00': 153, '11': 15}
{'01': 393, '10': 403, '00': 187, '11': 17}
```

### What is the expected behavior?

The barrier should not affect the results

### Suggested solutions

None

**Comment by ajavadia** [comment]
Yes I think this is expected. The barrier causes all measurements to be at the end. And the simulator has an optimization where if the measurements are at the end, it only simulates once, then samples the final statevector. However, if measurements appear in the middle, then the simulation is done for as many shots, and instead of distribution sampling, a state collapse due to measurement is simulated. These two processes are different, so the result slightly varies.

(There is a separate issue that the transpiler should put measurements at the end when it can, which is the same as #666).

**Comment by chunfuchen** [comment]
So it means that the one without barrier might not put the measurement at the end in the qobj.  
Will the fix in the transpiler resolve this issue?

**Comment by ajavadia** [comment]
Yes, the barrier ensures that no measurements get interleaved between the gates. 
Although semantically the two circuits are the same. It's just an order of writing the operations.
```
h q[1]; measure q[0];
```
is the same as
```
measure q[0]; h q[1];
```
but the simulator does not treat the latter as samplable. 

There is a conflict here between device vs. simulator optimality. On the device, you would want the measurement to be as early as possible. On the simulator, you want it moved to the end.

@nonhermitian and I thought that a possible solution is for the compiler to include a flag `samplable=True` when this is possible. The simulator can use this to apply its sampling optimization. @chriseclectic do you agree with this?

**Comment by chriseclectic** [comment]
@ajavadia is correct. In one case the simulator is sampling, in the other it is simulating every shot. This means the rng process is slightly different between the two cases so even with the same initial seed the counts should be expected to different slightly.

The C++ simulator checks the qobj to see if it can enable sampling, but it doesn't re-order any operations in doing so. If any non-measure instruction comes after a `measure` in the compiled qobj sampling will be disabled.

@chunfuchen  Since the terra compiler currently greedily pushes measurements forward in a circuit, putting in a barrier before final measurements is the safest way to ensure the compiler leaves the measurements at the end of the circuit to enable measurement sampling.

**Comment by chunfuchen** [comment]
@ajavadia @chriseclectic Thanks for the clear clarification.
Then, I have a question is that, to make codes can be run on a device and a simulator efficiently.
I need to do:
- On a device, do not explicitly put the barrier before the measurement.
- On a simulator, put the barrier before the measurement.

Is it correct? Or the barrier won't change the efficiency on running a device?

**Comment by chriseclectic** [comment]
@chunfuchen I think it's safe to always put the barrier in. As far as I know the IBMQ devices currently implement all measurements at the end of the circuit anyway.

**Comment by chunfuchen** [comment]
@chriseclectic Thanks!
@ajavadia I know the reason of the difference, do you want this issue keep open after the fix in transpiler? I am okay to close it now.

**Comment by ajavadia** [comment]
@kdk this is what you and I were talking about. I'll assign you as well.

**Comment by ajavadia** [comment]
This is now fixed by https://github.com/Qiskit/qiskit-terra/pull/1705.
