### ISSUE TITLE
removing tool.qi.qi.py

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1143]
We need to decide what lives in there and what can go else where.

**Comment by mtreinish** [comment]
Fwiw, we recently added test coverage for the `tool.qi.qi` module in #785. We probably could improve some of the input data (since I just made most of it up) to be more realistic though.  This is independent of our decision about what we keep and/or remove from the module just wanted to point out there is at least some existing test coverage.

**Comment by jaygambetta** [comment]
@chriseclectic and i will put a plan in and discuss it with you.

**Comment by jaygambetta** [comment]
We are going to remove this slowly and have the functions in quantum_info in its own module.

**Comment by jaygambetta** [comment]
I don't think we need to make this required for 0.7

**Comment by 1ucian0** [comment]
This issue is still valid,`qiskit//tools/qi/qi.py` still exists. Any plan @jaygambetta

**Comment by chriseclectic** [comment]
As of #3758 everything in this module is deprecated, so it can be deleted in future release in 3+ months time.

**Comment by chriseclectic** [comment]
Updating: it's been 3 months, so these functions can be removed in 0.15
