### ISSUE TITLE
eval_hamiltonian in qiskit/tools/apps/optimization.py seems to be broken

### ISSUE THREAD

**Issue by ens-lg4** [Qiskit/qiskit-terra#1233]
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.6.5
- **Operating system**: MacOS Sierra 10.12.6

### What is the current behavior?

function eval_hamiltonian() in qiskit/tools/apps/optimization.py that used to work for me
in Qiskit versions 0.5.4 through 0.5.7 no longer runs in Qiskit versions 0.6.0 and 0.6.1

### Steps to reproduce the problem

The old Qiskit code assumed the "device" parameter to be a name string.
Now it is expected to be the backend object.
However the eval_hamiltonian() code still attempts to find the 'statevector' substring in device,
so does not seem to have been adapted to the way the rest of the library works.

### What is the expected behavior?

This function should probably work if you pass in 'device' as a backend object,
with the rest of the code adapted to this new default behaviour.

### Suggested solutions

Erm... fix it, please?

**Comment by chunfuchen** [comment]
@ens-lg4 
There is an equivalent method in Qiskit Aqua.

At the Operator class, there is an `eval` method which does the same thing as `eval_hamiltonian`. 
https://github.com/Qiskit/aqua/blob/stable/qiskit_aqua/operator.py#L742

In the `eval_hamiltonian` method,  you need to provide `hamiltonian`, `input_circuit` and other device settings, and then it returns you the `mean` and `circuits`.
```python
def eval_hamiltonian(hamiltonian, input_circuit, shots, device):
```

Here is how you achieve the same goal in Aqua.
1. Build the Operator object, we support three modes `matrix`, `paulis` and `grouped_paulis`.
2. then, use `op.eval` method, where the `operator_mode` indicates which modes you used to create operator; the `input circuit` is the same one you used; 
 `backend` is a string name as the `device` parameter; `execute_config` is a dict that stores the setting of qiskit execute function (https://github.com/Qiskit/qiskit-terra/blob/stable/qiskit/wrapper/_wrapper.py#L282); `qjob_config` is a dict which stores the setting to retrieve the job result.
3. the method returns the `mean` and `std`. 
(!!! for the backend parameter, for Aqua > 0.3.0, you need to pass an backend object rather than a string.)

Here is example codes for Aqua 0.3.0
```python
from qiskit_aqua import Operator

operator_mode = 'paulis'
execute_config = {}
execute_config['shots'] = 1024

qjob_config = {}

device = 'statevector_simulator'  # or 'qasm_simulator' or others

op = Operator(paulis=hamiltonian)  # your hamiltonian is paulis whose dataformat must be a list of list.
mean, std = op.eval((operator_mode, input_circuit, backend=device, execute_config=execute_config, qjob_config=qjob_config)

```

Please let me know if you still encounter any issue.

**Comment by ens-lg4** [comment]
Thanks very much for your quick reply!

So you have a totally new solution for v0.6 ...

I'll have to work out the new patches to reintroduce the concepts of timeout and accounting of total quantum time spent. Unfortunately this information seems to be discarded already at run_circuits() level. Oh well...

**Comment by chunfuchen** [comment]
@ens-lg4 
The solution existed in Aqua for a long time. 
I am not sure the patch you mentioned but in the run_circuits function, we had a logic to avoid a timeout when you try to run on real hardware. 
Here is our logic: https://github.com/Qiskit/aqua/blob/stable/qiskit_aqua/utils/run_circuits.py

**Comment by chunfuchen** [comment]
you can pass timeout in qjob_config, like `qjob_config['timeout'] = 60` and the `functools.reduce()` just combine the Result object rather than waiting the result back.

The call at https://github.com/Qiskit/aqua/blob/stable/qiskit_aqua/utils/run_circuits.py#L147 is waiting for the result.

**Comment by ens-lg4** [comment]
Thank you very much for your help!

So I can now examine the timing after calling run_circuits() ?
There is get_counts() in https://github.com/Qiskit/aqua/blob/stable/qiskit_aqua/operator.py#L682 and https://github.com/Qiskit/aqua/blob/stable/qiskit_aqua/operator.py#L713 - I guess I could call get_data().get('time') in a similar way?

**Comment by chunfuchen** [comment]
Yes, definitely.

**Comment by jaygambetta** [comment]
Closing as now part of qiskit aqua
