### ISSUE TITLE
Bug in drawing conditionals in latex and matplotlib

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1318]
### Informations
After #1278 and #1276, the latex and matplotlib have a bug in drawing conditional gates:

This code:
```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
q = QuantumRegister(3, 'q')
c = ClassicalRegister(1, 'c')
circ = QuantumCircuit(q, c)
circ.u2(1.57, 0.7, q[0])
circ.measure(q[0], c[0])
circ.u1(0.1, q[1]).c_if(c, 1)
circ.draw(output='latex')
```
was drawn correctly before these 2 recent PR merges:
![image](https://user-images.githubusercontent.com/8622381/48883884-e92ff100-edef-11e8-9e8e-a903670ee792.png)

but with this patch the conditional vertical wire is gone:
![image](https://user-images.githubusercontent.com/8622381/48883923-22686100-edf0-11e8-85e2-66ba1131daf3.png)

This is also an issue with the mpl drawer:
![image](https://user-images.githubusercontent.com/8622381/48883940-36ac5e00-edf0-11e8-9c99-d2e2b466bbbb.png)

But the text drawer is fine:
```
q_2: |0>──────────────────────────────
                           ┌─────────┐
q_1: |0>───────────────────┤ U1(0.1) ├
        ┌──────────────┐┌─┐└────┬────┘
q_0: |0>┤ U2(1.57,0.7) ├┤M├─────┼─────
        └──────────────┘└╥┘┌────┴────┐
 c_0: 0 ═════════════════╩═╡   = 1   ╞
                           └─────────┘
```

**Comment by mtreinish** [comment]
Yeah, taking a brief look at the code this is being caused by the _get_instructions() output returning different data from the transpiler json format. It used to be op['conditional'] which would have a hex bitmask value. Now it's returning a bit label and is op['condition'] (so the drawers don't even know there is a conditional) we'll need to adjust the drawing code for conditionals to handle the new info.
