### ISSUE TITLE
Issue with new `from_qasm_str()` method

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#1446]
### Information

- **Qiskit Terra version**: 0.7.0
- **Python version**: 3.7.0
- **Operating system**: macOS 10.13.6

### What is the current behavior?

The `from_qasm_str()` method of `QuantumCircuit` does not seem to work.

### Steps to reproduce the problem

As far as I can tell

```
from qiskit import QuantumCircuit, Aer, compile, execute
backend = Aer.get_backend('qasm_simulator_py')

qasm = '''OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
creg c[1];
measure q -> c;'''
qc = QuantumCircuit()
qc.from_qasm_str(qasm)

print( qc.qasm() )
```
Should print the `qasm` string as defined in this snippet. Instead it just gives

```
OPENQASM 2.0;\ninclude "qelib1.inc";\n
```

along with the error

```
SchemaValidationError: 'Qobj failed validation. Set Qiskit log level to DEBUG for further information.'
```

The same occurs for the input qasm string in the form

```
qasm = '''OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[1];\ncreg c[1];\nmeasure q -> c;'''
```

### What is the expected behavior?

As described above.

### Suggested solutions

It works with

```
from qiskit import QuantumCircuit, Aer, compile, execute
backend = Aer.get_backend('qasm_simulator_py')

qasm = '''OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q[1];\ncreg c[1];\nmeasure q -> c;'''
qc = QuantumCircuit().from_qasm_str(qasm)

qc.qasm()
```

**Comment by mtreinish** [comment]
So I took a look at this and the issue is actually in the example script. The `from_qasm_str()` method is a static constructor, it operates off the class to return a circuit object based on the input qasm. In the example you're creating a blank circuit with `qc = QuantumCircuit()`, then creating a new circuit based on the qasm with `qc.from_qasm_str(qasm)` but never doing anything with it so it's not saved. Then you go back and try to use `qc` which is the blank circuit you created.

The normal pattern for using the function is something like: `qc = QuantumCircuit.from_qasm_str(qasm)` With this you only ever create 1 circuit object. While being able to create a new circuit using the method on an instantiated circuit object is a side effect of being a static method defined on the class. Using it doesn't effect that object and will only return a new circuit object independent of the existing object.

**Comment by quantumjim** [comment]
Thanks. So if I use `qc = qc.from_qasm_str(qasm)` then it would have worked (despite being a terrible way to do it!)

In that case, I guess there's no issue. It's not even that I found a method that leads to a fatal error, for which we could do something to prevent it, because it is possible to use this method to get the job done.
