### ISSUE TITLE
Mapping Error in BasicAer

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#1583]
`'OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q0[5];\ncreg c0[3];\nx q0[4];\nmeasure q0[1] -> c0[0];\nmeasure q0[3] -> c0[1];\nmeasure q0[4] -> c0[2];\n'`

The above qasm should give all shots in `100`, but they are all in `000`. Only happens in `BasicAer`, not in `Aer`. 

### Informations

- **Qiskit Terra version**: 0.7
- **Python version**: 3.6
- **Operating system**:

**Comment by jaygambetta** [comment]
I confirm there is a bug

```
qr = QuantumRegister(5)
cr = ClassicalRegister(3)
circuit = QuantumCircuit(qr, cr)
circuit.x(qr[4])
circuit.measure(qr[1], cr[0])
circuit.measure(qr[3], cr[1])
circuit.measure(qr[4], cr[2])

backend = BasicAer.get_backend('qasm_simulator')
job = execute(circuit, backend)
result = job.result()
counts1 = result.get_counts()
print(counts1)
```
gives the outcome david is saying.

**Comment by jaygambetta** [comment]
@chriseclectic can you have a look at this.

**Comment by ajavadia** [comment]
The bug is in the BasicAer python simulator. Specifically it is occurring in the `_add_sample_measure` function, which is responsible for finding a probability distribution from the statevector and sampling from that. This function cannot handle the case where only a subset of the total qubits are measured.
