### ISSUE TITLE
Bunch of warnings reported when lint

### ISSUE THREAD

**Issue by iblancasa** [Qiskit/qiskit-terra#1588]
### Informations

- **Qiskit Terra version**: master branch
- **Python version**: 3.5
- **Operating system**: Linux

### What is the current behavior?
A lot of warnings are reported when `make lint` is run.

### Steps to reproduce the problem
Run `make lint`.

### What is the expected behavior?
No warnings.

### Suggested solutions
...

**Comment by diego-plan9** [comment]
Thanks for reporting and the PR, @iblancasa - however, please note that we are using a [specific version of `pylint`](https://github.com/Qiskit/qiskit-terra/blob/master/requirements-dev.txt#L10) and it seems that the warnings are due to using a different version than the one specified.

It's good timing, though - it was discussed informally last week to revise the `pylint` version and bring it into a more recent one, and work is underway! I'm closing this issue and opening a new one for making the transition official, as it involves some extra revising and tuning (for example, the `no-else-return` might be disabled overall).
