### ISSUE TITLE
Qobj pretty printer option

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#1631]
### What is the expected enhancement?
In debugging Qobj I think we need to have a `pretty printer options` for them. I have found that I use this function often (i am not suggesting this function just something similar to make an output that is more human readable)

```python
def QobjPrint(qobj):
    print("global header: " + str(qobj.header))
    print("global user_config: " +  str(qobj.config))
    print("qobj_id: " + qobj.qobj_id)
    print("schema_version: " + qobj.schema_version)
    print("qobj_type: " + qobj.type)
    print("# experiments in qobj: " + str(len(qobj.experiments)))
    for experiment in qobj.experiments:
        print("    experiment header: " + str(experiment.header))
        print("    experiment user_config: " + str(experiment.config))
        for instructions in experiment.instructions:
            print("        " + str(instructions))
```

which for this circuit 
```python
qr = QuantumRegister(2)
cr = ClassicalRegister(2)
circuit3 = QuantumCircuit(qr, cr)
circuit3.h(qr[0])
circuit3.cx(qr[0], qr[1])
circuit3.measure(qr, cr)
```

makes the following output 
```
global header: QobjHeader()
global user_config: QobjConfig(max_credits=10, memory=False, memory_slots=2, n_qubits=2, shots=1024)
qobj_id: 8c5359a5-467e-4b8b-b1cb-c7185e61164e
schema_version: 1.0.0
qobj_type: QASM
# experiments in qobj: 1
    experiment header: QobjExperimentHeader(clbit_labels=[['c3', 0], ['c3', 1]], compiled_circuit_qasm='OPENQASM 2.0;\ninclude "qelib1.inc";\nqreg q3[2];\ncreg c3[2];\nh q3[0];\ncx q3[0],q3[1];\nmeasure q3[1] -> c3[1];\nmeasure q3[0] -> c3[0];\n', creg_sizes=[['c3', 2]], memory_slots=2, n_qubits=2, name='circuit2', qreg_sizes=[['q3', 2]], qubit_labels=[['q3', 0], ['q3', 1]])
    experiment user_config: QobjExperimentConfig(memory_slots=2, n_qubits=2)
        QobjInstruction(name='h', qubits=[0])
        QobjInstruction(name='cx', qubits=[0, 1])
        QobjInstruction(memory=[1], name='measure', qubits=[1])
        QobjInstruction(memory=[0], name='measure', qubits=[0])
```

The same may also be needed for backends.configuration, backend.properties.

**Comment by nonhermitian** [comment]
It would be nice if they had an __html_repr__ for pretty jupyter as well.

**Comment by jaygambetta** [comment]
I agree. This is why I'm not sure we need backend.configuration or backend.properties with you backend_monitor and backend_overview function.

**Comment by mtreinish** [comment]
@jaygambetta do you mean to add support to the Qobj class for use with the pprint module? If so that should just be adding a `__repr__` to the class so pprint() will be able to parse the class and return the data you want (formatted by pprint). Or did you mean add a custom function to take in a qobj and print the overview data (as you outlined in the description?

**Comment by jaygambetta** [comment]
I dont mind what we do. I can see some people might not want to overload __repr__ but i am happy if we do this and this would be my vote. The problem is viewing qobjs is painful when its a square of code with no spacing etc. I will let you, @ajavadia and @diego-plan9 decide.

**Comment by AkashGutha** [comment]
Hi, If you guys don't mind, I would like to work on this. Please let me know if you have any inputs. I will start by creating something that resembles the example provided by @jaygambetta.

**Comment by jaygambetta** [comment]
I think this would be great. @ajavadia, @diego-plan9 and @mtreinish please give some input.

**Comment by diego-plan9** [comment]
How human-readable you feel using the `as_dict` is (using `pprint` and its options directly), compared to the draft output in the issue description?

```python
>> pprint(qobj.as_dict(), depth=2)
{'config': {'max_credits': 10, 'memory_slots': 2, 'n_qubits': 2, 'shots': 1024},
 'experiments': [{...}],
 'header': {},
 'qobj_id': '73c8a082-ab57-451a-85ac-70d776e992cb',
 'schema_version': '1.0.0',
 'type': 'QASM'}
```

If that is indeed not enough, I'd recommend going with either a separate function or `__str__`, rather than `__repr__` - this has been touched in the past, but they [serve different purposes](https://docs.python.org/3/reference/datamodel.html#object.__repr__), and I think we should stay close to their original meaning and recommendations:

> Called by the repr() built-in function to compute the “official” string representation of an object. If at all possible, this should look like a valid Python expression that could be used to recreate an object with the same value (given an appropriate environment). If this is not possible, a string of the form <...some useful description...> should be returned. (...)
> This is typically used for debugging, so it is important that the representation is information-rich and unambiguous.

**Comment by AkashGutha** [comment]
@diego-plan9 I'm inclined towards making a separate function. `print_info` is the name that I'm using right now. I'm planning on making it as human readable as possible. 

I like the `as_dict` method too. But it may not make sense to everyone. So I think I'm going to make another function, probably named `print_info_raw` that can print the dictionary object using `pprint`.

**Comment by ajavadia** [comment]
I think @diego-plan9 has a good point here. 

The `as_dict` method is scalable to every instance of QobjItem, where as a specialized method is not. Currently you can do:
`qobj.as_dict()`,
`qobj.experiments[0].as_dict()`,
`qobj.experiments[0].config.as_dict()`,
`qobj.experiments[0].config.as_dict()`

and ```pprint(qobj.as_dict())```  looks like this:
```python
{'config': {'max_credits': 10, 'memory_slots': 2, 'n_qubits': 2, 'shots': 1024},
 'experiments': [{'config': {'memory_slots': 2, 'n_qubits': 2},
                  'header': {'clbit_labels': [['c0', 0], ['c0', 1]],
                             'compiled_circuit_qasm': 'OPENQASM 2.0;\n'
                                                      'include "qelib1.inc";\n'
                                                      'qreg q0[2];\n'
                                                      'creg c0[2];\n'
                                                      'h q0[0];\n'
                                                      'cx q0[0],q0[1];\n'
                                                      'measure q0[1] -> '
                                                      'c0[1];\n'
                                                      'measure q0[0] -> '
                                                      'c0[0];\n',
                             'creg_sizes': [['c0', 2]],
                             'memory_slots': 2,
                             'n_qubits': 2,
                             'name': 'circuit0',
                             'qreg_sizes': [['q0', 2]],
                             'qubit_labels': [['q0', 0], ['q0', 1]]},
                  'instructions': [{'name': 'h', 'qubits': [0]},
                                   {'name': 'cx', 'qubits': [0, 1]},
                                   {'memory': [1],
                                    'name': 'measure',
                                    'qubits': [1]},
                                   {'memory': [0],
                                    'name': 'measure',
                                    'qubits': [0]}]}],
 'header': {},
 'qobj_id': 'ed0a8018-40e9-487f-b128-f1615d3da9d2',
 'schema_version': '1.0.0',
 'type': 'QASM'}
```

what does the specialized pretty printer add to this in terms of readability?

**Comment by ajavadia** [comment]
@jaygambetta please see if the above meets your needs, and if so close the issue.

**Comment by jaygambetta** [comment]
sure we can use this code to do it but then i would still overload the `__repr__`. This being said i think it is important to also give some information like the number of circuits of the qobj (which cant be done with JSON) so i would make a function for this. I don't see why it is simpler to remember to go to dict and then go to print on it over a print option. Also this ties us to qobj being in JSON or having a to_dic whereas if we decide it is better as zip file (only joking on this representation) then the print is the human-readable representation of the qobj.

**Comment by ajavadia** [comment]
@jaygambetta The `__repr__` that you're asking for was added in #1865.

Though @nonhermitian I have to say this `__repr__` is really weird. I didn't get to review it before it was merged. With that PR, the qobj shows up like this:

```Qobj<2 qubits, 10 circuits, 1024 shots>```

First, this is an abuse of `__repr__` just to get it to show in a Jupyter notebook. `__repr__` is supposed to give an unambiguous representation of the object.

Second, what does it mean for a Qobj to have 2 qubits? The qubits can be different per experiment. That `n_qubits` in the global config is a very specific thing and is supposed to show max_qubits for across all experiments. It is not a required field and some QOBJs may not have it.

Third, it should be "experiments" not "circuits". That's qobj terminology to encapsulate pulse too.

Fourth, we've just arbitrarily chosen to show some fields and not others. For example I would argue that the schema version that the qobj was generated for is quite important information.

**Comment by nonhermitian** [comment]
1) I would personally prefer to make the `__repr__` return something useful for the end user, rather than have it obey some Pythonista convention.  Indeed, one could modify the `__str__` but then you do not get the niceties such as having clean looking lists etc.  Following your suggestion, the `__repr__` should just be the `qobj_id`, since that will unambiguously, i.e. uniquely, identify the  Qobj.  I would also point out that here is the `__repr__` for an example NumPy array: 

```
array([[0.9165739 , 0.81424152, 0.08088255, ..., 0.36733988, 0.03425009,
        0.55857208],
       [0.26647187, 0.83659415, 0.97095867, ..., 0.20384745, 0.85780822,
        0.67406684],
       [0.28641415, 0.81245791, 0.49357109, ..., 0.39085449, 0.87725276,
        0.26403877],
       ...,
       [0.02814329, 0.6342627 , 0.87257461, ..., 0.86215589, 0.50435657,
        0.79843344],
       [0.64228974, 0.92623909, 0.16000736, ..., 0.3644373 , 0.1280699 ,
        0.82067033],
       [0.62764179, 0.63865418, 0.90161605, ..., 0.20630578, 0.88383325,
        0.21530904]])
```

it is not unambiguous as you have no idea what is being hidden in the `...`, and you cannot tell the shape of the array from this.  To the best of my knowledge, the NumPy developers have not been called out on this issue.

2) Yes, that would be `n_qubits` but `n_qubits` seemed kind of silly to use, so it is `qubits`.  The number of qubits is something that an user might find useful to know.  For example, this number is different than the qubit count when compiled for a backend.  I was unaware that it is optional as it is always there.  These JSON schema things would be infinitely more useful if the optional pieces could be tagged as such, rather than having to scroll to the right location in a multi-nested mess to find out what is required.

3) Please take a look at the code in #1865.

4) Yes, we did, and that is kind of the whole point.  Instead of returning a whole `Qobj` as the `__repr__`, which was a mess, we return minimal info that is useful to the end user, some of which is actually not available easily from the raw Qobj itself, e.g. number of circuits / schedules.  Your point about schema version is spot on, and that should be added.

**Comment by jaygambetta** [comment]
not really we made `__repr__` a summary. I still want a printer for the reasons above, if you dont want to call it a printer we can call it a function `about`.

**Comment by jaygambetta** [comment]
also while I dont really like the summary lets keep it `circuits` as this is the unit of them.

**Comment by jwoehr** [comment]
Seems to be less of a coding problem than a question of the team stating a clear spec for the enhancement.

**Comment by jaygambetta** [comment]
removing with #4105
