### ISSUE TITLE
Cannot install latest version (sympy problem)

### ISSUE THREAD

**Issue by kwyip** [Qiskit/qiskit-terra#1641]
### Informations

- **Qiskit Terra version**: 0.7
- **Python version**: 3.7
- **Operating system**: Mac

### What is the current behavior? 
I create a new environment and install by pip but,
when I get to the following step i have the error:
```
Installing collected packages: sympy, qiskit-terra, qiskit
  Found existing installation: sympy 1.2
Cannot uninstall 'sympy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

### Steps to reproduce the problem

N/A

### What is the expected behavior?
N/A

### Suggested solutions
Would it help to uninstall sympy 1.2 myself?

**Comment by Exferro** [comment]
@kwyip I am not a Qiskit developer, but are you sure that you have `source <name of your venv>/bin/activate`d your virtual environment? I am asking because if you had done so, the environment should have contained no existing installations. I've just installed Qiskit into new venv without any troubles.

Please, check that you have done all the steps:
```bash
$ python3 -m venv <your_venv_name>
$ source <your_venv_name>/bin/activate
(<your_venv_name>)$ pip install qiskit
```

Hope, it will help! If not, probably someone from community could provide a better solution.

**Comment by fioyarce** [comment]
I have the same problem, but I'm using python 3.6.2 and Ubuntu 16.04 and the message is the following:

```
Install collected packages: sympy, qiskit-terra
 Found existing installation: sympy 1.1.1
Cannot uninstall 'sympy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```

**Comment by ajavadia** [comment]
I think I ran into this problem once. I had sympy installed via anaconda, so I did this:
```
> conda uninstall sympy
> pip install qiskit
```
This will install sympy via pip for you.

**Comment by ajavadia** [comment]
I also agree with @Exferro that if you have really created a new environment you should not have any pre-existing packages.

**Comment by ajavadia** [comment]
If this does not solve the issue please reopen.

**Comment by daveshen2019** [comment]
I am running the latest python 3.7.  I running into problem installing qiskit:
C:\Users\dave_>pip install qiskit
Collecting qiskit
  Using cached https://files.pythonhosted.org/packages/37/13/62c8421098faf49cbd380911986b1c9eebead08518084faa9a0dbbfc71c1/qiskit-0.8.0.tar.gz
Collecting qiskit_terra==0.7.1 (from qiskit)
  Using cached https://files.pythonhosted.org/packages/62/82/ecc340252e644dbf51b97f22b9d1b04541f6171db65aebbc7821a561fff4/qiskit-terra-0.7.1.tar.gz
Collecting qiskit-aer==0.1.1 (from qiskit)
  **Could not find a version that satisfies the requirement qiskit-aer==0.1.1 (from qiskit) (from versions: 0.1.0)
No matching distribution found for qiskit-aer==0.1.1 (from qiskit)**

**Comment by daveshen2019** [comment]
Thanks for the advice. I revert back to qiskit 0.7, and it worked. For my intent&purpose, qiskit0.7 works fine.  I filed a bug under qiskit #579 and got an answer that explains this.  Since then, it should be fixed.  However, i am still using 0.7 since i am fine with it.
https://github.com/Qiskit/qiskit-tutorials/issues/579
