### ISSUE TITLE
The output dimension of statevector simulation could be wrong if coupling map is used.

### ISSUE THREAD

**Issue by chunfuchen** [Qiskit/qiskit-terra#1649]
### Informations

- **Qiskit Terra version**: 0.7.0 
- **Python version**: 3.7.1
- **Operating system**: macOS 10.13.6

### What is the current behavior?

If a user passes a coupling map from a real device (like `ibmq_16_melbourne`, 16-qubit machine) to a statevector simulator, the output dimension of the statevector will not be the number of qubits used in the circuits.
In general, a customized coupling map with more qubits than the number of qubits in a circuit could result in the incorrect output dimension of statevector. (QASM simulation is okay since the measurement is specified.)

### Steps to reproduce the problem
Code script: using the coupling map from a real device. The same error is found for both Aer and BasicAer providers.
```python
from qiskit import IBMQ, Aer
from qiskit import QuantumCircuit, QuantumRegister, execute, compile

device = IBMQ.get_backend('ibmq_16_melbourne')
device_copling_map = device.configuration().coupling_map

q = QuantumRegister(2)
qc = QuantumCircuit(q)

qc.h(q[0])
qc.h(q[1])

aer = Aer.get_backend('statevector_simulator')

qobj = compile(qc, backend=aer, coupling_map=device_copling_map)
vec = aer.run(qobj).result().get_statevector(qc)
print(vec.shape)
```
Now, the vector dimension is `16384=2^14` but the dimension should be `4` since only two qubits are in the circuit.

### What is the expected behavior?
The output dimension should be aligned with the number of qubits used in the circuit.

### Suggested solutions
It seems that the number of qubits in the qobj is over-mapped.
E.g., for the above code, the compiled qasm looks like this, and then the backend use 14-qubit for simulation.
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[14];
u2(0,pi) q[1];
u2(0,pi) q[0];
```

**Comment by ajavadia** [comment]
@chunfuchen I revisited this issue, and I think the way we have it now is probably the expected behavior. When you use a coupling map, you are embedding a circuit within a device. So, for example you have a 14-qubit experiment, even if only 2 of the qubits are being acted upon. It is hard to interpret intentions and know that a user is not interested in the other qubits (why else would you embed it)? 

In general this is not a problem when getting counts, as you only see classical bits active in the measurement. But for the statevectors, would it help if there was a transpiler pass `RemoveIdleQubits` that a user can invoke to eliminate extra qubits? Even with this note that the statevector could be different to the unmapped case, as qubits may be swapped during transpilation.
