### ISSUE TITLE
get_counts() started to return results in HEX.

### ISSUE THREAD

**Issue by lukasszz** [Qiskit/qiskit-terra#1683]
### Informations

- **Qiskit Terra 0.6.1**:
- **Python version 3.6.1**:
- **Operating system Fedora 25**:

### What is the current behavior?
`job.result().get_counts()` started to return results in HEX.
The Qiskit and Python version didn't change. One day it started to return values in HEX instead of BIN.
![zrzut ekranu z 2019-01-16 11-11-57](https://user-images.githubusercontent.com/4717990/51242170-9a31b280-197f-11e9-9695-c73c43a266d5.png)

### Previous behaviour
![zrzut ekranu z 2019-01-16 11-09-57](https://user-images.githubusercontent.com/4717990/51242038-52129000-197f-11e9-8cbd-89013664bfe4.png)

### Steps to reproduce the problem
Run the notebook:
https://github.com/lukasszz/qiskit-tutorial/blob/bitstring_enc/community/hello_world/bitstring_encoding.ipynb

### What is the expected behavior?
Information why.

**Comment by maddy-tod** [comment]
I tried to run your notebook and also got results returned in hex. However when I ran it against the most recent version of Qiskit the results were returned in binary again, so I would suggest updating your Qiskit version to fix this error.  

The [CHANGELOG](https://github.com/Qiskit/qiskit-terra/blob/master/CHANGELOG.rst) shows a change in the location of the post-processing of result (at the end of the Remove section for 0.7.0), and so if you are running against an older version of Qiskit it is likely this processing is now getting skipped, and so the results are being returned in hex instead of binary.

**Comment by ajavadia** [comment]
Yes as @maddy-tod mentioned, updating Qiskit should resolve this issue. The devices are sending back results in hex now for efficiency, and for correct post-processing you'll need the latest qiskit. Or if you prefer to keep working with 0.6.1, you probably have to write a [quick hex2bin function](https://github.com/Qiskit/qiskit-terra/blob/5be36bc58adab346edac309932125a27cbf35b78/qiskit/result/postprocess.py#L13) over the counts.
