### ISSUE TITLE
Compile does not work for qasm_simulator when noise model is given

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1696]
### Informations

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The following fails:
```
from qiskit import QuantumRegister, ClassicalRegister
from qiskit import QuantumCircuit, execute, Aer, IBMQ, compile
from qiskit.providers.aer import noise

# Choose a real device to simulate
IBMQ.load_accounts()
device = IBMQ.get_backend('ibmq_16_melbourne')
properties = device.properties()
coupling_map = device.configuration().coupling_map

# Generate an Aer noise model for device
noise_model = noise.device.basic_device_noise_model(properties)
basis_gates = noise_model.basis_gates

# Generate a quantum circuit
q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q, c)

# Perform noisy simulation
backend = Aer.get_backend('qasm_simulator')
job_qobj = compile(qc, backend,
                  coupling_map=coupling_map,
                  noise_model=noise_model,
                  basis_gates=basis_gates)
```
```
TypeError: compile() got an unexpected keyword argument 'noise_model'
```

### Steps to reproduce the problem
Run above.

### What is the expected behavior?
It should work.

### Suggested solutions
It seems that `execute` was modified:
```
kwargs: extra arguments used by AER for running configurable backends.
                Refer to the backend documentation for details on these arguments
```
to include extra `kwargs` for Aer, but `compile` was not.

**Comment by ajavadia** [comment]
I think this is by design. It is part of separating `CompileConfig` and `RunConfig` (see #1629, and #978.).

Qobj is the experiment payload, and you only need circuits and a CompileConfig to generate it (e.g. coupling_map, native gate set, etc.)

RunConfig configures your runtime environment, like shots, max_credits, memory, etc.

The idea is that you would compile something once, but run it multiple times and on different backends, without having to recompile.

In this regard, I think it was decided that `noise_model` is part of RunConfig, so you could for example simulate the same payload with different noise. @chriseclectic can comment more.

**Comment by nonhermitian** [comment]
Ok.  However unless one read the issues you linked to they would not know this.
