### ISSUE TITLE
How to filter jobs by qasm.header.description?

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1710]
### What is the expected enhancement?

Is it possible to filter jobs on a backend by the `qasm.header.description` string?  For example:

`[job for job in backend.jobs if 'experiment_123' in qasms.header.description]`

If not, can this be added?  It is a requested feature.

**Comment by ewinston** [comment]
This should be possible with the `db_filter` argument of `backend.jobs()` but it may require some knowledge of the data format coming back from the api.

**Comment by nonhermitian** [comment]
Yeah, I know about `db_filter`, but I have no idea how to get it to do what I want.  In addition, some things are CamelCased from the API, but they are snake_cased in terra, so searching is less than straightforward unless you are directly copying an example from the docstrings

**Comment by Matt-Stypulkoski** [comment]
If this issue is still relevant, the filter that worked for me that returns `job`s based on their `qobj.header.description` was `db_filter = {'qObject.header.description': <target_qobj_description>}` where `target_qobj_description` is the `qobj.header.description` you are filtering for.

If it is still a feature a lot of people ask about, I could make a Jupyter notebook tutorial explaining how to filter `backend.jobs` briefly and giving examples to some filters, such as this one.

**Comment by nonhermitian** [comment]
I think this resolves itself once the jobs themselves have a name: https://github.com/Qiskit/qiskit-ibmq-provider/issues/118.

The question was asked in lieu of not having this functionality.

**Comment by 1ucian0** [comment]
Since Qiskit/qiskit-ibmq-provider#118 is closed, I'm closing this issue. Feel free to open back.
