### ISSUE TITLE
Terra high-level workflow and PassManager workflow

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1887]
During Qiskit Camp, there were a small discussion about how the high level API should look for a better workflow.
```python
def assemble(circuits, (optional) run_config):
   ...
   return obj

def transpile(circuit, passmanager)
   ...
   return circuit

def synthesize(circuits, compile_conf)
  optimized_circuits = []
  parallel_for circuit in circuits:
    passmanager = choose_pass_manager(compile_conf)
    circuit = transpile(circuit, passmanager)
    optimized_circuits.append(circuit)
  return optimized_circuits

def choose_pass_manager(compile_conf)
   ...
   return passmanager

def execute(circuits, backend):
   compile_conf = backend.configuration
   circuits = synthesize(circuits, compile_conf)
   qobj=assemble(circuits, compile_conf(?))
   backend.run(qobj)
```

Chris made a case for changing the `run_config` header in the Qobj without running `assemble` via, for example, an `update_qobj(qobj, run_config)` function.

**Comment by ajavadia** [comment]
Jay and I discussed some more over the weekend, and we started to converge to something like this. Feel free to comment. PR #1856 is a start of this, but needs a couple follow-ups.

Couple notes:
- `TranspileConfig` is not quite the same as `BackendConfig`. Some things differ, for example what the initial layout should be, or what optimization level to apply. See example below.
- The API should be unified across circuit-level, pulse-level, and algorithm-level (Aqua) programs. Section 2 below shows what this could look like, even though Section 1 is just focused on circuit-level programs.
- The main difference with the above is that `synthesize` is gone, and low-level `PassManager` users are encouraged to use `pass_manager.run()`.

# Section 1: Low-level compile API
## Step 1: transpile circuits
**1a)** transpile circuits and see new circuits, using some high-level transpilation goals
```python
def transpile(circuits, transpile_config):
   # (parallelize over circuits)
   pass_manager = choose_pass_manager(transpile_conf)  # a smart function
   new_circuits = pass_manager.run(circuits)
   return new_circuits

# example usage:
transpile_config = qiskit.compiler.TranspileConfig(
   basis_gates=['u3', 'cx'],
   coupling_map=[[0,1], [0,2], [1,3], [3,4]],
   initial_layout=[qr0[2], qr0[1], qr0[0], None, qr1[0]],
   optimization_level=2
)
new_circuits = qiskit.compiler.transpile(circuits, transpile_config)
```

**1b)** customize pass manager: for those who want to specify exactly which transpiler passes to run
```python
pass_pipeline = [
  qiskit.transpiler.passes.Unroll(basis_gates=['u1', 'u2', 'u3', 'cx']),
  qiskit.transpiler.passes.LookaheadSwap(coupling_map=[[0,1], [0,2], [1,3]]),
  qiskit.transpiler.passes.Optimize1qGates()
]
pass_manager = qiskit.transpiler.PassManager(pass_pipeline)
new_circuits = pass_manager.run(circuits)
```

## Step 2: assemble a runnable qobj 
(either a openqasm-type qobj or openpulse-type qobj). 
These methods are not smart, they just serialize the experiments and write some config/headers.
```python
def assemble_circuits(circuits, run_config):
   ...
   return qobj

def assemble_pulses(pulse_schedule, run_config):
   ...
   return qobj

# example usage:
run_config = qiskit.compiler.RunConfig(
   shots=1024,
   memory=True,
   simulator_seed=12,
   noise_model=qiskit.aer.NoiseModel(depolarizing_noise)
)
qobj = qiskit.compiler.assemble_circuits(circuits, run_config)
```

## Step 3: run the qobj
```python
job = backend.run(qobj)
while job.status() != 'DONE':
   wait(5)
job.result()
```


# Section 2: High-level `execute()` API
for the high-level user who doesn't care what transformations are done, just wants result.
```python
# executor of circuit-level programs
def execute_circuits(circuits, backend, transpile_config, run_config):
   new_circuits = qiskit.compiler.transpile(circuits, transpile_config)
   qobj = compiler.assemble_circuits(circuits, run_config)
   job = backend.run(qobj)
   return job

# executor of pulse-level programs (will go in terra)
def execute_schedule(schedule, backend, schedule_config, run_config):
   new_schedule = qiskit.compiler.reschedule(schedules, schedule_config)  # this is when we have pulse optimizers
   qobj = qiskit.compiler.assemble_schedules(schedules, run_config)
   job = backend.run(qobj)
   return job

# this is in aqua as a high-level algorithm executor
def execute_algorithm(schedule, backend, transpile_config, run_config):

# we may provide a generic `execute()` that overloads all of the above.
```

`execute()` wraps steps 1, 2, 3 above.
Question: is there value in another wrapper `compile()` that wraps only steps 1 and 2, as we have now? i.e. takes circuits to qobj.

**Comment by jaygambetta** [comment]
Sum changes a bit -- I still want to keep an `execute` as well that just takes lots of inputs so that this does not break old code. I dont think we should make people make the run_config and transpile_config by hand if they just want to change the shots.

**Comment by jaygambetta** [comment]
compile I just want to understand the use case. If it is the compile one run on different backends then I think we should encourage the user to give it a new run_config not just assume it will run on backend2.

```python 
new_circuits = transpile(circuits, trans_config)
qobj = assemble_circuits(new_circuits, run_config)
backend.run(qobj)
qobj2= update_qobj_header(qobj, shots = 10000)
backend2.run(qobj2)
```
of course we could assemble it again but if all we are changing is the header we should have a function for this so that it goes from O(N) to O(1).

**Comment by ajavadia** [comment]
Ok I agree with this. My only thing about compile is backward compat, but I guess calling the transpiler then assembler isn't horrible.

Another fairly common use case is the high-level user who wants to run a circuit as-is. Now they would have to do the following. I don't have a problem with it, but some may think it's too much if they just want to skip the transpiler.

```
run_config = qiskit.compiler.RunConfig(shots=1024)
qobj = qiskit.compiler.assemble_circuits(circuits, run_config)
backend.run(qobj)
```

**Comment by jaygambetta** [comment]
It is one extra line I am fine with this.

**Comment by eddieschoute** [comment]
I was mostly interested in the value that having a PassManager adds. Specifically, it seems that the `PassManager.run: DAG → DAG` is function composition of the `run: DAG → DAG` functions of each individual `Pass` with some control code. The control code is left unspecified in the above, so could you clarify how that is going to work? E.g. when you want to iterate certain groups of passes or do conditionals.
One can imagine an alternative approach where from each Pass a `run: DAG→DAG` is constructed through partial application of configuration parameters and those are then chained together. (One could even mandate that any Pass object implements the `__call__` function with type DAG→DAG.) But now the user has exact control in Python (instead of a perhaps a config language) of the control code and how the passes are chained together.

**Comment by ajavadia** [comment]
@eddieschoute I think your example does make things much simpler, and I do like simplicity, but consider the following cases that a pass manager has been used for:

1- A way for passes to communicate information to each other:
Examples:
   - run a pass that selects a layout (placement), and the following pass find the best swaps.
   - run a pass that finds commuting sets of gates, and the following pass optimizes based on those.

2- A way to compactly express a pass pipeline, so that we may provide several default ones (say defaul_pass_manager1 and default_pass_manager2 corresponding to optimization levels `-O1` and `-O2`).

3- A global orchestrator of passes (receives an initial schedule, but also dynamically making decisions about what pass to run next). e.g. has the `circuit.depth()` reached a fixed point, if not keep applying passes.
@1ucian0 and I did discuss the fact that providing this control code statically to the PassManager (like a config language as you say) kind of seemed like we're reinventing Python, but it seemed good to be able to specify some schedules in a compact way (see 2).

4- A way for passes to specify relationships to each other. This is mainly through saying they require another pass to be run before them.
Examples:
  - In order for the Optimize1qGates pass to work correctly, the circuit has to first be decomposed to a `u1, u2, u3` basis (because those are the only gates that pass understands). So it specifies `Unroller(['u1', 'u2', 'u3', 'cx']) as a requirement.
  - The swappers may end up bringing measurements to the middle of a circuit, creating invalid code for current experiments (that only support final measurements). So they say that they require a pass that puts barriers before measurements, to prevent them from coming forward.

(^Here it is true that one pass can just call another pass, without relying on the pass manager. But the pass manager may be able to make some smart decisions based on knowing the full schedule (for example it knows that the Unroller was just ran, so it doesn't need to run it again).
I agree that the full benefit of this one has not really emerged yet.)

**Comment by ajavadia** [comment]
@jaygambetta
another use case for the `compiler` is that it makes it much easier to debug a qobj.
for example it has happened to me multiple times that I do:
```
job = execute(circuits, backend, initial_layout, seed_mapper)
```
but my job fails. so then I make a tiny change (`execute -> compile`) and look inside the qobj.

Right now we have removed compile, and the signature of execute is quite different from that of transpile and assemble, which makes it cumbersome to do this.

**Comment by eddieschoute** [comment]
> @eddieschoute I think your example does make things much simpler, and I do like simplicity, but consider the following cases that a pass manager has been used for:
> 
> 1- A way for passes to communicate information to each other:
> Examples:
> 
>     * run a pass that selects a layout (placement), and the following pass find the best swaps.
> 
>     * run a pass that finds commuting sets of gates, and the following pass optimizes based on those.

I think this would fit nicely into my formalism as well.
```py
input_circuit = ...
while input_circuit:
  layout = find_layout(circuit)
  swap_circuit = implement_layout(layout)
  output_circuit += swap_circuit
 #could mutate input in-place or output a new input_circuit
  output_circuit += execute_gates(input_circuit)
```
Now, admittedly, this is different from the DAG→DAG formalism. But I don't quite see how that would be nicely implemented in a pass either.
```py
circuit = ...
commuting_gates = analyse_commutativity(circuit)
# commuting_gates is not recomputed every iteration
while x:
  optimize_pass = CommutativityOptimizer(commuting_gates)
  circuit = optimize_pass(circuit)
 # or
  circuit = CommutativityOptimizer.pass(circuit, commuting_gates)
  # or make commuting_gates arg optional, and it will compute it every iteration (also easier to use).
  circuit = CommutativityOptimizer.pass(circuit)
```

> 2- A way to compactly express a pass pipeline, so that we may provide several default ones (say defaul_pass_manager1 and default_pass_manager2 corresponding to optimization levels `-O1` and `-O2`).

This can be defined as a function too. Any `default_pass_manager` equals the function `default_pass_manager.pass`. Therefore, it could be defined as function too. (Or perhaps as an argument `optimize_level = 1`)


> 3- A global orchestrator of passes (receives an initial schedule, but also dynamically making decisions about what pass to run next). e.g. has the `circuit.depth()` reached a fixed point, if not keep applying passes.
> @1ucian0 and I did discuss the fact that providing this control code statically to the PassManager (like a config language as you say) kind of seemed like we're reinventing Python, but it seemed good to be able to specify some schedules in a compact way (see 2).

Why can't you do this in Python?
```py
circuit = ...
while circuit.depth() > 5:
  circuit = optimize_pass(circuit)
```

> 4- A way for passes to specify relationships to each other. This is mainly through saying they require another pass to be run before them.
> Examples:
> 
>     * In order for the Optimize1qGates pass to work correctly, the circuit has to first be decomposed to a `u1, u2, u3` basis (because those are the only gates that pass understands). So it specifies `Unroller(['u1', 'u2', 'u3', 'cx']) as a requirement.
> 
>     * The swappers may end up bringing measurements to the middle of a circuit, creating invalid code for current experiments (that only support final measurements). So they say that they require a pass that puts barriers before measurements, to prevent them from coming forward.
> 
> 
> (^Here it is true that one pass can just call another pass, without relying on the pass manager. But the pass manager may be able to make some smart decisions based on knowing the full schedule (for example it knows that the Unroller was just ran, so it doesn't need to run it again).
> I agree that the full benefit of this one has not really emerged yet.)

Would the pass manager automatically insert missing passes or throw an error at runtime? If the latter, then a simple assertion at the beginning of each pass would achieve the same thing. Moreover, (required) arguments flag more clearly to the user that there are prerequisites to a function than documentation describing it.

**Comment by 1ucian0** [comment]
PassManager on the side (we can have another discussion issue about it) I think the original issue is solved.

**Comment by eddieschoute** [comment]
What was the original issue besides discussing the design of PassManager and the workflow?

**Comment by 1ucian0** [comment]
By high-level workflow API I meant the top level functions to generate a QObj.

**Comment by ajavadia** [comment]
Let's keep this open since it contains important discussions that must be considered (probably after this upcoming release). I'll update the issue title.

**Comment by mtreinish** [comment]
I'm going to close this as it is no longer relevant and we've built a lot of the interfaces being discussed here (some time ago). If I'm missing something or there is still more to discuss on this please feel free to reopen this.
