### ISSUE TITLE
latex drawer cannot draw custom gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1942]
### What is the expected enhancement?
Currently only the text drawer is able to do this. This capability is useful when defining hiearchical circuits.

Also refer to #1939 for a discussion of how to draw these.

**Comment by mtreinish** [comment]
I'm a bit confused by how to start working and testing the implementation for this. Based on all the examples in #1939 this is dependent on #1816 before we can implement this. Or am I missing something?

**Comment by mtreinish** [comment]
I pushed up a branch (not a PR yet) with a WIP implementation for how this would be implemented here: https://github.com/mtreinish/qiskit-core/commit/e358db2bae6fa8193e896184d11e915453ee255c

Having an example script to add a custom gate to the circuit with current master (not a PR) would be ideal because then I can actually test this. The code in the latex module is hairy enough without actually testing a bunch of edge cases this is unlikely to work completely on my first try.

**Comment by ajavadia** [comment]
Yeah #1816 needs to be merged to test this. That is close to being merged though.

You can maybe implement it on top of 1816 and test for now, rebase later.

**Comment by mtreinish** [comment]
I just tested https://github.com/mtreinish/qiskit-core/commit/e358db2bae6fa8193e896184d11e915453ee255c  with #1816 applied locally and it works after a small tweak (the numeric arg to `\multigate` was off by one). So I pushed up #2049 with the version I tested locally.
