### ISSUE TITLE
need function to get TranspileConfig for a backend

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1953]
### What is the expected enhancement?

The `qiskit.compiler.transpile()` function is to be decoupled from a monolithic `backend`, in favor of transpiling for some TranspileConfig options (basis_gates, coupling_map, initial_layout, optimization_level, etc.)

Still, we need a convenience function that makes it easy to get these TranspileConfig options from a backend.

```
transpile_config = qiskit.compiler.default_transpile_config(backend)
```

this would populate a `transpile_config = TranspileConfig(basis_gates, coupling_map)`, and the user still has the option to add more fields like `transpile_config.seed_mapper = 10`.

**Comment by ajavadia** [comment]
@jaygambetta in your PR you wrote this function as:
```
[run_config, transpile_config] = default_compiler_configs(backend)
```

but what does it mean to return a `run_config`? if there's not an overwhelming usecase for this I'd rather keep the function returning a single output for ease of use.

**Comment by nonhermitian** [comment]
In my opinion this idea of throwing everything into a config object just makes our software harder to use.  The user has to learn yet another object.  There is some benefit for having less used options in a config, but things like `coupling_map` and `basis_gates` should not be in the config class.  The compile should probably look more like:

```python
compile(circuits, coupling_map, basis_gates=None,
        initial_layout=None, shots=1024, config=TranspileConfig())
```

where everything else is in the config.  Then the `backend` instance should allow for doing `backend.coupling_map` and `backend.basis_gates` since they are fundamentally the key things you want.  Then, in the simplest case you can do:

```python
backend = IBMQ.get_backend('ibmqx4')
compile(circuits, backend.coupling_map, backend.basis_gates)
```

**Comment by taalexander** [comment]
@ajavadia, Is a `RunConfig` not something like the number of `shots`, `rep_time`s, etc.? It can be used to guarantee that two different compiles will create Qobjs that run with the exact same runtime settings? 
@nonhermitian, I think promoting specific configuration variables too first level could set a dangerous precedent for future variables.

**Comment by 1ucian0** [comment]
PR #2166 closes this issue "by making it moot".
