### ISSUE TITLE
dag.depth seems broken

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#1994]
It seems that PR #1815 introduced a bug in `depth()`. 
```
from qiskit import QuantumRegister, QuantumCircuit
from qiskit.converters import circuit_to_dag

qr = QuantumRegister(2)
circuit = QuantumCircuit(qr)
circuit.h(qr[0])
circuit.h(qr[1])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[1], qr[0])
circuit.cx(qr[1], qr[0])
dag = circuit_to_dag(circuit)

assert dag.depth() == 7
```

**Comment by nonhermitian** [comment]
Yes, the depth is zero.  The change to `QuantumCircuit` in #1993, that computes the depth without the DAG, is correct, i.e. 7.

**Comment by 1ucian0** [comment]
The problems is that DAGNodes considers every node with the same name equal. I will have a look...

**Comment by 1ucian0** [comment]
Probably the same issue that @kdk detected here https://github.com/Qiskit/qiskit-terra/pull/1815#issuecomment-474382798.

**Comment by maddy-tod** [comment]
@1ucian0, @kdk and I discussed it and he pointed out that equality in Python is meant to be for when two objects are semantically equivalent which those two `cx` gates are as they have the same parameters. This can easily be reverted by reintroducing the version of the `__eq__` method [here](https://github.com/maddy-tod/qiskit-terra/blob/8c9aa0550488e3dd660898dc5b1c0b9455a98280/qiskit/dagcircuit/_dagnode.py#L87) which checks that the ids of the two operations are also the same.

**Comment by kdk** [comment]
Agree that the current `DAGNode` implementation of `__hash__`/`__eq__` is inconsistent. From https://docs.python.org/3/reference/datamodel.html#object.__hash__ ,
> The only required property is that objects which compare equal have the same hash value; ...

If we want `DAGNode`s to be used as the labels of the networkx graph, we need semantically equivalent gates (as in the example) to be `neq` so that they can be safely hashed and compared ( line `where u != v` in https://networkx.github.io/documentation/stable/_modules/networkx/algorithms/dag.html#dag_longest_path is where the current example goes wrong.)

If that's the path we go, we can remove `DAGNode`s `__hash__`/`__eq__` and add a weaker "semantic equivalence" check to be used in comparing `DAGCircuit`s (which do `__eq__` by semantic equivalence.)
