### ISSUE TITLE
Empty circuits from transpiler fail qobj validation

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2020]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The compiler removes all the gates from this circuit and leaves an empty circuit that fails validation.

```
qr = QuantumRegister(2, 'qr')
circuit = QuantumCircuit(qr)
circuit.h(qr[0])
circuit.h(qr[0])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[0], qr[1])
circuit.cx(qr[0], qr[1])

coupling_map = [[0, 1]]
basis_gates = ['u1', 'u2', 'u3', 'cx', 'id']

backend = BasicAer.get_backend('qasm_simulator')

qobj = compile(circuit, backend=backend, coupling_map=coupling_map, basis_gates=basis_gates)
```

```
ModelValidationError: {'instructions': ['Shorter than minimum length 1.']}
```
### What is the expected behavior?
I believe that a valid circuit returned by the transpiler, in this case an empty circuit, should result in a valid qobj.

**Comment by mtreinish** [comment]
What would you suggest the fix is here? The transpiler is able to optimize that circuit away to include 0 elements. It looks like the validation model for qobj enforces at least 1 element:  https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qobj/models/qasm.py#L53 (man was that irritating to find) for the instructions in the circuit (it's also in a few other places which we should remove at the same time for consistency, but that line is the only one blocking your use case). If we just remove that condition it should work fine. I don't anything in the qobj spec actually says there need to be any items in instructions, just that the element is there.

**Comment by nonhermitian** [comment]
I would remove the restriction.

**Comment by mtreinish** [comment]
Ok works for me, I was leaning that way too. The patch is up at: #2048
