### ISSUE TITLE
Latex circuit output completely different from text and mpl methods

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2033]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
size = 5
q = QuantumRegister(size, 'q')
qc = QuantumCircuit(q)

qc.h(q[0])
qc.h(q[1])
qc.h(q[2])
qc.h(q[3])
qc.h(q[4])
qc.y(q[2])
qc.cx(q[0], q[3])

qc.t(q[2])
qc.ccx(q[1], q[4], q[0])
qc.x(q[4])
qc.cx(q[3], q[4])
qc.x(q[2])
qc.s(q[2])
```
<img width="400" alt="Screen Shot 2019-03-28 at 5 02 56 AM" src="https://user-images.githubusercontent.com/1249193/55144270-d4a19380-5116-11e9-832d-d4566b9ab3dc.png">

<img width="481" alt="Screen Shot 2019-03-28 at 5 03 02 AM" src="https://user-images.githubusercontent.com/1249193/55144277-d9664780-5116-11e9-8b19-4bee0356235a.png">

<img width="726" alt="Screen Shot 2019-03-28 at 5 03 11 AM" src="https://user-images.githubusercontent.com/1249193/55144291-df5c2880-5116-11e9-9a3f-2b6f2bc8486c.png">

**Comment by maddy-tod** [comment]
Hi @nonhermitian I think this is because the Latex drawer doesn't accept the `justify` parameter yet, but there is an open PR for this #1977. Running your code against this branch I get
![image](https://user-images.githubusercontent.com/40489777/55144775-71752880-5139-11e9-8219-a701d1c8d0a9.png)
which is the same as the mpl and text outputs.

**Comment by nonhermitian** [comment]
Ok cool. Will close this then since fix is coming.
