### ISSUE TITLE
Helper function for pulse to auto align measurement

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-terra#2067]
It can be helpful if all schedules in an experiment have measurements that occur at the same physical time after the start of the schedule (particular for level 2 measurement). This would be a helper function that would offset schedules appropriately and add measurements/acquires automatically. Also this would enforce any constraints on minimum wait times for the measurement (e.g. to ensure enough time for the calibration schedules which are added by the hardware).

**Comment by taalexander** [comment]
This method should:
1. Search through the schedule in conjunction with `meas_map` and find acquires which do not fill out a `meas_map` instance. In such a case default acquires of equal duration should be inserted on qubits in `meas_map` instance that were not already being measured. 
2. If `cmd_def` is provided as argument all instructions should be shifted so that acquires happen after the longest `u2` gate in the `cmd_def`. This is so that sufficient time is available on devices to peform calibration experiments.

**Comment by ajavadia** [comment]
Moving this to 0.9 milestone as it doesn't seem like it'll be done for 0.8.
