### ISSUE TITLE
Latex drawer produces error when barriers are included in the circuit

### ISSUE THREAD

**Issue by kgeorgopoulos2** [Qiskit/qiskit-terra#2187]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### Current behavior
When i try to produce a Latex output for my circuit that has barriers, it produces an error that looks like this:
`Command '['pdflatex', '-halt-on-error', '-output-directory=/var/folders/qf/k4kkwsxn40gdvddkffd8_jv8xt8k_b/T/tmpo4n4jze0', 'circuit.tex']' returned non-zero exit status 1.`
On the other hand, when I  try to create the Latex without the `.barrier()` command, the circuit is drawn perfectly fine. 

I tried to run the tutorial, which includes Latex outputs that have barrier, but that one gave me an error as well.

I am using the usual imports, am I missing something? I am working on MacOS.

**Comment by mtreinish** [comment]
What version of terra are you using. If you're using something >=0.7.0 then there should be an error message that says look at the log file (and it generates a log file that contains the output of pdflatex). That being said since you've ruled it down to the use of barriers, my guess is that your version of qcircuit in latex is out date. You need to have the latest version of [qcircuit](https://ctan.org/pkg/qcircuit), 2.6.0, installed for latex to have the `\barrier` command to draw them.

**Comment by kgeorgopoulos2** [comment]
I just needed to update qcircuit, I don't know why I didn't think of that earlier. Thank you very much for the help :)
