### ISSUE TITLE
Unroller and Decompose overwrite input dag object

### ISSUE THREAD

**Issue by quantumhamiltonian** [Qiskit/qiskit-terra#2192]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.6.7
- **Operating system**: Ubuntu

### What is the current behavior?

The method `run` in classes `Unroller` and `Decompose` changes the input dag object.

### Steps to reproduce the problem

When executing `run`, e.g.:
```
dag = circuit_to_dag(circuit)
deco = Decompose()
newdag = deco.run(dag)
```
The object dag will be overwritten by the output of `Decompose().run`.

### What is the expected behavior?

The passed input object `dag` should not change. (Unless this is an expected behaviour due to performance aspects, which should be mentioned in the documentation).

### Suggested solutions

Make a deepcopy of the dag input in `Decompose().run` and in `Unroller().run`, e.g.:
```
import copy
newdag = copy.deepcopy(dag)
[...]
return newdag
```
This suggested fix was tested with transpiler unittests and was running successfully.

**Comment by 1ucian0** [comment]
This should be solved with an immutable DAG.

**Comment by kdk** [comment]
Agree that an immutable DAG would solve this, but this is still fixable with the current DAG. We haven't been great about adhering to "passes shouldn't modify the input DAG" policy, in general. We could review existing passes, document current behavior, and at least fix simple cases with e.g. a deepcopy and check performance implications (and add tests around preservation of the input dag).

**Comment by 1ucian0** [comment]
I see this coming, a deepcopy at the beginning of the run will be expensive. :)

**Comment by ajavadia** [comment]
Yeah this is related to: https://github.com/Qiskit/qiskit-terra/issues/1435 

It is something we should fix and have tests for, but I'm a little worried about the performance penalties of doing this a few days before the release (unless it is not that bad? do we have some rough numbers?)

So I'd like to understand the bug report a bit better. @quantumhamiltonian what is the context here? Did you get a bug in your code when working with these passes?

Because if you work at the level of circuits (and not DAG), it should be ok. The conversion from circuit->DAG has an inherent copy, therefore the original circuit remains untouched. 

```python
from qiskit import QuantumCircuit
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes import Unroller

circuit = QuantumCircuit(2)
circuit.ch(0, 1)

pass_ = Unroller(['u3', 'cx'])
pm = PassManager(pass_)
new_circuit = pm.run(circuit)   # circuit remains untouched
```

**Comment by quantumhamiltonian** [comment]
@ajavadia So I get the bug while working my own context, therefore in no qiskit routine from the homepage. But I am wondering, why you can give a circuit as input for the Unroller. The way I understand the documentation, the input-parameter for both must be a DAG. I would be lucky if you can explain me why it works in your case.

**Comment by ajavadia** [comment]
The unroller works on DAG. We just recently added a `PassManager.run()` method for simplified usage of running a pass manager on a circuit. It goes to DAG internally and comes back to circuit again. Similar to `transpile(circuit, basis_gates)` for example that internally goes to DAG.

These are currently our public user facing functions. There are hidden copies in these conversions, which is why I am not too worried about the bug you raise. It should be fixed, but only someone that directly works with the DAG will see them for now.
