### ISSUE TITLE
new copyright header

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2232]
### What is the expected enhancement?
The following copyright needs to replace the old one in all the files:

```python

# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, XXXX.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.
```
where `XXXX` is the year of the file in question.

**Comment by mtreinish** [comment]
The (C) doesn't actually mean anything, and I'm not sure we need the GPL style "this code is part of Qiskit". But, I'm fine with the [normal Apache header](http://www.apache.org/licenses/LICENSE-2.0#apply) instead of what we normally do.

**Comment by mtreinish** [comment]
Also if we really want things to be consistent we should have this machine enforced by the style rule checker. Otherwise we'll eventually slip on this. I've written rules like this before (see: https://opendev.org/openstack/hacking/src/branch/master/hacking/checks/comments.py#L49-L93 and https://opendev.org/openstack/hacking/src/branch/master/hacking/checks/comments.py#L112-L170 ) the same rule shouldn't  be that much harder to write in pylint.

**Comment by 1ucian0** [comment]
https://www.ibm.com/legal/copytrade refers to `Copyright IBM Corporation` instead of `Copyright IBM`. I have no idea about the difference. Probably is a good moment to involve a lawyer?

**Comment by diego-plan9** [comment]
It seems some of the files still contain the old header, most likely because they were caught under friendly fire during the busy release period - I'll make a round of PRs aiming to adjust them according to the header posted in the issue description.
