### ISSUE TITLE
latex drawer: justifying doesn't work for custom gates

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2235]
### What is the expected enhancement?
Boxes get overlapped in the latex drawer. In the example below I have 3 boxes: a 1-qubit unitary, a 2-qubit unitary, and a 2-qubit custom opaque gate.

```python
from qiskit.circuit import QuantumRegister, QuantumCircuit
from qiskit.circuit import Gate
from qiskit.quantum_info.random import random_unitary
qr = QuantumRegister(3)
qc = QuantumCircuit(qr)
U1 = random_unitary(2)
U2 = random_unitary(4)
opaque_gate = Gate(name='opaque_gate', num_qubits=2, params=[])
qc.append(U1, [qr[1]])
qc.append(U2, [qr[0], qr[1]])
qc.append(opaque_gate, [qr[1], qr[2]])
qc.draw(output='latex', justify='left')
```

![image](https://user-images.githubusercontent.com/8622381/56903233-ddfd8300-6a69-11e9-8810-537e3c51d1e1.png)

Maybe an issue with justification? Though I was not able to fix this by tweaking the `justify` param.

PS. The underscore in the opaque_gate name should also render better.

**Comment by mtreinish** [comment]
Hmm, I'm thinking the layers for justification isn't interpreting things the same way the latex is drawing them so we end up drawing overlapping boxes. @maddy-tod you're more familiar with the layers and justification does this seem like what's going on? Either way I'll check the raw latex output, because I didn't actually think that would render. (I expected xypic to return an error, but it might be an edge case in the multigate).

As for the text, the easiest way would be to just use: https://pypi.org/project/pylatexenc/ as pass all the gate display text through that.

**Comment by mtreinish** [comment]
#2246 will fix the name issue, but I still have to look into the overlapping gate drawings
