### ISSUE TITLE
Unit tests fail when run locally on OSX

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2345]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**: osx

### What is the current behavior?

Get about 8 of these for the visualization tests:

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

### Steps to reproduce the problem
Run the master-branch tests locally on OSX.

**Comment by mtreinish** [comment]
I can think of two ways to fix this, either we add `@unittest.skipUnless(qiskit.visualization.HAS_MATPLOTLIB)` on those 8 tests. Or we can set a backend in the test base class so that we use the same backend (and likely something not interactive) in all environments. That's what we do for CI using an environmental variable but we can just move that to `setUpClass` in the base test class (or add a base visualization class).

**Comment by nonhermitian** [comment]
Ok, I figured this out.  Something somewhere downgraded my matplotlib from 3.0.3 -> 2.2.4.  In doing so, it changed the default backend for mpl from Agg -> macosx.  This is the source of the problem.  Luckily the default for 3.0 does not run into the framework issues.
