### ISSUE TITLE
cmd_def expression extraction should be replaced with math expression parser 

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#2348]
### What is the expected enhancement?
Pulse commands supplied by the backend may be parameterized with some expression that includes math performed on parameters of the form `P#`. Examples of valid strings are
```
P1
-(P1)
cos(pi)*P1
1+1+P1
P1/P2
...
```
Currently, parameters are extracted by first sanitizing the untrusted string supplied by backends to only math and then passing to Sympy parser for parameter extraction as [Sympy parsing is known to be unsafe due to its use of `eval`](https://docs.sympy.org/latest/modules/core.html). Sanitization is notoriously hard to implement correctly, and while it currently is mostly sufficient as the majority of backends are assumed to be trusted. 

Rather than using a sanitization + Sympy, a parser for the limited subset of math and expressions required should be implemented. This parser should output a Qiskit expression with parameters.

**Comment by nkanazawa1989** [comment]
I found the `cmd_def` returns some fc phases in the format such as `np.pi*0.5`, and it returns `ParametrizedSchedule` because the value is classified as a parameter. Also, parameters such as `-(P#)` returns unsafe expression error. New parser should fix these bugs.

I have implemented shunting yard based math parser in pulse simulator. Maybe I can build some parser for `cmd_def` as well.

**Comment by taalexander** [comment]
The first bug you note has already been fixed in master.

It would be great if you could implement the math parser for terra.
