### ISSUE TITLE
latex drawer: missing gates and params

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2388]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
from qiskit import QuantumRegister, QuantumCircuit

qr = QuantumRegister(3)
qc = QuantumCircuit(qr)

qc.h(qr[0])
qc.cu1(0.1, qr[1], qr[0])
qc.cu1(0.2, qr[2], qr[0])
qc.h(qr[1])
qc.cu1(0.3, qr[1], qr[2])
qc.h(qr[2])

qc.draw(output='latex')
```

results in two missing hadamards and a missing parameter (0.1)
![image](https://user-images.githubusercontent.com/8622381/57479791-40c1fc00-726c-11e9-9d23-dc938c1d0867.png)

The culprit is #1977. Before that commit, it shows correctly (except for the bad spacing which is a separate issue (#693):
![image](https://user-images.githubusercontent.com/8622381/57479869-71099a80-726c-11e9-9d6e-d8ecc5351daf.png)

**Comment by ajavadia** [comment]
@maddy-tod can you take a look please?

**Comment by mtreinish** [comment]
@maddy-tod I started working on this because at first it seemed quick and easy. But, I just realized there is a further complexity to it, which I explained in: https://github.com/Qiskit/qiskit-terra/pull/2389#issuecomment-491048567 I'm not sure when I'll be able to circle back to it, but feel free to push commits to that PR's branch to continue it if you get a chance to look before me.
