### ISSUE TITLE
remove pylatexenc as required dependency

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2417]
### What is the expected enhancement?
pylatexenc is used in a relatively minor place for formatting latex_drawer's strings. Given that everything associated with latex drawing is optional itself, this part should also be optional and not a core dependency of terra.

**Comment by mtreinish** [comment]
Well that's not entirely the case, we also have pillow in requirements which is also only used for latex drawing. The thing which is optional is the external dependencies like pdflatex and the latex requirements (because we don't have a mechanism to require them). I'd actually argue that pillow should be optional but not pylatexenc, mostly because pylatexenc is used by the latex_source backend which has no other external dependencies and just returns a string.

**Comment by ajavadia** [comment]
pillow should also be optional.
This was the point of creating a text drawer so that we could make the dependencies light. Terra is very much usable without them.
I think all of these should be part of the extra visualization requirements -- along with matplotlib, nxpd, ipywidgets, pydot that are already there.
