### ISSUE TITLE
Improved error message for overlapping pulses

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#2523]
### What is the expected enhancement?
The current pulse overlap error message reads: `PulseError: 'Child schedules <Schedule 0>, <Schedule 1> overlap.'`

For a user building pulse schedules, it would be nice for the error to give more information about how they overlapped, so the user could more easily debug their mistake.

(For example, in my case, schedule 0 involved only qubit 0, and I thought schedule 1 involved only qubit 1, but I was actually measuring qubit 1 into mem slot 0, causing the conflict.)

**Comment by nkanazawa1989** [comment]
This is the code to reproduce what @lcapelluto pointed as an example case:
```python
system = pulse.PulseChannelSpec.from_backend(backend)

sched0 = pulse.Schedule()
sched0 |= pulse.Acquire(10)(qubits=system.qubits[0], mem_slots=system.memoryslots[0])
sched1 = pulse.Schedule()
sched1 |= pulse.Acquire(10)(qubits=system.qubits[1], mem_slots=system.memoryslots[0])

sched0 |= sched1 # this raises an error
```

I got an error message below and I think error message has been improved.
```
PulseError: 'Timeslot: Timeslot(MemorySlot(0), (0, 10)) overlaps with existingTimeslot: Timeslot(MemorySlot(0), (0, 10))'
```
But this is still not sufficient for novice users, especially who don't know `__repr__` of `TimeSlot`. This is because error message just reuse representation of TimeSlot object. We can rewrite error message to be like
```
Timeslot: MemorySlot(0) t=[0, 10] overlaps with existing Timeslot: MemorySlot(0) t=[0, 10]
```

We can get more confusing case by rewriting `sched1` as 
```python
sched1 |= pulse.Acquire(100)(qubits=system.qubits[1], mem_slots=system.memoryslots[0])  << 5
```

The error message is now
```
PulseError: 'Timeslot: Timeslot(MemorySlot(0), (5, 105)) overlaps with existingTimeslot: Timeslot(MemorySlot(0), (0, 10))'
```

Actually, in above schedule, a section where two schedules are overlapped is [5, 10], but error message says whole section of sched1 is overlapped. In this case, error message should be
```
PulseError: 'Input schedules has overlap in MemorySlot(0) t=[5, 10]'
```

**Comment by nkanazawa1989** [comment]
Sorry, I noticed we have another option to reproduce the example case.
```python
sched = pulse.Schedule(sched0, sched1)
```

Then I got an error
```
PulseError: 'Child schedules (Schedule(0, (0, Instruction(Acquire(acq14, duration=10, kernel=None, discriminator=None), AcquireChannel(0), MemorySlot(0)))), Schedule(5, (5, Instruction(Acquire(acq15, duration=100, kernel=None, discriminator=None), AcquireChannel(1), MemorySlot(0))))) overlap.'
```
You're right. This is not readable.

@IceKhan13 thanks for pointing out simple solution. we have two things to be done.

1. Rewrite below error message
https://github.com/Qiskit/qiskit-terra/blob/277407c0550cf8e4cfc0e1844113594933efa903/qiskit/pulse/timeslots.py#L284

2. throw the message to Schedule. Representation object of schedule should be replaced by more readable one.
