### ISSUE TITLE
Import of qiskit causes console window to be opened many times

### ISSUE THREAD

**Issue by eendebakpt** [Qiskit/qiskit-terra#2615]
### Information

- **Qiskit Terra version**: 0.8.1
- **Python version**: 3.6.8
- **Operating system**: Windows 10

### What is the current behavior?

If I import qiskit a console window is opened and closed many times. It is due to the execution of 
``` 
cmd=['c:\\projects\\venv\\scripts\\pythonw.exe', '-m', 'pip', 'freeze']
reqs = subprocess.check_output(cmd)
```
in `qiskit\version.py` (line 29, in `_get_qiskit_versions`)

### Steps to reproduce the problem

Import qiskit with the following command:
```
import qiskit
```

### What is the expected behavior?

Qiskit should be important without side effects.

### Suggested solutions

The issue seems to be the same as described in https://stackoverflow.com/questions/6390394/executing-subprocess-from-python-without-opening-windows-command-prompt, however the sollutions suggested there do not work.

**Comment by mtreinish** [comment]
Can you give https://github.com/Qiskit/qiskit-terra/pull/2497 a try to see if this fixes this. The latest commit I just added to the PR (https://github.com/Qiskit/qiskit-terra/pull/2497/commits/1f786fe5f257266602568b71b81269fd765eee32) adjusts how we call subprocess to run the pip command for `__qiskit_version__` to be the updated way for the git commands being added there. I think that might fix the issue (since it nukes the env except for what's needed) and want to see if it actually fixes this (since I don't have simple access to a windows environment).

**Comment by eendebakpt** [comment]
@mtreinish Seems to work. (I did run some commands manually, as I cannot compile qiskit-terra on my system)

**Comment by mtreinish** [comment]
@eendebakpt ok cool, then I'll add a fixes tag to that PR to mark that once that merges it'll fix this.
