### ISSUE TITLE
BackendConfiguration should allow None for gates and basis_gates

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2617]
### What is the expected enhancement?
`BackendConfiguration` needs to allow for `gates = None` and `basis_gates =  None` in the model validation in order to allow a pulse-based simulator

**Comment by taalexander** [comment]
Could you instead pass an empty list?

**Comment by nonhermitian** [comment]
I could remove the min length requirements instead of allowing None. But this may make the checks for gate backends less robust.

**Comment by taalexander** [comment]
This is the approach that was taken for other simulator parameters. Although a better choice might be to have an `open_qasm` flag.

**Comment by diego-plan9** [comment]
I think this topic was raised in other contexts - allowing `None` tends to be problematic, as the consumers of the model no longer have assurances that the attribute will be of the same type (in this case, they cannot rely on `.gates` being a list, and they need to explicitly check for the type instead of just iterating over the value, etc), and in general opens the door to ambiguity in subtle ways.

Actually,  why not make the changes to `PulseBackendConfiguration` instead of `BackendConfiguration`? By using the more specialized class, there might be less constraints and we can keep the checks for Qasm backends to the same level of robustness.

**Comment by nonhermitian** [comment]
Because using `PulseBackendConfiguration` makes things worse:

```python
ModelValidationError: {'dtm': ['Missing data for required field.'], 'n_uchannels': ['Missing data for required field.'], 'rep_times': ['Missing data for required field.'], 'basis_gates': ['Missing data for required field.'], 'qubit_lo_range': ['Missing data for required field.'], 'meas_lo_range': ['Missing data for required field.'], 'gates': {0: {'name': ['Missing data for required field.'], 'qasm_def': ['Missing data for required field.'], 'parameters': ['Missing data for required field.']}}, 'dt': ['Missing data for required field.'], 'discriminators': ['Missing data for required field.'], 'meas_kernels': ['Missing data for required field.'], 'meas_levels': ['Missing data for required field.']}
```

and they still require `gates` and `basis_gates` as well.  In short, the pulse simulator is closer to the qasm backend schema because it does not need most of the stuff above, and the stuff that it does require must be in the qobj itself.

**Comment by taalexander** [comment]
It seems that an empty list of gates and basis gates may be the cleanest solution.

**Comment by nonhermitian** [comment]
#2618 now allows for empty list.
