### ISSUE TITLE
test_examples.TestPythonExamples) (example='stochastic_swap.py') fails locally

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2690]
### Information

- **Qiskit Terra version**: master 
- **Python version**:
- **Operating system**: OSX

### What is the current behavior?
```
======================================================================
FAIL: test_all_examples (test_examples.TestPythonExamples) (example='stochastic_swap.py')
Execute the example python files and pass if it returns 0.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paul/Desktop/Github_repos/qiskit-terra/test/python/test_examples.py", line 52, in test_all_examples
    self.assertEqual(run_example.returncode, 0, error_string)
AssertionError: 1 != 0 : Running example stochastic_swap.py failed with return code 1
stdout:
stderr: Traceback (most recent call last):
  File "/Users/paul/Desktop/Github_repos/qiskit-terra/examples/python/stochastic_swap.py", line 97, in <module>
    after = pass_.run(dag)
  File "/miniconda3/lib/python3.7/site-packages/qiskit_terra-0.9.0-py3.7-macosx-10.7-x86_64.egg/qiskit/transpiler/passes/mapping/stochastic_swap.py", line 107, in run
    if len(dag.qubits()) != len(self.initial_layout):
TypeError: object of type 'int' has no len()
```

### Steps to reproduce the problem
Run tests locally on OSX.  Note that the example itself works fine when run separate, so it is something in the tests that is causing the issue.

**Comment by mtreinish** [comment]
A couple things stand out looking at that stack trace. The first is that it's using an installed egg instead of your local checkout, which makes me think this might be a packaging issue. All the script does is run `sys.executable` -m example_file_path for each of the examples and fail on a non-zero exit code. For whatever reason the python environment that the tests are running in are picking an installed package instead of the git checkout which you probably want it to use. Especially, because the second thing I noticed is that the stochastic_swap code on master doesn't have the line that failed (not at L107 or anywhere else in the module). So it looks like it's failing because the test is passing the current master version of the dagcircuit class to an old version of stochastic swap and there is a mismatch in the return type for `dag.qubits()`.

**Comment by nonhermitian** [comment]
Ahh good find. Let me close till I sort that out.

**Comment by mtreinish** [comment]
FWIW, these oddities and overall level of terribleness with python packaging is why I normally use tox (normally by just calling `tox -epy37` instead of `make test`) to run the tests locally, because it isolates the test execution in a venv. Just to prevent the class of failures that occur by trying to run things in system python (or a larger environment) and also to prevent tests from interfering with my system python environment.
