### ISSUE TITLE
the option to choose ThreadPoolExecutor or ProcessPoolExecutor

### ISSUE THREAD

**Issue by snuffkin** [Qiskit/qiskit-terra#2707]
### What is the expected enhancement?
BasicAerJob automatically chooses ThreadPoolExecutor or ProcessPoolExecutor depend on `sys.platform`.
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/providers/basicaer/basicaerjob.py#L51

This default behavior is good.
But, on my linux environment, I cannot use ProcessPoolExecutor(to say precisely multiprocessing).
So I want the option to choose ThreadPoolExecutor or ProcessPoolExecutor.

**Comment by nonhermitian** [comment]
All platforms will use threadpool soon.

**Comment by snuffkin** [comment]
Hi @nonhermitian !

Thank you for your response.
This problem will be solved soon!

**Comment by mtreinish** [comment]
I'm closing this as since the last release, 0.17.0, basicaer doesn't use an async future anymore and executes jobs synchronously. So a user who wants to run the job async will have to do this themselves (and therefore choose how they want to do that). But, please feel free to reopen this if there is more to discuss or do here.
