### ISSUE TITLE
Performant method for adding large numbers of gates to circuits

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#2854]
`QuantumCircuit` has the following two methods for adding gates to circuits:
- `append`: Broadcast, expand, validate and add a single instruction
- `_append`: (internal) validate and add a single instruction

There's a need for a more efficient means of adding large numbers of instructions to a circuit, specifically in cases where the user does not need broadcasting/expansion and has already validated ops and qargs.

We could a) document and expose `_append` as a user facing function and b) add an additional method (maybe `__append`) which includes only the steps necessary to add an instruction or set of instructions to a circuit (and no verification), with the understanding that users of `_append` (or `__append`) are responsible for validating their instruction and q/cargs.

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP

❓ quantumcircuit.py's `append` has now been changed to append multiple instructions since OP's issue posting. `_append` seems to function as per OP's definition of `__append` (_appends does not check for broadcasting or scoping and is unsafe to use). PR #4169 introduces changes in _append and discusses the overhead expected. PR #7134 Improves scaling performance of append. 

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by jakelishman** [comment]
Closing as `_append` no longer does any validation; it only does the stuff necessary to append an instruction.
