### ISSUE TITLE
Latex barrier bugs

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#2918]
There have been a number of attempts at fixing barriers in the latex drawer (https://github.com/Qiskit/qiskit-terra/pull/1727, https://github.com/Qiskit/qiskit-terra/pull/1534, https://github.com/Qiskit/qiskit-terra/pull/1361), but there are still bugs.

```python
from qiskit import *
qasm = """
OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
cx q[1],q[6];
barrier q[1],q[4],q[5],q[6];
u3(1.8,-0.5,0.4) q[1];
cx q[0],q[1];
"""
circ = QuantumCircuit.from_qasm_str(qasm)
circ.draw(output='latex')
```
![image](https://user-images.githubusercontent.com/8622381/62546337-4b6f3b80-b831-11e9-8595-a2aadb532a84.png)

Bug 1: The barrier should only be on qubits 1, 4, 5, 6 -- but it is on qubits 1 to 4.

Bug 2: It cuts through the U3 gate.

**Comment by guruhegde** [comment]
Hi, I want to try this issue. 

Bug 2: 
* One possible solution is to set the horizontal offset value in `\barrier`. This bug will not occur with a smaller box (`H` gate for ex.). 
* Another solution is to make U3 gate use 2 columns. The first column will have `\qw`. This way
U3 box will not overlap with barrier column.
I tested both. Please suggest if you have any other idea.

**Comment by ajavadia** [comment]
Hi, I think this has to depend on the width of the gate in question. It's not just U3, it happens with other gates such as U1 and U2 as well. So I'm good with any solution that works but it should not hardcode to certain gates and be general. Thanks.

**Comment by guruhegde** [comment]
Details of the problem - for barrier one column space (say `A`) is allocated. But in the circuit image, barrier location (where it appears)  depends on the next column (say `B`) width - `-0.95em` from the center of the `B`. Boxed gates with single characters won't overlap, but for others, there will be overlap.
The proper fix is to place the barrier in the column space allocated for it using `offset` value arg, which is in `em` unit. 

I am not sure how to map column width(in characters) to `offset` value, so that solution is generic.
What I have in mind - If `op` is multi-character gate and previous column contains barrier, set
offset` = -4.0em else `offset` = -1.65em` (lesser value).
One plus is fix will be local (All change happens in one place).

@ajavadia What do you suggest?

**Comment by guruhegde** [comment]
Thanks for the explanation!

There is one more idea - When barrier op is present, add `\qw` in a new column, but append ` \barrier[0em]{*}` to the previous column. This way barrier location would be fixed.
@mtreinish What is your opinion on this?

**Comment by guruhegde** [comment]
I raised a PR to test the changes. I tested manually with simple circuits (few found in previous bug reports) and so far good. Also tried circuits in this link - qiskit/advanced/terra/3_advanced_circuit_visualization.ipynb. I didn't find any issue.

Fix added here - https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/visualization/latex.py#L626-L634 and https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/visualization/latex.py#L743-L753 can be removed right? Can you point me where test circuits for those changes can be found?
