### ISSUE TITLE
Custom multiqubit gates overlap

### ISSUE THREAD

**Issue by maddy-tod** [Qiskit/qiskit-terra#3063]
### Information

- **Qiskit Terra version**: master

### What is the current behavior?
Custom multiqubit gates can overlap other gates. 
![image](https://user-images.githubusercontent.com/40489777/64109983-c6683b00-cd78-11e9-9bcd-a3e5e11f0f35.png)
I think this is because the width of a layer has to be an integer, and this is what happens when the layer is given a width of 2. The result for a width of 3 below is obviously still not desirable but at least there is not overlap.
![image](https://user-images.githubusercontent.com/40489777/64110058-fa436080-cd78-11e9-9a58-774413a6d931.png)

### Steps to reproduce the problem
```python
q = QuantumRegister(3)
c = ClassicalRegister(3)
circ1 = QuantumCircuit(q, c, name='my instruction')
circ1.measure(1, 1)
inst = circ1.to_instruction()

circ2 = QuantumCircuit(q, c, name='circ2')
circ2.h(0)
circ2.append(inst, q[:], c[:])
circ2.draw(output='mpl')
```
### What is the expected behavior?
The custom gate is drawn a suitable distance away from the previous gate

### Suggested solutions
Look at how to modify where the gate is plotted, maybe by taking more into consideration in `Anchor.plot_coord()`

**Comment by Matt-Stypulkoski** [comment]
Would it be possible to adjust the way in which the `layer_width` is calculated? I looked into the `_draw_ops()` function, specifically the part that gets executed when drawing a custom gate with a name longer than 4 chars.

The way it currently is now, I see a few possible scenarios:
1) `box_width <= 1`, which causes `box_width` to be set to 2 and `layer_width` to be set to 2 
2) `box_width == 2`, which causes `layer_width` to be set to 2
3) `box_width > 2` which causes `layer_width` to be set to `box_width * 2`

The problem lies in scenario 2, where `box_width` and `layer_width` are the same causing the overlap. The overlap does not happen for larger `box_width`s, but the spacing between the custom gate and the adjacent gates can get pretty large depending on the box_width.

My suggestion was to replace this block of code:
```
if box_width <= 1:
    box_width = 2
    if layer_width < box_width:
        if box_width > 2:
            layer_width = box_width * 2
        else:
            layer_width = 2
```
with this:
```
layer_width = math.ceil(box_width * 1.5)
```

I've tested drawing the circuit with this code and the gates seem to be fairly close together without any gate overlap. There is some text overlap, but I currently see that without my changes as well. From what I can see, the code being replaced by this should not affect anything else, but if you see anything I might have missed, please let me know.

Here are some examples of the `circuit.draw(output='mpl')` with this change:
`box_width == 1`
<img width="286" alt="Screen Shot 2019-09-10 at 4 21 39 PM" src="https://user-images.githubusercontent.com/50181769/64647753-98719f00-d3e7-11e9-8d8f-13c141ee10f7.png">

`box_width == 2`
<img width="352" alt="Screen Shot 2019-09-10 at 4 23 36 PM" src="https://user-images.githubusercontent.com/50181769/64647754-98719f00-d3e7-11e9-94fb-07df0464e4bd.png">

`box_width == 3`
<img width="440" alt="Screen Shot 2019-09-10 at 4 23 49 PM" src="https://user-images.githubusercontent.com/50181769/64647755-98719f00-d3e7-11e9-93a2-695152e82f0e.png">

`box_width == 4`
<img width="481" alt="Screen Shot 2019-09-10 at 4 24 02 PM" src="https://user-images.githubusercontent.com/50181769/64647756-98719f00-d3e7-11e9-94dc-12c3a0347d02.png">

**Comment by maddy-tod** [comment]
@Matt-Stypulkoski This looks like a good start! Are you able to fix the text overlap too? As this will mean that the boxes need to be slightly bigger to allow for it. Maybe this could be done by adjusting your factor `1.5`

**Comment by Matt-Stypulkoski** [comment]
@maddy-tod I have been digging a little more into this issue, but cannot seem to improve on what I had in my previous post.  It seems to work well for smaller and slightly larger gate names, but for much larger ones the margin tends to be more than what might be needed. The string of W's example also has overlap, but could not replicate that with many other short string of capital letters.

Do you have any suggestions? Or do you think these flaws are not that impactful?
