### ISSUE TITLE
Auto scale pulse drawings for given channels

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3116]
### What is the expected enhancement?
There's a lot of unused space with default Schedule drawing.

<img width="914" alt="Screen Shot 2019-09-19 at 10 33 44 AM" src="https://user-images.githubusercontent.com/10730254/65253650-fcbbef00-dac8-11e9-8020-480b7dae24ae.png">

Changing the `scaling` option helps, but this still isn't great. We should try to automatically adjust the plotting range, or the scale, or at least not show negative values by default (it looks like the space for neg values leaves a large gap between channels, and I haven't seen it used)

<img width="914" alt="Screen Shot 2019-09-19 at 10 28 24 AM" src="https://user-images.githubusercontent.com/10730254/65253795-41e02100-dac9-11e9-9f74-7e915d9c29ab.png">

**Comment by AzizNgoueya** [comment]
Hi @lcapelluto, i'm working on this.

**Comment by AzizNgoueya** [comment]
I think the problem come from the method `_count_valid_waveforms()`  of `qiskit.visualization.pulse_visualization` module, and when the scaling=1(by default in the draw method) the maximum amplitude `v_max=0.5*scaling` is low.
![image](https://user-images.githubusercontent.com/49644465/65698381-b47a6f00-e07c-11e9-9edb-389f5490aa8c.png)

However we can specify `scaling=None`  like this to have a better visualization:
![image](https://user-images.githubusercontent.com/49644465/65698982-ac6eff00-e07d-11e9-9f91-c9309f518280.png) 

So my recommendation is to change the  default value to 1 à `None` but also adjust the scaling for this last.

**Comment by lcapelluto** [comment]
Thank you! That is definitely already an improvement. Would it be possible to also check if the pulse envelope has negative values, and if not, set the range for the drawn channel to go from 0 up? For many cases, including our examples, this would remove a lot of unused space. (Note that we can't assume the envelope won't have negative values)

**Comment by AzizNgoueya** [comment]
I tried two values of `v_max` for `scaling=None`:

### 1- `v_max = 0.5 / (v_max)`

![image](https://user-images.githubusercontent.com/49644465/65701676-02de3c80-e082-11e9-914a-34ae63062671.png)

And for a DriveChannel with negative values

![image](https://user-images.githubusercontent.com/49644465/65701899-69635a80-e082-11e9-8601-60c4e4e57f1a.png)


### 2-`v_max=1/v_max`
![image](https://user-images.githubusercontent.com/49644465/65702820-f1962f80-e083-11e9-943a-317dbe0dcf9e.png)

With negative value:

![image](https://user-images.githubusercontent.com/49644465/65703323-dd066700-e084-11e9-9aab-9bd7ac3d489e.png)

As you said, if i don't have negative values, could i use the case 2, otherwise the case 1?

**Comment by lcapelluto** [comment]
I think the `scaling=None` solution you found handles the scaling issue well. I was hoping we could make the best use of the space by also changing the y-axis range that is displayed for each channel. If there are no negative values, I was hoping we could get an output something like this:

<img width="955" alt="Screen Shot 2019-09-26 at 12 12 05 PM" src="https://user-images.githubusercontent.com/10730254/65705816-26d85880-e057-11e9-820b-c17112d15911.png">

Do you think that would be possible?
