### ISSUE TITLE
Quantum circuits created using a shared register end up on different registers when combined after transpiling

### ISSUE THREAD

**Issue by bjader** [Qiskit/qiskit-terra#3136]
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**: 3.7.4
- **Operating system**: Ubuntu 18.04.3

### What is the current behavior?

When you combine two quantum circuits, that were created using the same shared register, they will appear on different registers.

### Steps to reproduce the problem

```python
from qiskit import QuantumRegister, QuantumCircuit, ClassicalRegister
from qiskit.compiler import transpile

qr = QuantumRegister(3)
cr = ClassicalRegister(1)
qc1 = QuantumCircuit(qr)

qc1.x(qr[1])
qc1.h(range(3))
qc1.cx(qr[1], qr[2])
qc1.cx(qr[0], qr[1])

qc2 = QuantumCircuit(qr)
qc2.x(qr[1])
qc2.h(range(3))
qc2.cx(qr[1], qr[2])
qc2.cx(qr[0], qr[1])

qc2 = transpile(qc2, coupling_map=[[0, 1], [0, 2], [1, 2]])
qc1 += qc2
qc1.draw(output='mpl').show()
```
Produces this:

![image](https://user-images.githubusercontent.com/14994219/65514170-b6093300-ded4-11e9-8b69-0ea83964035f.png)

### What is the expected behavior?

The two circuits should end up on the same register. This is the behaviour when running the above code on Qiskit 0.11.0.

### Suggested solutions

The expected behaviour is restored when removing the coupling map in the above example. This could provide a starting point for debugging.

**Comment by kdk** [comment]
Hi @bjader , thanks for reporting. Following Qiskit 0.12.0, this is the expected behavior. Terra 0.9 included several bugfixes to standardize the way in which circuits are laid out by the transpiler,  including laying out circuits over a standardized device register.

You should be able to achieve the old behavior by either transpiling with a custom pass manager that excludes layout passes, or by looking at the `circuit._layout` property on the output circuit which will hold the layout used during transpile. N.B. The location/format of `circuit._layout` hasn't been finalized, and may move in future releases.

**Comment by bjader** [comment]
Hi @kdk thank you for the response! It's good to know that this is the expected behaviour now - although I think in this particular case the old behaviour would be more commonly what a user would like to happen. 

I'll have a try with the `circuit._layout `property. Could you give more details on what you mean by "look" at it. Would I modify the property to use the original register?

**Comment by 1ucian0** [comment]
Try `qc1.draw(output='mpl', with_layout=True).show()`.
