### ISSUE TITLE
Increase number of trials for default swap mapper

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3169]
### What is the expected enhancement?

The default swap mapper has been hard-coded to 20 trials for a couple of years now.  Given that the routine is several order of magnitude faster now, this number should be increased.  This should reduce the variability of swap mapper, and lead to shorter depth circuits.

It would also be nice to make this argument accessible to the users.

**Comment by gines-carrascal** [comment]
Working on it...
Should it be a new parameter at transpile initialization?
```def transpile(circuits,
              backend=None,
              basis_gates=None, coupling_map=None, backend_properties=None,
              initial_layout=None, seed_transpiler=None,
              optimization_level=None,
              pass_manager=None, callback=None, output_name=None,
              swapTrials=20):
```
Or should it be better to set different values in the different preset_passmanager levels?

level0 -> 20
level1 -> 40
level2 -> 80
level3 -> 160

**Comment by 1ucian0** [comment]
I think the different values for different preset pass managers is the way to go.

**Comment by 1ucian0** [comment]
The consensus here seems to be towards the second approach mentioned in https://github.com/Qiskit/qiskit-terra/issues/3169#issuecomment-536504980, ie. preset trials depending on the optimization level (in general, having pass-specific parameters in `transpile` is something to avoid).

In order to decided the preset constant for each level, a benchmark analysis needs to be done, considering the running time and the depth of the result.

**Comment by 1ucian0** [comment]
Based on https://github.com/Qiskit/qiskit-terra/pull/3178#issuecomment-606686326, I'm closing this one. Please reopen if its still valid.
