### ISSUE TITLE
intermittent bug in stochastic swap pass

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3197]
```python
qasm = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c[5];
cx q[4],q[1];
u3(0.771421551875327*pi,1.93195729272833*pi,1.95526496079462*pi) q[2];
cx q[1],q[4];
cx q[3],q[2];
cx q[4],q[1];
u1(0.0680407993035097*pi) q[2];
u3(0.474906730130952*pi,0.679527728632899*pi,1.16361128456302*pi) q[1];
cx q[2],q[3];
cx q[1],q[0];
u3(0.479236620087447*pi,0,0) q[3];
u3(1.65884252662582*pi,0,0) q[1];
cx q[3],q[2];
cx q[0],q[1];
cx q[2],q[0];
cx q[1],q[0];
cx q[3],q[2];
cx q[0],q[1];
cx q[2],q[3];
cx q[1],q[0];
cx q[3],q[2];
cx q[0],q[4];
cx q[1],q[2];
measure q[4] -> c[4];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
"""

from qiskit import QuantumCircuit, execute, transpile, assemble, Aer
from qiskit.transpiler import CouplingMap
from qiskit.visualization import plot_histogram
from qiskit.transpiler import passes
from qiskit.transpiler import PassManager

circ = QuantumCircuit().from_qasm_str(qasm)
backend = Aer.get_backend('qasm_simulator')
coupling_map = [[0, 1], [1, 0], [1, 2], [1, 3], [2, 1], [3, 1], [3, 4], [4, 3]]

stochastic = passes.StochasticSwap(CouplingMap(coupling_map), seed=0)
lookahead = passes.LookaheadSwap(CouplingMap(coupling_map))
basic = passes.BasicSwap(CouplingMap(coupling_map))

pm = PassManager(stochastic)
new_circ = pm.run(circ)

counts_cm = backend.run(assemble(new_circ,shots=10000)).result().get_counts()
counts_no_cm = backend.run(assemble(circ,shots=10000)).result().get_counts()

plot_histogram([counts_cm,counts_no_cm],legend=['coupling_map','no_coupling_map'])
```

![image](https://user-images.githubusercontent.com/8622381/66239363-abfee580-e6c7-11e9-804e-11f3f37b7447.png)

The circuit mapped to coupling map returns different counts vs. original circuit.

This only occurs for some random seeds.

**Comment by nonhermitian** [comment]
Oddly, running it through `transpile` with `seed_transpiler=0` gives the correct result.

**Comment by brandhsn** [comment]
In the instance above, stochastic swap removes the measurement on qubit q3. This is also visible in the shown histogram: after running stochastic swap with the coupling map, every count is 0 where q3 is supposed to be 1. After adding a measurement on qubit q3, the counts are nearly identical.

Running the circuit through transpile does not show this error because the pass BarrierBeforeFinalMeasurements() is always added before any swap pass which seems to stop stochastic swap from removing measurement gates.

I see three possible fixes:
1. The method _mapper in https://github.com/Qiskit/qiskit-terra/blob/00ba08f742fec038d962d96d446186d9aadda83a/qiskit/transpiler/passes/mapping/stochastic_swap.py#L303 could be extended to make sure any removed measurement is added again to the circuit as given by last_edgemap.
2. Debugging and fixing when and why stochastic swap removes measurements.
3. Change nothing and expect developers to always use BarrierBeforeFinalMeasurements() before using any swap pass.

I tend to option 1 or 3 since the method seems to rely on removing measurements as per comment in line 303 and changing this could cause bugs down the road.

What should be done?

**Comment by ajavadia** [comment]
We should not always rely on the `BarrierBeforeFinalMeasurement` pass. That is just there to ensure measurements don't creep into the middle of the circuit, because then the circuit cannot run on current hardware. Future hardware can support middle measurements. So the transpiler should produce an equivalent circuit with or without the `BarrierBeforeFinalMeasuremet` pass.

Also, this seems to not be the whole story. The example below fails even with `execute()` -- i.e. when the default level 1 pass manager is invoked, which has inside it the implicit barrier insertion.

```python
qasm="""OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c[5];
cx q[4],q[1];
u3(0.771421551875327*pi,1.93195729272833*pi,1.95526496079462*pi) q[2];
cx q[1],q[4];
cx q[3],q[2];
cx q[4],q[1];
u1(0.0680407993035097*pi) q[2];
u3(1.7210274485623*pi,0,0) q[3];
u3(0.474906730130952*pi,0.679527728632899*pi,1.16361128456302*pi) q[1];
cx q[2],q[3];
cx q[1],q[0];
u3(0.479236620087447*pi,0,0) q[3];
u3(1.65884252662582*pi,0,0) q[1];
cx q[3],q[2];
cx q[0],q[1];
cx q[1],q[0];
cx q[2],q[0];
cx q[0],q[2];
cx q[2],q[0];
cx q[1],q[0];
cx q[3],q[2];
cx q[0],q[1];
cx q[2],q[3];
cx q[1],q[0];
cx q[3],q[2];
cx q[0],q[4];
cx q[1],q[2];
u3(0.777850970026001*pi,0.585592073798391*pi,1.12646645031497*pi) q[3];
measure q[4] -> c[4];
measure q[0] -> c[0];
measure q[1] -> c[1];
measure q[2] -> c[2];
measure q[3] -> c[3];
"""
from qiskit import QuantumCircuit, execute, IBMQ, Aer
from qiskit.transpiler import CouplingMap
from qiskit.visualization import plot_histogram

backend = Aer.get_backend('qasm_simulator')

circ = QuantumCircuit().from_qasm_str(qasm)

coupling_map = [[0, 1], [1, 0], [1, 2], [1, 3], [2, 1], [3, 1], [3, 4], [4, 3]]

seed_transpiler = 0

couple_job = execute(circ, backend, shots=1000, basis_gates=['u1', 'u2', 'u3', 'cx'], coupling_map=coupling_map, seed_transpiler=seed_transpiler)
no_couple_job = execute(circ, backend, shots=1000, basis_gates=['u1', 'u2', 'u3', 'cx'], seed_transpiler=seed_transpiler)

couple_counts = couple_job.result().get_counts()
no_couple_counts = no_couple_job.result().get_counts()

plot_histogram([couple_counts,no_couple_counts],legend=['coupling_map','no_coupling_map'])
```

![image](https://user-images.githubusercontent.com/8622381/66953865-426ac980-f02d-11e9-9808-1e962e54b2a1.png)

**Comment by nonhermitian** [comment]
The original fix was to have the swap mapper remove the measurements and then add them back at the end (https://github.com/Qiskit/qiskit-terra/pull/691), i.e. option 1 above.

**Comment by brandhsn** [comment]
Fixing the measurements does not seem to be sufficient: in the second instance provided by @ajavadia , an U3 gate on q3 is missing in the transpiled circuit after stochastic swap. The cx gates seem to be okay in both instances, i.e. if the measurement/u3 gate is reintroduced to the erroneously transpiled circuit, the counts are almost identical.

I can have a closer look when I have more time. :-)

**Comment by brandhsn** [comment]
it seems that the bug is triggered whenever stochastic swap encounters a layer with multi- and single-qubit gates that cannot be placed with one swap. In this case, the pass iterates over each gate in the layer individually and tries to place it. However, single-qubit gates are skipped and thereby omitted in the final circuit.

Minimal example for the given coupling map:
qasm="""OPENQASM 2.0;
include "qelib1.inc";
qreg q[5];
creg c[5];
cx q[0],q[4];
cx q[1],q[2];
u3(0.777850970026001*pi,0.585592073798391*pi,1.12646645031497*pi) q[3];
"""
![image](https://user-images.githubusercontent.com/23399754/67108896-b644d780-f1cf-11e9-9267-74b2c14f25eb.png)

->

![image](https://user-images.githubusercontent.com/23399754/67108915-bc3ab880-f1cf-11e9-93e2-8a3a117fc6d4.png)
