### ISSUE TITLE
MPL rendering fails for circuits with operations conditioned on a classical register

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-terra#3237]
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**: 3.7.4
- **Operating system**: macOS Mojave v10.14.6

### What is the current behavior?

When trying to render a circuit with `output='mpl'`, if it contains any operations conditioned on the state of a classical register, it fails:
```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
q = QuantumRegister(1)
c = ClassicalRegister(1)
qc = QuantumCircuit(q, c)
qc.x(q[0]).c_if(c, 0)
qc.measure(q,c)
qc.draw(output='mpl')
```
The following error is thrown:
```
AttributeError: 'Clbit' object has no attribute 'reg'
```
It does work, however, with `output='text'`, `output='latex'` and `output='latex_source'`.

Same thing happens when using `circuit_drawer(qc, output='mpl')` instead.

### Steps to reproduce the problem

1. Prepare a virtual environment.
2. Install `qiskit`, `qiskit-terra[visualization]` and `jupyter`.
3. Create a new jupyter notebook and run the above mentioned code.

### What is the expected behavior?

 Circuit figure should be rendered in 'mpl' format.

**Comment by mtreinish** [comment]
Thanks for opening an issue. This issue was actually already caught and fixed on the day we pushed the 0.9.0 release (it barely missed the deadline). The fix was here: https://github.com/Qiskit/qiskit-terra/pull/3032 it's been backported to stable/0.9 (see: https://github.com/Qiskit/qiskit-terra/pull/3049 ) for inclusion in a bugfix release per the stable branch policy: https://github.com/Qiskit/qiskit-terra/blob/master/CONTRIBUTING.md#stable-branch-policy Or it will be included in the next minor version release 0.10.0 which will likely also happen relatively soon. I'll ask and see if people are opposed to pushing a bugfix release to get this fix out prior to the 0.10 release.

In the meantime I'm going to close this issue as it's already been fixed. Please feel free to reopen it if I'm missing something or there is more to discuss.

**Comment by pedrorrivero** [comment]
Thanks for the quick response @mtreinish ! I did not see the fix in the list of closed issues, apologies.

**Comment by mtreinish** [comment]
Actually looking at the PR it looks an issue about it was never opened. It was quick typo fix and we didn't bother to open an issue about it because it was a 1 line fix. I think we assumed we would have pushed a `0.9.1` that included it well before now.
