### ISSUE TITLE
Document`Bit.index` and `Bit.register`

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#3238]
### What is the expected enhancement?

PR #2414 introduced `Qubit(Bit)` and `Clbit(Bit)` classes as a standardized replacement for `(Register, int)` tuples, including properties `register` and `index` to access the corresponding values. These properties are not included in the class docstrings, and so are not surfaced to users through either `help(qubit)` or through the generated sphinx documentation, and should be added.

**Comment by willhbang** [comment]
Hello! I'm just getting started with Qiskit and looking to make my first contribution. Do you mind if I give this one a shot?
Looks like we just have to add to the docstring for the Bit constructor?
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/circuit/bit.py#L25

**Comment by kdk** [comment]
Hi @willhbang , feel free! The `Bit` class isn't expected to be visible to users, that's why its omitted from the generated sphinx docs. The properties could be added to the class doc string on Bit (and then inherited by Clbit and Qubit) or added to the child classes directly. 

Instructions for building the docs to test can be found here: https://qiskit.org/documentation/contributing_to_qiskit.html#documenting-your-code . Let me know if you have any questions.

**Comment by willhbang** [comment]
I'm having trouble generating the docs locally with `tox -edocs` (I'm running Python 3.7 on Windows)... might be an issue with my installation of tox, because the whole test suite isn't working for me either.
Testing with `help()` seems to have the expected changes, so for now I'll try opening the PR so I can check the Sphinx docs from the CI job.
