### ISSUE TITLE
DAG Drawer not working

### ISSUE THREAD

**Issue by dennis-liu-1** [Qiskit/qiskit-terra#3306]
### Information

- **Qiskit Terra version**: 0.10.0
- **Python version**: 3.7.3
- **Operating system**: Mac

### What is the current behavior?

Calling dag_drawer() in the tutorial 4_transpiler_passes_and_passmanager.ipynb on IQX yields the following error: 

<img width="812" alt="Screen Shot 2019-10-23 at 2 31 12 PM" src="https://user-images.githubusercontent.com/54714046/67423399-3a1d0c00-f5a2-11e9-81ec-28432c165b02.png">
 

### Steps to reproduce the problem 

Ran other code that calls dag_drawer() as well, and this results in the same error.

### What is the expected behavior?

Draw the dag without errors

**Comment by mtreinish** [comment]
It's caused because of an incompatibility with networkx 2.4 and nxpd which is used to generate the visualizations. There are 2 fixes in progress for it, one in the upstream nxpd lib: https://github.com/chebee7i/nxpd/pull/15 and the other in terra itself (which is to stop using nxpd): https://github.com/Qiskit/qiskit-terra/pull/3280

In the meantime the only way to avoid this is to downgrade networkx to 2.3.0 (which is what we do for ci and test envs).
