### ISSUE TITLE
pulse library issues, part #2

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#3327]
Follow up to #3313 

1- `square`, `sawtooth`, `triangle` are defined in terms of period, but `sin`, `cos` are defined in terms of frequency.

2- another initial discontinuity:
```
discrete.sech(duration=240, amp=0.1, sigma=80)
```
![image](https://user-images.githubusercontent.com/8622381/67629649-2c3fe300-f84f-11e9-9138-f27c2351f733.png)

**Comment by taalexander** [comment]
1. I think these should all be frequency.
2. We need to define the standard behavior for such discrete symmetric/antisymmetric non-periodic pulses whose domain goes from [-infinity, infinity]. I don't think the discontinuity is always wrong and sometimes may in fact be the desired behaviour. I propose that we define a `zeroed` flag that force the first/last sample to zero. I am not sure if we should enable/disable by default.

**Comment by eembees** [comment]
I can have a look at this over the weekend, if it's still open?
1. This looks relatively straightforward, unless there are some special issues I should take into account? 
2. This looks a bit more complex - @taalexander or @ajavadia, if either of you could give any guidance on this, that'd be much appreciated!

**Comment by taalexander** [comment]
This is still open if you want to take it on. These could be done in two separate PR to separate the complexity.
1. This is straightforward
2. I think has been solved for `sech` but not for the gaussian derivative component of drag. `zeroed_width` is the parameter name for the continuous pulse `zeroed_ends` for the discrete pulse. The Gaussian derivative component of the pulse should be zeroed about its center by subtracting (adding) the zeroed width value.

**Comment by eembees** [comment]
Yes, I'll try my best - updating you when I have something more!

**Comment by eembees** [comment]
Quick question @taalexander - Should we allow `square` , `sawtooth` and `triangle` to still take `period` as an argument, with a `DeprecationWarning`, or only allow `freq` as argument?

**Comment by taalexander** [comment]
I'm not certain as these pulses are not often used and to allow this we would have to change the order of arguments as we would have to allow `None` for both `freq` and `period`. I've asked for input on my review from @lcapelluto as she is better versed in graceful deprecations.

**Comment by eembees** [comment]
For part 2:
The simplest way would be to make a new function, `_fix_gaussian_deriv_width()` that subtracts the value of `gaussian_deriv` at `zeroed_width/2`, from the absolute value of the `gaussian_deriv`.

This will introduce a discontinuity in the pulse at the center of the pulse, where the derivative of the gaussian crosses 0. I assume that is inconvenient.

An alternative route would be to take the derivative of the corrected gaussian, instead of calling `gaussian_deriv` with the same parameters (as `gaussian_deriv` creates a new instance of a gaussian pulse. This would probably work better, seeing as it corresponds to the gaussian pulse component of `drag`, but we will still have a discontinuity at the edges. 

Do you have any suggestions for how to address this @taalexander?

**Comment by taalexander** [comment]
I believe first of all we should introduce a new set of pulse functions, `ZeroedGaussian`, `ZeroedGaussianSquare`, `ZeroedDRAG` and there associated parametric pulses so that it is absolutely clear that the pulse shapes are being zeroed. I have created issue #3742 for this.

I believe the solution for the gaussian derivative and generally any antisymettric component is to subtract `g(-1)` for (t < width/2) and `g(width+1)` for (t>= width/2).

I believe this can be generalized to any linear combination of symmetric and anti-symmetric pulse functions that share a duration and can be derived from the assumption that we want our zeroed pulse to satisfy `f(-1) = 0`, `f(width+1) = 0` and `f(t)-g(t)= c` such that the separation of all pulse samples remains constant pre and post lowering. Here g(t) is the un-zeroed pulse, eg., the gaussian derivative or gaussian pulse.

**Comment by eembees** [comment]
> I believe the solution for the gaussian derivative and generally any antisymettric component is to subtract `g(-1)` for (t < width/2) and `g(width+1)` for (t>= width/2).

I think it's a good approach for generalization, but it doesn't solve the discontinuity issue when `g(t)=0` which in this case is at `t = width`.

Either way, I guess we can move this discussion to #3742, and close this issue? I don't see any reason to double the work on this if we'll remove it in a future PR.

**Comment by taalexander** [comment]
Ok, let's move the discussion over there 😄.
