### ISSUE TITLE
[RFC] client-side job validation

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3345]
# Terra:  client-side job validation 
| Status        | Proposed                                             |
:-------------- |:---------------------------------------------------- |
| **Author(s)** |         |
| **Updated**   |                                            |
## Objective
There are [many situation](https://github.com/Qiskit/qiskit-terra/projects/13) where a user transpile and assemble a qobj that is rejected by the backend with `Invalid job state`.

The accepted solution should be:
- [ ] easy to understand where is the invalid element.
- [ ] should be optional, so invalid jobs can be created on purpose or avoiding double validation (server-side) for big jobs.  
- [ ] client side.
- [ ] support for PULSE experiments.

**Comment by nonhermitian** [comment]
I will just point out that validation is already done API side, and the error codes corresponding to what went wrong are starting to be returned in the jobs.  This API validation cannot be turned off as people can submit jobs directly to the API.

**Comment by 1ucian0** [comment]
Correct. Server-side validation stays.  More info about what went wrong would be nice. But is independent to this RFC.

**Comment by nonhermitian** [comment]
Just pointing it out because validating things twice may become expensive as job sizes grow.

**Comment by taalexander** [comment]
It should be optional on the client-side. The machinery to perform this should exist within Qiskit since to be done properly will require the tools available in the QuantumCircuit and pulse Schedule classes. Validating directly on the Qobj for complicated constraints would be very difficult and require the reinvention of many parts of qiskit.

**Comment by jakelishman** [comment]
I'm going to close this discussion as stale now.  If there's more to discuss, it would definitely be part of _much_ larger discussions about Terra's role, given that we decoupled Terra from IBM backends since this discussion was opened.  There's likely more that can be said about the evolving `BackendV2` (and beyond) and what constraints machines can pass to Terra, but those would be better placed in other issues now.

Feel free to re-open / start new discussions if there's something I've missed.
