### ISSUE TITLE
Process matrix visualization

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-terra#3374]
### What is the expected enhancement?
We need visualization tool for quantum process.

**Comment by 1ucian0** [comment]
If you have some code as example to generate what needs to be graph (and maybe some idea of what's the expected graph, but we can leave that open), we can tag this as `good first issue`.

**Comment by fs1132429** [comment]
### Update for QoQP
✅ PR #3375 Seems to be stalled which has also stalled this issue.

**Comment by jakelishman** [comment]
I'm going to close this now due to an ongoing lack of interest after it stalled.  If there's further interest in having this sort of visualisation, please feel free to open a new issue.

(imo I'm not certain that we'll necessarily be able to maintain further visualisations, so would suggest that people look to other packages for enhanced visualisation, but am willing to have further discussion on that.)
