### ISSUE TITLE
Makefile assumes conda

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#340]
When running `make` I get an error for not having `conda` installed.

## Expected Behavior
Either require Anaconda explicitly for building (I would not prefer this) or support a normal python installation.

## Current Behavior
I use `pipenv` for managing my virtual environments and installed & sourced the dependencies. Then I run `make` and get this message:
```
make
make: conda: Command not found
if test ; then \
		bash -c "source activate QISKitenv;pip install -r requirements.txt"; \
	else \
		conda create -y -n QISKitenv python=3; \
		bash -c "source activate QISKitenv;pip install -r requirements.txt"; \
	fi;
/bin/sh: conda: command not found
```

In effect, this probably does not matter since I have already installed the dependencies in an other way.

## Possible Solution
Check with `pip` if the requirements are already included in the environment, and install them only if they are missing.
Add a fallback for normal python.

## Steps to Reproduce (for bugs)
1. Clone qiskit
2. Run `pipenv install --three --dev` (a normal python install with venv should also work)
3. Run `pipenv shell`
4. Run `make`

## Context
I am trying to make qiskit so I can contribute changes.

## Your Environment
* Version used: master branch
* Environment name and version (e.g. Python 3.6.1): python 3.6.4
* Operating System and version: macOS 10.13

**Comment by diego-plan9** [comment]
Thanks, @eddieschoute ! As hinted in slack a few days ago, I believe the issue can be attributed to a combination of three separate ones:

* the `Makefile` on the root folder is not meant to be invoked without a target - the `make env` target (which is the one picked up if invoked without parameters) has fallen a bit out of sync with recent developments, and its original purpose was to be a helper for new users to set up their environment. It is indeed not very robust as it is, and still referenced in the docs, which can be a source of confusion.
* there have been / are some changes in regards to the philosophy and the tooling used that might have not been explicitly documented properly. In particular, we have been working towards a clearer separation of "instructions for users" vs "instructions for devs" in the documentation as a whole, and also looking into using cmake instead of make directly as part of some updates to the tooling.
* somewhat related to #343 and to the previous point, it feels reasonable to assume that potential contributors will "know their way" around the development environment and have personal preferences about it. Ideally, we should be able to accommodate all those and leave as much choice for the tooling and workflow to the contributor, but there are still remains in that sense (`make env` can be seen as one of those).

We'll give it a look at the full situation after the upcoming release, and see if we can ensure that these points are reflected and avoid confusion - thanks for raising awareness and for the rationale!

**Comment by eddieschoute** [comment]
I agree that documentation for users and contributors have different goals. Mainly I feel like there are no clear build instructions for qiskit. Even a quick code snippet with a sequence of commands could help. For me on Mac it is (thanks @atilag ):
```
cmake -DSTATIC_LINKING=False out
cd out
make pypi_package
```
then a user may import the built package from `dist` by untarring it and running `pip -e .`.

It is definitely harder to engineer for allowing a larger set of development tools, but at the least common denominator still includes the basic build process and dependency management. From there people can use their own tools (such as `pipenv` or `conda`).

**Comment by delapuente** [comment]
This seems to have been addressed. @eddieschoute, re-open if you feel something is missing yet.
