### ISSUE TITLE
DAGCircuitError running Aqua VQC

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-terra#3440]
### Information

- Master
- 3.6
- Linux, Mac, Windows...

### What is the current behavior?
When running Aqua unit test test_vqc we get a DAGCircuitError in latest master code (not in stable). See Aqua PR https://github.com/Qiskit/qiskit-aqua/pull/719 where 'decompose' was in feature_maps/pauli_expansion.py
```
                inst = evolution_instruction([[1, p]], coeff, 1)
                qc.append(inst, qr)
                qc = qc.decompose()   <---- With this we get DAGCircuitError
        return qc
```
decompose was used to allow caching of resultant ccts. Cache in Aqua does not support instruction so it was decomposed. Since we have now deprecated cache I have removed the above line since we do not need it and it causes the failure. However it maybe that this is something that needs looking into in Terra hence this PR.

### Steps to reproduce the problem
Install latest Aqua, Terra from master. Modify feature_maps/pauli_expansion.py to add the decompose line back above (i.e. revert what was done in the PR for that file). Run unit test test_vqc

### What is the expected behavior?
Unit test passes with no DAGCircuitError

### Suggested solutions
-

**Comment by kdk** [comment]
Hi @woodsp-ibm , the error from https://github.com/Qiskit/qiskit-aqua/pull/719
```
qiskit.dagcircuit.exceptions.DAGCircuitError: 'Cannot replace node of width (2 qubits, 0 clbits) with instruction of mismatched with (1 qubits, 0 clbits).'
```
indicates that one of the gates in the circuit has a definition which does not use all of the qubits over which the gate is defined. (e.g. A 3-qubit composite gate which only has instructions on `q0` and `q1`.) It looks like that is the case for https://github.com/Qiskit/qiskit-aqua/blob/86f3f70/qiskit/aqua/operators/common.py#L229 .

This issue came up previously for `isometry` gates ( https://github.com/Qiskit/qiskit-terra/pull/3233#issuecomment-546662030 ). The thinking then was that instruction definitions should always match the shape of the instruction. Is there a use case for `evolution_instruction` or any instruction having a definition of a different width than the instruction?

It does seem that `QuantumCircuit` could detect and raise earlier if there are idle qubits when `.to_instruction()` is called.

**Comment by woodsp-ibm** [comment]
Having investigated further here is what is happening: The failures came as result of building an instruction from a Pauli string. Lets say we have an Hamiltonian where we have Pauli strings over 2 qubits. So we building out a circuit, including appending an instruction created from the Pauli string. Since its on 2 qubits it spans two qubits but when it comes to building the gates, say its 'ZI' then we get a gate on one qubit, but since the other was Identity no gate was applied to that qubit to form the instruction corresponding to the Pauli String. It is this that is failing to decompose when the circuit containing such an instruction is decomposed. This is the use case under which it was failing as per the above.
