### ISSUE TITLE
cRz gate problem in Composer/Qasm?

### ISSUE THREAD

**Issue by gfpaulik** [Qiskit/qiskit-terra#3527]
### Information

- **Qiskit Terra version**: OPENQASM 2.0
- **Python version**:
- **Operating system**:

### What is the current behavior?
   The problem is seen in the two screenshots below: The cRz with theta=pi does not behave correctly as a ctrlZ in the phase kickbacks. I have experimented a little bit and noted that cRz(2pi) appears to work as a ctrlZ in the kickback scenario, and that cRz(pi) does appear to work as ctrlZ in a simple H->Z->H type circuit. Thank you.

cRz:
![image](https://user-images.githubusercontent.com/58337389/69878961-ddd99600-128b-11ea-99b0-08c4764729d0.png)
cz:
![image](https://user-images.githubusercontent.com/58337389/69879044-12e5e880-128c-11ea-8134-023be6d3e11f.png)

### Steps to reproduce the problem
Here's the code for the two circuits.
crz(pi) circuit:

OPENQASM 2.0;
include "qelib1.inc";

qreg q[5];
creg c[5];

h q[0];
x q[1];
crz(pi) q[0],q[1];
h q[0];
measure q[0] -> c[0];

cz circuit:

OPENQASM 2.0;
include "qelib1.inc";

qreg q[5];
creg c[5];

h q[0];
x q[1];
cz q[0],q[1];
h q[0];
measure q[0] -> c[0];

### What is the expected behavior?
The crz(pi) circuit result should agree with cz circuit result.

**Comment by itoko** [comment]
Hi, @gfpaulik. This is not a problem, in fact, the results you got are the expected results. The definition of crz(lambda) is diag(1, 1, exp(-i*lambda/2), exp(-i*lambda/2)). So crz(pi) != cz. (diag(1, 1, -i, i) != diag(1, 1, 1, -1)).
Although rz(pi) is equals to Z *up to global phase*, it does not mean crz(pi) is also equals to cz (because of the difference of the global phase in the subsystem).

**Comment by gfpaulik** [comment]
Dear @itoko,
   Thank you for responding, however, consider the following. If what you say is correct, then a crz(pi) with the control activated should behave as an S-gate but it appears instead to agree with a Z-gate:
 
![image](https://user-images.githubusercontent.com/58337389/70241988-9e042a00-1735-11ea-9f6b-9541ef459f7b.png)

**Comment by gfpaulik** [comment]
Dear @itoko ,
   Thank you for your response, but I am surprised to see your definition of the crz(lambda) gate. My understanding is that the control version of a Z rotation is diag(1,1,1,e^i*lambda). This differs not only in the the interpretation of the phase argument but in the (3,3) diagonal value as well; the control version of a gate should not alter the functioning of the original gate. An rz(lambda) gate is diag(1,e^i*lambda), an rz(pi) gate is the Pauli-Z gate, and the controlled version should behave the same when the control is a "1":
![image](https://user-images.githubusercontent.com/58337389/70245757-3e5d4d00-173c-11ea-905d-7d4287136430.png)
![image](https://user-images.githubusercontent.com/58337389/70245793-4c12d280-173c-11ea-86ec-b0c5c9701b7a.png)
   Do you agree? What is interesting is that the crz() gate does not behave properly in the phase kickback circuit. Thanks.

**Comment by itoko** [comment]
In (the latest) Qiskit, the gate diag(1,1,1,e^i\*lambda) is named cu1(lambda). The cu1(pi) = cz as you expect.

You can find the Qiskit's definition of gate matrices at
https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorials/blob/master/qiskit/fundamentals/7_summary_of_quantum_operations.ipynb

It says the definition of rz(lambda) gate is diag(exp(-I\*lambda/2), exp(-I\*lambda/2)).
That's the reason why rz(pi) = z *up to global phase* but crz(pi) != cz.

Note: Excuse me, I used big endian indices for matrix whereas Qiskit uses little endian. That's why the gate matrices in my previous comment apparently look different from those in the qiskit tutorial.

**Comment by gfpaulik** [comment]
Dear @itoko ,
   Ah, now I understand, thank you! At first, I was confused by your explanations because for some reason your gate definitions repeat the -i, as in diag(exp(-I*lambda/2),exp(-I*lambda/2)), when you obviously meant diag(exp(-I*lambda/2),exp(I*lambda/2)) or diag(exp(-I*lambda/2),exp(+I*lambda/2)). This definition explains the different results I was seeing: The gate has the same eigenvectors but different eigenvalues. Thank you for your help!
