### ISSUE TITLE
An error message for large circuits

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-terra#3529]
### What is the expected enhancement?

Circuit size is limited. I don't know if different devices have different limits, and whether the limit is exposed somewhere. When a user runs a circuit which is too large, the validation passes, and later there is a general job error,  that does not specify that circuit size is the cause for the error.

**Comment by 1ucian0** [comment]
transpiler pass
backend improvement error (coming soon)
client-side validation

**Comment by 1ucian0** [comment]
This issue seems still valid:
```
from qiskit import QuantumCircuit, IBMQ
circuit = QuantumCircuit(2)
circuit.h(range(2))

provider = IBMQ.load_account()

backend = provider.get_backend('ibmq_armonk')

job = backend.run(circuit)
job.result()
```
```
IBMQJobFailureError: 'Unable to retrieve result for job 61bdb2cb794ea36a1ef5881c. Job has failed: The number of qubits in the Qobj (2) is higher than the number of qubits supported by the device (1). Error code: 1109.'
```

**Comment by jakelishman** [comment]
I'm going to close this as "no longer Terra's responsibility" now; an improved error message would be the responsibility of the backend returning the error message.

Luciano's given example is not Terra's fault because the `transpile(circuit, backend)` step (which _does_ raise an error) is absent.  In that situation, the backend returning the error is correct.
