### ISSUE TITLE
`cry` and `crz` cannot use index of qubit

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-terra#3531]
### Information

- **Qiskit Terra version**: 0.10.0
- **Python version**:
- **Operating system**:

### What is the current behavior?

For `crz` and `cry` it is not possible to use the simplified syntax in which qubits are passed by index. For example

```
qc.crz(np.pi,0,1)
qc.cry(np.pi,0,1)
```
Instead, the more old-fashioned notation must be used

```
qr = qc.qregs[0]

qc.crz(np.pi,qr[0],qr[1])
qc.cry(np.pi,qr[0],qr[1])
```

### Steps to reproduce the problem

See [this notebook](https://github.com/quantumjim/Misc_QISKit_Things/blob/master/crx_tests.ipynb)

**Comment by Cryoris** [comment]
For `crz` this should work. Looking at the notebook, the error is raised by the call to `cry` and not `crz`. 

As for `cry`: this gate is currently still part of Aqua (it will be moved to Terra) and there this issue was fixed by a recent PR. If you update Aqua, the `cry` should also work with indices.

**Comment by quantumjim** [comment]
Thanks. I'll close, then.
