### ISSUE TITLE
Supported meas_levels should be validated on client-side at assembly

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3610]
### What is the expected enhancement?
The new `ibmq_armonk` device only supports `meas_levels=[1,2]`. An optional validation error should be raised if a user tries to submit a `meas_level=1` job. This is related to #3606.

**Comment by eembees** [comment]
Hi @taalexander , I would like to have a look at this. 
Should I (just) add a validation error to this, similar to #3606? 
I see that #3606 also includes a test, but I don't know if that's necessary for this?

**Comment by taalexander** [comment]
Thank you @eembees! I think you have the right idea @eembees. A test would be nice to verify this is working you could just use an empty schedule `pulse.Schedule()` and add it to `test.python.compiler.test_assembler`.

**Comment by eembees** [comment]
I implemented a basic fix, but I have some clarifying questions I want to have cleared up pre-PR:
1. I assume it should raise a ValidationError when `meas_levels = 0`, not 1? 
2. I don't exactly know how to make the validation optional.
 I suppose we could add a keyword `validate=T/F` but I don't see exactly where this should be located - should it be in `backendconfiguration`? Or should we put it directly in the `assemble` function?. Any guidance on this would be super useful!
3. If we don't add the validate kw, there are two tests in `test.python.result.test_results`: `test_meas_level_0_avg` and `test_meas_level_0_single`,  that I think could be removed, as it doesn't make sense to keep them around if we don't support anything with `meas_level=0`. Correct me if I'm wrong on this, please.

@taalexander tagging you so you will see it.

**Comment by lcapelluto** [comment]
1. Yes, I think that is what he meant. Rather than hardcoding, you should check if `meas_level` given by the user is not in the list `backend.configuration().meas_levels`
2. I think it would be an argument to `assemble`. However, since Matt is likely to do the same work for #3606, I'd ignore that requirement for now, and copy/rebase off his work to avoid redundant work and conflicts.
3. Meas level 0 is sometimes supported, just not by `ibmq_armonk`, so we can leave those tests 👍 

Thanks again for your patience, and welcome to our Terra community! 🎉
