### ISSUE TITLE
Complete the integration of multi-controlled qubit gates

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#3639]
After migrating to Terra from Aqua, the multi-controlled qubit gates are missing tests. Since tests for these gates still exist in Aqua, they could simply be migrated as well.
Is there a reason why they have not yet been imported to Terra? 

Also, they are not yet gate objects. Once they are, we can also use these to override the `control` of the Toffoli and rotation gates to return these, more efficient controlled gate versions if the number of control qubits is larger than 1 (related to #3631).

This concerns the following gates: 
```
mct mcrx mcry mcrz rccx rcccx
```

Plan:
- [x] Move the tests for these gates to Terra
- [x] Implement the relative-phase Toffoli gates
- [x] Implement the multi-controlled U1 gate
- [x] Implement the multi-controlled X gate
- [ ] Implement the multi-controlled rotations
- [x] Port the multi-controlled multi-target X gate from Aqua
- [x] Port the boolean logic gates from Aqua

**Comment by ewinston** [comment]
The ControlledGate implementation uses these gates for the rotation and Toffoli gates so it should be as effecient. Perhaps if these gates were converted to proper gates, however, it would simplify the code in `add_control` further. Additionally there are tests for multicontrolled gates although perhaps not everything that is tested in aqua so that could be good to add. 

Something else which could be added is their support for ancilla.

**Comment by kdk** [comment]
When the tests are migrated, we should include https://github.com/Qiskit/qiskit-aqua/blob/master/qiskit/aqua/circuits/gates/boolean_logical_gates.py and their tests so they can be removed from aqua.

**Comment by frankharkins** [comment]
@Cryoris will the multi-qubit toffolis have the behaviour:

`qc.mcrz(math.pi, [0,1,2], 3)`

(take integers as well as / instead of `Qubit` objects)? It would be good to have this to be consistent with the other `QuantumCircuit` methods such as `qc.x(0)`.

**Comment by Cryoris** [comment]
Yes, they will 🙂

**Comment by Cryoris** [comment]
Closing in favor of #4451.
