### ISSUE TITLE
Optional module dependencies are requirements-dev?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3654]
It seems that we don't have a clear policy on how to handle requirements for "optional" modules.

For example #3532 introduced a pass that requieres `z3-solver` an that was added as a  *requirements-dev* https://github.com/Qiskit/qiskit-terra/pull/3532/files#diff-f4c265073ea4274a80eca85440875e56, while #3043 also introduced a pass with an extra dependency (`python-constraint` in this case) but did not extend *requirements-dev*.

What should be the policy here?

**Comment by mtreinish** [comment]
One thing I think we need to ensure is that we have these optional requirements installed in CI for testing. An issue that is very easy to envision is that we end up skipping all the tests for optional requirements because they're not present. Then we never test things anywhere. I felt that putting the optional requirements in requirements-dev.txt and having the tests unconditionally run felt like the right approach. That way we're always running all the tests in CI. While some features (like the passes mentioned here) look self contained they do rely on base constructs like the dag, passmanager, etc so it's good to make sure that we don't accidentally break these passes.

**Comment by 1ucian0** [comment]
Good point. Would having a `requirements-optional.txt` (with comments about which module needs each dependency) too overkilling?

**Comment by jakelishman** [comment]
Ha, I was just looking through old issues and found this.  Turns out that great minds think alike.  Will be fixed by #8967.
