### ISSUE TITLE
How to deal with Qubit does not exist error while specifying initial layout

### ISSUE THREAD

**Issue by Tininfin96** [Qiskit/qiskit-terra#3721]
<img width="925" alt="Screenshot 2020-01-16 at 9 44 37 PM" src="https://user-images.githubusercontent.com/56279716/72542432-2683f780-38aa-11ea-88ad-28a2c76a7ee0.png">
This is the layout I am trying to implement for the Ibmq burlington machine.
<img width="317" alt="Screenshot 2020-01-16 at 9 51 21 PM" src="https://user-images.githubusercontent.com/56279716/72542579-62b75800-38aa-11ea-87e8-1829a06960d7.png">

<img width="887" alt="Screenshot 2020-01-16 at 9 44 45 PM" src="https://user-images.githubusercontent.com/56279716/72542378-0eac7380-38aa-11ea-84d5-5b102e30d4ae.png">
What changes should I make to the circuit definition or layout specification to deal with this?

**Comment by yesodharan1892** [comment]
hi, @Tininfin96 please share the complete code so that i can look into it , if you are okay with it.

**Comment by Tininfin96** [comment]
Hey, yeah. The code is as follows:

qub=QuantumRegister(5)
clreg=ClassicalRegister(2)
c=QuantumCircuit(qub,clreg)
c.x(qub[0])#initialize(init_st,qub[0])
c.x(qub[1])
c.cx(qub[0],qub[1])
c.measure(qub[:2],clreg)

backend=provider.get_backend('ibmq_burlington')
layout=Layout({qub[0]:3,qub[1]:4,qub[2]:0,qub[3]:1,qub[4]:2})#,2:c[2],3:c[3],4:c[4]}
job = qiskit.execute(transpile(c,backend), backend, initial_layout=layout, shots=2048)

**Comment by kdk** [comment]
Hi @Tininfin96 , what version of qiskit are you using? I wasn't able to reproduce this particular error on master.

Can you try replacing your last line with the following:
`qiskit.execute(c, backend, initial_layout=layout, shots=2048)`?
`execute` will internally call `transpile` with the provided `initial_layout`, so you don't need to call it separately.

(I'd guess that the layout stage is failing because the circuit returned by `transpile(c, backend)` has already been laid out on to device qubits, and so doesn't match the `initial_layout` provided to execute defined over qubits in `qub`. We should notice this earlier so we can raise a more detailed error message.)

**Comment by Tininfin96** [comment]
@kdk Hey! Thank you so much, you are right. I am now passing the layout in the transpile function itself. That has taken care of the issue.
