### ISSUE TITLE
Rename ControlChannel to InteractionChannel

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-terra#3753]
### What is the expected enhancement?
Currently, in Qiskit-Pulse arbitrary pulse channels are of type `ControlChannel`. Typically these are used for two-qubit _interactions_ so the name `InteractionChannel` is hopefully more descriptive. 

Thoughts @ajavadia @lcapelluto?

**Comment by lcapelluto** [comment]
I had discussed the name at length with @dcmckayibm once (can't say if he is still of the same opinion now, though), and we had thought "derived channel" was a good name for them, since there is that `u_channel_lo` list which gives the control channels their definition in terms of drive channel frequencies. Is this feature of the control channel going to be removed?

I also have to bring up that drive channels also _interact_ with qubits. `DriveChannel` and `InteractionChannel` seem even more like synonyms than `Drive` and `Control`

**Comment by taalexander** [comment]
I really do not like the name derived channel as it is possible someday we will want to disconnect certain properties (say the frequency) of these channels dynamically.

**Comment by lcapelluto** [comment]
so, the `ControlChannel` is really just a second `DriveChannel`. I don't think we will be able to come up with a good name if there's nothing distinguishing about it

**Comment by lcapelluto** [comment]
`MultiQubitDriveChannel` 🤷‍♀ :(

**Comment by dcmckayibm** [comment]
The problem is the channel could represent anything that changes a term in the Hamiltonian, so it could have nothing to do with multiple qubits or interactions (e.g. a fast flux control knob).

**Comment by taalexander** [comment]
Ok, so we shall remain with `ControlChannel` until the right name smacks us in the head 😄.
