### ISSUE TITLE
Documentation for the Pulse module: `Command` linking

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#3859]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Locally, `Command` API cross references are not working.

With the Azure docs artifact, neither Channels nor Commands works, but Channels works for me locally! :(

### Steps to reproduce the problem

Build this locally https://github.com/Qiskit/qiskit-terra/pull/3849

### What is the expected behavior?

Clicking `Command` and `commands` should lead to another API page

### Suggested solutions

Just need to update `:mod:~qiskit.pulse.commands` probably. It should work though, so unclear!

**Comment by lcapelluto** [comment]
@SooluThomas has been helping me with this

**Comment by SooluThomas** [comment]
The code (in #3849) is correct but the corresponding `.rst` files aren't generated in the `stubs/` folder during the build, which is why `Channels` and `command` are not hyperlinked when the html is generated. I'll look into the details and will open a PR if I find a solution.

**Comment by lcapelluto** [comment]
Thank you @SooluThomas !!! <3

**Comment by SooluThomas** [comment]
`:mod:foo.x` will only add a hyperlink, if the file exists. Currently, the stub files for the modules aren't generated during the build, which is why the hyperlink isn't working. 

The stub files for the modules `qiskit.pulse.channels` and `qiskit.pulse.commands.command` can be created during the build by adding 
```
.. autosummary::
   :hidden:
   :toctree: ../stubs/

   qiskit.pulse.commands.command
   qiskit.pulse.channels
```
to the end of the docstrings so that the stub files will be generated and that particular directive will be hidden.

@nonhermitian Any Ideas?

**Comment by SooluThomas** [comment]
**Update**: Paul agrees to the proposed idea. I'll be opening a PR for this 🎉 :
