### ISSUE TITLE
add visualization of open controlled gates [mpl drawer]

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#3957]
@ewinston says in https://github.com/Qiskit/qiskit-terra/issues/3864:
> In PR #3739, open controlled gates were implemented. With that PR a new keyword argument was added to specify the control state,
> 
> `XGate().control(3, ctrl_state=6)`
> 
> This creates a 4 qubit gate where the first three qubits are controls and the fourth qubit is the target where the x-gate may be applied. A `ctrl_state` may alternatively be expressed as an integer string,
> 
> `XGate().control(3, ctrl_state='110')`
> 
> where it is more apparent which qubits are open and closed. In this case when q[0] is open and q[1] and q[2] are closed the x-gate will be applied to q[4].

As a reference https://github.com/Qiskit/qiskit-terra/pull/3867 implements open controlled gates for the text visualizer like this:
```python
qr = QuantumRegister(4, 'q')
circuit = QuantumCircuit(qr)
circuit.append(U2Gate(pi, -5 * pi / 8).control(3, ctrl_state='100'),
               [qr[0], qr[3], qr[2], qr[1]])
circuit.draw('text')
```
```
                         
q_0: |0>────────o────────
        ┌───────┴───────┐
q_1: |0>┤ U2(pi,-5pi/8) ├
        └───────┬───────┘
q_2: |0>────────■────────
                │        
q_3: |0>────────o────────
```
The current output for `circuit.draw('mpl')` is:
![image](https://user-images.githubusercontent.com/766693/76469326-72dc4700-63c4-11ea-896c-32f28a70d362.png)

**Comment by JayantiSingh** [comment]
Hi @ewinston , I am new to qiskit, but I would like to work on it if you don't mind.

**Comment by enavarro51** [comment]
@1ucian0, I played around with this a bit and think I know how to make the changes. I'm not sure if @JayantiSingh is still interested, but if not, I can take it on.

**Comment by 1ucian0** [comment]
Let's give Jayanti Singh <https://github.com/JayantiSingh> two or three
days for a ping. If silence, go ahead!

**Comment by enavarro51** [comment]
Haven't heard any pinging. Shall I proceed?

**Comment by 1ucian0** [comment]
Sure! Let me know if you need any pointers!

**Comment by enavarro51** [comment]
Thanks, Luciano. I'd already started working on it, and this is what I have done. Given this code,
```
from qiskit import QuantumRegister, QuantumCircuit
from qiskit.extensions import U3Gate, U2Gate
import numpy as np

pi = np.pi
qr = QuantumRegister(4, 'q')
circuit = QuantumCircuit(qr)
circuit.append(U2Gate(pi/8,pi/8).control(3, ctrl_state=2),
               [qr[0], qr[3], qr[2], qr[1]])
circuit.append(U3Gate(3*pi/4,3*pi/4,3*pi/4).control(3, ctrl_state='101'),
               [qr[0], qr[3], qr[2], qr[1]])
circuit.draw(output='mpl')
```
![image](https://user-images.githubusercontent.com/16268251/79022726-784bbf00-7b33-11ea-8c49-6546a67478c4.png)
Is this what you are looking for? I also have a couple of questions.
- Most of this was pretty straightforward, but the layer_width for these ControlledGates was not working correctly. Gates were jumping to very wide spacing. There were two sections in the code for layer_width and these gates fell into a default area. I decided not to change the other 2 sections, but  added a new section for these gates only. I did a lot of testing on the layer width to make sure the boxes were as close as possible horizontally without touching., There are a lot of possible combinations of these gates, though, and I'm wondering if additional QA would be in order.
- Since the output of this code is visual, I'm not sure how one would create a test for this. Any suggestions would help.
Thanks.
