### ISSUE TITLE
Add prelude on quantum_info for 0.13 release notes

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#4001]
### What is the expected behavior?

This issue is to remind me to write a prelude section for the 0.13 release notes summarizing the new classes and many upgrades in the quantum_info module.

**Comment by mtreinish** [comment]
When you do write something we'll have to make sure to integrate it into the broader prelude for the release. The prelude section of reno is the one piece that doesn't do well to have multiple entries since you can't really have more than one prelude providing a high level description of the same release.

**Comment by mtreinish** [comment]
This has been handled by: https://github.com/Qiskit/qiskit-terra/pull/4057 so going to mark this as closed
