### ISSUE TITLE
Error in text drawing of open controlled CX and CCX gates

### ISSUE THREAD

**Issue by TharrmashasthaPV** [Qiskit/qiskit-terra#4052]
### Information

- **Qiskit Terra version**: 0.13.0.dev0+6002304
- **Python version**: 3.7
- **Operating system**: Ubuntu 18.04

### What is the current behavior?

The control bullets are drawn closed irrespective of the provided control state in CX and CCX gates in text drawer. The same error is observed in CY gate. Other controlled and multi-controlled gates are drawn fine. See below for an instance.

![2020-03-30 (2)](https://user-images.githubusercontent.com/51048173/77940422-51d98880-72d6-11ea-9fee-b40f283013b2.png)

### Steps to reproduce the problem

```
qc = QuantumCircuit(4)
qc.append(XGate().control(1,ctrl_state='0'),[0,1])
qc.append(XGate().control(2,ctrl_state='10'),[0,1,2])
qc.append(XGate().control(3,ctrl_state='100'),[0,1,2,3])
qc.append(YGate().control(1,ctrl_state='0'),[0,1])
qc.append(YGate().control(2,ctrl_state='10'),[0,1,2])
qc.draw('text')
```

**Comment by enavarro51** [comment]
@TharrmashasthaPV. I worked on #3957 for a similar problem for the mpl drawer. I mostly followed the code from the text drawer, and now realize the mpl I submitted has this problem as well. I made a minor change to the mpl and now get
![image](https://user-images.githubusercontent.com/16268251/79072389-a0533380-7c95-11ea-9cfc-1c4dd4e42720.png)
I'm going to go ahead and submit this change for #3957 and I can make the necessary changes to the text drawer and also the latex drawer if needed. Should I proceed with this?

**Comment by TharrmashasthaPV** [comment]
> 
> 
> @TharrmashasthaPV. I worked on #3957 for a similar problem for the mpl drawer. I mostly followed the code from the text drawer, and now realize the mpl I submitted has this problem as well. I made a minor change to the mpl and now get
> ![image](https://user-images.githubusercontent.com/16268251/79072389-a0533380-7c95-11ea-9cfc-1c4dd4e42720.png)
> I'm going to go ahead and submit this change for #3957 and I can make the necessary changes to the text drawer and also the latex drawer if needed. Should I proceed with this?

@enavarro51 Yeah, sure. Please go ahead.

**Comment by enavarro51** [comment]
@TharrmashasthaPV I started working on this and the change you mentioned is pretty straightforward, but in the process, I discovered a bug in the ctrl_state code and finally tracked it down today, but haven't finalized a solution yet. The failure is for this gate
`ct.append(XGate().control(3, ctrl_state='101'), [qr[0], qr[3], qr[1], qr[2]])`
which returns
q_0: ──■──
       │  
q_1: ──o──
     ┌─┴─┐
q_2: ┤ X ├
     └─┬─┘
q_3: ──■──
          
q_4: ─────
It should show two closed on top and open on the bottom. The problem is that the order used to iterate over the qubits was based on controlled_top, bot, etc. but this is not necessarily the order of the qargs. So I'm looking at restructuring that section of code. Will let you know how it goes.
