### ISSUE TITLE
U1 gets decomposed into U3

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4144]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
U1 gates are decomposed into U3:

```
qc = QuantumCircuit(1)
qc.u1(0.24,0)
qc.decompose().draw()
```
gives

```
     ┌──────────────┐
q_0: ┤ U3(0,0,0.24) ├
     └──────────────┘
```

This is an issue because U1 is free whereas U3 is not.

It seems that U1 is being mapping to U3 here: https://github.com/Qiskit/qiskit-terra/blob/09240bb25b8117474b0d15467093126ac8115814/qiskit/extensions/standard/u1.py#L91

Note also that the docstrings discuss U3: https://github.com/Qiskit/qiskit-terra/blob/09240bb25b8117474b0d15467093126ac8115814/qiskit/extensions/standard/u1.py#L75

**Comment by ajavadia** [comment]
what is your intention with `decompose()` here? this is how all gates are defined currently - they all build from U3 and CX as their base. This is due to openqasm's hierarchy, and so all gates fundamentally translate to that universal gate set. `decompose()` should not be treated as an optimizer. 
For optimization you should use `transpile()`, and say that your backend supports u1 so that the transpiler keeps it.
```
transpile(qc, basis_gates=['u1', 'u2', 'u3', 'cx'])
```

 If a backend does not support u1, then it all goes to u3. A use case of this could be noise modeling, e.g. as described in this issue https://github.com/Qiskit/qiskit-terra/issues/2762

**Comment by nonhermitian** [comment]
ok, I guess it is my misunderstanding.
