### ISSUE TITLE
import errors -  Modules are missing in qiskit requirements

### ISSUE THREAD

**Issue by hykavitha** [Qiskit/qiskit-terra#4242]
### What is the expected enhancement?
some more python modules to be added to requirements.txt

After we fork, git clone, create conda environment in our local & install pip install -r requirements.txt. I would imagine I should not be installing any more packages or not expecting any import errors. And without any code change, if I run make style / make test, its causing missing modules.
I have been installing separately these packages. With this also, there are some tests which are failing with ddt module not found, etc.. needs to be fixed.

I would look at adding these into requiremnts.txt
  pip install pycodestyle
  pip install pylint
  pip install pylintfileheader
  pip install pylatexenc
  pip install matplotlib
  pip install nbformat
  pip install z3-solver
  pip install pydot
  pip install nbconvert
  pip install pycodestyl
  pip install pylint pylintfileheader
  pip install pydot

**Comment by hykavitha** [comment]
@lcapelluto : if you can assign it to me, I can take care of this issue.

**Comment by mtreinish** [comment]
This isn't actually a bug, those dependencies are not for qiskitt-terra (which is what lives in the requirements.txt file) those are development only dependencies which are listed in requirements-dev.txt file. Those packages are only needed for running tests or linting checks, we don't want users to have to install them when they install terra (which is the pupose of the requirements.txt list). If you read the contributing guide: https://github.com/Qiskit/qiskit-terra/blob/master/CONTRIBUTING.md#test it recommends the use of tox because it will handle the dependencies for you (and also build an isolated venv for testing).

 I'm going to close this issue, feel free to reopen it I'm missing something.
