### ISSUE TITLE
MPL drawer breaks with Isometry

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4352]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: MacOS

When trying to MPL graph an isometry gate, I'm getting a lot of funny outputs, depending on the isometry size.

### What is the current behavior?

considering the following code:
```python
from qiskit import QuantumCircuit
import numpy as np

size =  # <- input
qc = QuantumCircuit(size)
qc.isometry(np.eye(2**size, 2**size), [i for i in range(size)], [])
qc.draw('mpl')
```
```
size = 1
```
![image](https://user-images.githubusercontent.com/766693/80643499-30cf9900-8a36-11ea-8412-4436ca214ae5.png)

```
size = 2
```
![image](https://user-images.githubusercontent.com/766693/80643791-aa678700-8a36-11ea-9738-6e544e696c3b.png)
```
size = 3
```
![image](https://user-images.githubusercontent.com/766693/80643829-b8b5a300-8a36-11ea-8977-54e2d2d16267.png)

### What is the expected behavior?

Something like the text drawer:
```
     ┌──────────┐
q_0: ┤ ISOMETRY ├
     └──────────┘
```

```
     ┌───────────┐
q_0: ┤0          ├
     │  ISOMETRY │
q_1: ┤1          ├
     └───────────┘
```

```
     ┌───────────┐
q_0: ┤0          ├
     │           │
q_1: ┤1 ISOMETRY ├
     │           │
q_2: ┤2          ├
     └───────────┘
```

**Comment by enavarro51** [comment]
@1ucian0. In #4264, I addressed some of these issues, but it's part of a much bigger issue in the mpl drawer. In that PR, I treated hamiltonian and unitary as special cases, but that's not a long-term solution. 

When I first added mulit-control gates in #4131, some of the gates jumped to very large layer_width's, since the code for layering was assuming anything with an op.name of 4 chars or more was a large gate, so ccu3 had a different layer_width from a cu3. I solved this by treating control gates specially, but there's a much bigger issue.

With the advent of labels for all gates, mpl will need some serious redo. There are 3 issues your isometry example points out,
- Single qubit gates are not handled properly, unless they are one of the standard gates, X, H, etc.
- The current code will not handle labels on standard gates properly. If 'X' is replaced by 'This is an X gate', it will create an entirely different gate.
- Width of long name gates in mpl is determined solely by the number of chars in the label/name. This works fine in the text drawer where a monospace font is used, but in mpl, a proportional font is used, so 'MMMMMMMMMM' is much longer than 'iiiiiiiiii'. If we just allow for the worst case M's, there will be a lot of whitespace and overly wide gates. The solution is to calculate the true text width and build the gate size and layer_width from that.

'isometry' can be fixed with a couple of lines of code by creating another special case like 'unitary', and eliminating the printing of matrices like you did in the text drawer. But I believe the bigger issues should also be addressed with a fairly major rework of the mpl drawer code.

**Comment by TharrmashasthaPV** [comment]
Hi @1ucian0 . This problem is primarily seen in the parametrized operations. This is due to very large parameter descriptions since the size of the parameter is used to compute the layer width for each layer of gates. As for isometry, the parameter is the matrix I suppose. So I think if we use the size of parameter to compute the layer width only if the length of the parameter is below an upper bound, then this problem could be solved.
