### ISSUE TITLE
PauliFeatureMap circuit should use jupyter-execute

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4418]
### What is the expected enhancement?

https://qiskit.org/documentation/stubs/qiskit.circuit.library.PauliFeatureMap.html#qiskit.circuit.library.PauliFeatureMap

**Comment by mrvee-qC** [comment]
# Update for Santa:elf:- QGoGP

:white_check_mark: PR #4614 Seems to be stalled which has also stalled this issue. I am not sure if this was ever implemented in any of the other PRs.

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by jakelishman** [comment]
Closing for the same reason as #4417 - this is somewhat stale now, and we don't even use `jupyter-execute` any more.  We've softly been moving in favour of hardcoding output and not having the doctest validation (though that is under consideration in #7661), because of the on-going problems with `jupyter-execute` that eventually caused us to abandon it.

That's not to say we don't want to improve our docs, just that in the current set-up, this particular page doesn't need updating in the manner suggested.
