### ISSUE TITLE
Cannot copy a pulse enabled backend configuration

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4550]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Doing `copy.deepcopy(provider.backends.ibmq_almaden.configuration())` fails with the error:

TypeError: __init__() missing 10 required positional arguments: 'n_uchannels', 'u_channel_lo', 'meas_levels', 'qubit_lo_range', 'meas_lo_range', 'dt', 'dtm', 'rep_times', 'meas_kernels', and 'discriminators'

Non-pulse enabled backends work fine. e.g.

```python
copy.deepcopy(provider.backends.ibmq_vigo.configuration())
```

QasmBackendConfiguration(backend_name='ibmq_vigo', backend_version='1.0.2', basis_gates=['u1', 'u2', 'u3', 'cx', 'id'], conditional=False, coupling_map=[[0, 1], [1, 0], [1, 2], [1, 3], [2, 1], [3, 1], [3, 4], [4, 3]], gates=[GateConfig(id, [], gate id q { U(0,0,0) q; }, [[0], [1], [2], [3], [4]]), GateConfig(u1, ['lambda'], gate u1(lambda) q { U(0,0,lambda) q; }, [[0], [1], [2], [3], [4]]), GateConfig(u2, ['phi', 'lambda'], gate u2(phi,lambda) q { U(pi/2,phi,lambda) q; }, [[0], [1], [2], [3], [4]]), GateConfig(u3, ['theta', 'phi', 'lambda'], gate u3(theta,phi,lambda) q { U(theta,phi,lambda) q; }, [[0], [1], [2], [3], [4]]), GateConfig(cx, [], gate cx q1,q2 { CX q1,q2; }, [[0, 1], [1, 0], [1, 2], [1, 3], [2, 1], [3, 1], [3, 4], [4, 3]])], local=False, max_shots=8192, memory=True, n_qubits=5, open_pulse=False, simulator=False)

**Comment by mtreinish** [comment]
It looks like PulseBackendConfiguration is missing a `__reduce__` method so pickle is trying to call it with the function signature from QasmBackendConfiguration which isn't correct because there are more arguments for the pulse backend configuration's init. 

One thing that is tricky to get with the pickling/deepcopy is extra non-named parameters. This is because these both subclass `SimpleNamespace` which defines it's own custom reduce function. When I encountered this on the result class I had to abandon the use of `SimpleNamespace` because it was losing kwargs. For QasmBackendConfiguration can you confirm that all the fields are there after a deepcopy? Or are all the fields in the backends from ibmq in: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/providers/models/backendconfiguration.py#L310-L314

**Comment by nonhermitian** [comment]
It looks like the QASM fields are all there:

```
{'backend_name': 'ibmq_vigo',
 'backend_version': '1.0.2',
 'n_qubits': 5,
 'basis_gates': ['u1', 'u2', 'u3', 'cx', 'id'],
 'gates': [{'name': 'id',
   'parameters': [],
   'qasm_def': 'gate id q { U(0,0,0) q; }',
   'coupling_map': [[0], [1], [2], [3], [4]]},
  {'name': 'u1',
   'parameters': ['lambda'],
   'qasm_def': 'gate u1(lambda) q { U(0,0,lambda) q; }',
   'coupling_map': [[0], [1], [2], [3], [4]]},
  {'name': 'u2',
   'parameters': ['phi', 'lambda'],
   'qasm_def': 'gate u2(phi,lambda) q { U(pi/2,phi,lambda) q; }',
   'coupling_map': [[0], [1], [2], [3], [4]]},
  {'name': 'u3',
   'parameters': ['theta', 'phi', 'lambda'],
   'qasm_def': 'gate u3(theta,phi,lambda) q { U(theta,phi,lambda) q; }',
   'coupling_map': [[0], [1], [2], [3], [4]]},
  {'name': 'cx',
   'parameters': [],
   'qasm_def': 'gate cx q1,q2 { CX q1,q2; }',
   'coupling_map': [[0, 1],
    [1, 0],
    [1, 2],
    [1, 3],
    [2, 1],
    [3, 1],
    [3, 4],
    [4, 3]]}],
 'local': False,
 'simulator': False,
 'conditional': False,
 'open_pulse': False,
 'memory': True,
 'max_shots': 8192,
 'coupling_map': [[0, 1],
  [1, 0],
  [1, 2],
  [1, 3],
  [2, 1],
  [3, 1],
  [3, 4],
  [4, 3]]}
```

**Comment by nonhermitian** [comment]
I can get around it with a `config.to_dict()` and back to the object so not the end of the world but we had also just fixed this issue earlier.
