### ISSUE TITLE
pulse jobs fail schema validation

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4618]
Every pulse job is failing schema validation. This happened in https://github.com/Qiskit/qiskit-terra/pull/4539.

```py
from qiskit import *

IBMQ.load_account()
p = IBMQ.get_provider(project='......')
backend = p.get_backend('ibmq_armonk')

c = QuantumCircuit(1, 1)
c.measure(0, 0)
c = transpile(c, backend)
s = schedule(c, backend)
qobj = assemble(s, backend=backend, shots=100)
job = backend.run(qobj)
```

**Comment by mtreinish** [comment]
To make #4539  work with our broken system around schemas (because of the lack of versioning and the backwards relationship between iqx and terra) it needs to be reverted on the qobj and assembly side except for the qobj schema changes. Then after the schema changes get included in the next release we can look at adding back the pieces that use the changes. (Note this only works because the change is an addition only and a backwards compatible type change)

Right now the schemas used by iqx rely on the released version of terra as the source of truth for the schema files and are not using versioning. So until we release terra with the updated schema IQX doesn't know about any changes made in the terra and will be using the schema from the last release.

**Comment by taalexander** [comment]
It seems like it may be failing because `rep_time` may be empty? We could provide a dummy value if not supplied to make this pass validation temporarily? @zachschoenfeld33
