### ISSUE TITLE
iplot_state_qsphere

### ISSUE THREAD

**Issue by Qoll** [Qiskit/qiskit-terra#4719]
### Information

- Qiskit Terra version: 0.14.2:
- Python version 3.7:
- Operating system Windows 10:

### What is the current behavior?
Running example code for iplot_state_qsphere from https://qiskit.org/documentation/stubs/qiskit.visualization.iplot_state_qsphere.html#qiskit.visualization.iplot_state_qsphere renders no response

### Steps to reproduce the problem

Open jupyter notebook in Brave Browser and run each line of the example code from https://qiskit.org/documentation/stubs/qiskit.visualization.iplot_state_qsphere.html#qiskit.visualization.iplot_state_qsphere

### What is the expected behavior?
the iplot_state_sphere renders no response

**Comment by mtreinish** [comment]
Thanks for opening an issue about this. Unfortunately the interactive drawers no longer work, they depended on JS code hosted at a URL that no longer exists. We weren't able to preserve the functionality so for this upcoming release we've deprecated it and have the functions just use the matplotlib based drawers: https://github.com/Qiskit/qiskit-terra/pull/4438 This change will be included in the next release. But, since the URL was hardcoded in the `iplot` drawers and that URL no longer works we weren't able to have a migration path for existing releases. I'm going to close this since there is nothing that can be done to address this, but please feel free to reopen if I'm missing something.
