### ISSUE TITLE
Gate functions not "linter-friendly"

### ISSUE THREAD

**Issue by ZamboniM** [Qiskit/qiskit-terra#476]
Hi, I'm using qiskit just by a short time, but I noticed that some methods are not recognized by the linter. (For example `QhantumCircuit.h`)
So in my project there are errors, I can ignore them, but it would be better if the implementation of _qiskit_ take this in consideration.
Thanks, 
Marco

**Comment by diego-plan9** [comment]
Hello Marco,

thanks for the suggestion - it would indeed be ideal, but requires either a more "intelligent" linting solution or a modification on how the gates are currently implemented. The `.h()` method you mention is appended to `QuantumCircuit` dynamically at runtime, and the linter is not able to recognize it as a valid method, since it is mostly based on static analysis.

The topic of how gates are implemented has been touched on other issues as well, as it is a bit inconvenient not only for the linter, but for other purposes - it's not a top priority at the moment, but certainly worth revising. In the meantime, and only for your convenience, perhaps your IDE supports an option similar to [the `generated-members` pylint directive](https://github.com/QISKit/qiskit-sdk-py/blob/master/.pylintrc#L300) that might alleviate the issue?

**Comment by delapuente** [comment]
A better way of doing this is being discussed in #316.
