### ISSUE TITLE
qc.draw() doesn't show the circuit diagram

### ISSUE THREAD

**Issue by abhishekengg24** [Qiskit/qiskit-terra#4895]
I wrote a simple program to get the output
```python
qc = QuantumCircuit(1)
qc.h(0)
qc.z(0)
qc.h(0)
qc.draw()
backend = Aer.get_backend('statevector_simulator')
result = execute(qc,backend).result() # Do the simulation, returning the result
out_state = result.get_statevector()
print(out_state)
out = execute(qc,backend).result().get_statevector()
plot_bloch_multivector(out)
```
when I check the result I just get the  statevector output and the bloch sphere output but not the Circut diagram( qc.draw() )
But when i just do the below it works fine :
```python
qc = QuantumCircuit(1)
qc.h(0)
qc.z(0)
qc.h(0)
qc.draw()
```

### What is the expected enhancement?

My request is qc.draw() can be mentioned in any part of the code and it should show the Quantum circuit and then the result

**Comment by Cryoris** [comment]
The `draw` method without any arguments returns a string representing the circuit. If you want to display the string, you have to print it:
```python
print(qc.draw())
```

About the second code snippet: Did you run this in a Jupyter notebook? If yes, the output of the last line is implicitly shown as output, which is why in the second code example you see a circuit.

**Comment by SiddTim** [comment]
It does work if you replace it with `print(qc.draw())`

**Comment by TanveshT** [comment]
The error is occurring mainly due to the attempt of plotting multiple plots after the execution of the same code cell block.

**Comment by Cryoris** [comment]
@abhishekengg24 Feel free to re-open if you think we're missing something here.
