### ISSUE TITLE
Show pi in the text drawer as π

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#4959]
### What is the expected enhancement?

Based on a discussion in #4931, there's interest in displaying pi in the text drawer as `π `instead of `pi`.
``` 
                   ┌─────────┐               ┌─────────┐
Change from   q_0: ┤ RX(pij) ├     to   q_0: ┤ RX(πj)  ├
                   └─────────┘               └─────────┘
```
To do this on all platforms requires completion of #4900 and modifying pi_check and 24 tests.

**Comment by PaulMcElligott** [comment]
Can I be assigned this issue please? I'd like to give it a shot, I actually think it might be a good first issue.

**Comment by enavarro51** [comment]
It's ok by me. @1ucian0 Ok by you?

**Comment by 1ucian0** [comment]
Sure

**Comment by 1ucian0** [comment]
ping @PaulMcElligott ! Any news?

**Comment by PaulMcElligott** [comment]
Still working on it. 
Have been busy. I'll have more time tomorrow morning.

**Comment by 1ucian0** [comment]
another ping @PaulMcElligott?

**Comment by PaulMcElligott** [comment]
Hi @1ucian0. I have managed to recreate the issue, but I'm having difficulty recreating it in a new environment. I have been following @aasfaw's episode closely. I am new to using git & anaconda.


### Method to reproduce
```
from qiskit import *
import numpy as np
import sympy
from sympy.abc import pi
pi = np.pi
qr = QuantumRegister(1)
circuit_all = QuantumCircuit(qr)
circuit_all.rx(pi,0)
circuit_all.draw()
       ┌────────┐
q10_0: ┤ RX(pi) ├
       └────────┘
circuit_all.draw(output='mpl')
```
mpl (below) subtext uses the greek letter '&pi;' instead of the latinized 'pi'
![image](https://user-images.githubusercontent.com/25926103/94480571-67206880-01ce-11eb-8267-ccde818fe72a.png)

### Action plan

1. Attempt pass in a greek letter &pi; using **sympy** in the notebook.
2. Inspect **visualization.matplotlib.py** to see what the mpl uses for greek letters and try to insert it in the code in **visualiztions.txt.py**

**Comment by 1ucian0** [comment]
You might be overthinking this one.

Either `inpt` in `pi_check` can take the `self.encoding` as input, or you replace `pi`  by `π` after that (if the encoding allows it).

**Comment by alejomonbar** [comment]
@PaulMcElligott are you still in it? can I try this one? @1ucian0

**Comment by 1ucian0** [comment]
Sure! Go ahead @alejomonbar
