### ISSUE TITLE
HoareOptimizer does not handle CZ correctly 

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#4981]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7.8
- **Operating system**: MacOS

### What is the current behavior?

Consider the following program, where `circuit_in` is optimized by `HoareOptimizer` pass as `circuit_out` :
```python
from numpy import pi
from qiskit import *
from qiskit.converters import *
from qiskit.transpiler.passes import HoareOptimizer
from qiskit.transpiler.passmanager import PassManager

circuit_in = QuantumCircuit(2)
circuit_in.h(0)
circuit_in.x(1)
circuit_in.cz(0, 1)
circuit_in.h(0)
circuit_in.measure_all()

def print_circuit_and_counts(circuit):
    print(circuit)
    backend = BasicAer.get_backend('qasm_simulator')    
    print(execute(circuit, backend=backend, optimization_level=0).result().get_counts())

print_circuit_and_counts(circuit_in)

pm = PassManager()
pm.append(HoareOptimizer(size=10))
circuit_out = pm.run(circuit_in)

print_circuit_and_counts(circuit_out)
```
```
        ┌───┐   ┌───┐ ░ ┌─┐   
   q_0: ┤ H ├─■─┤ H ├─░─┤M├───
        ├───┤ │ └───┘ ░ └╥┘┌─┐
   q_1: ┤ X ├─■───────░──╫─┤M├
        └───┘         ░  ║ └╥┘
meas: 2/═════════════════╩══╩═
                         0  1 
{'11': 1024}
              ░ ┌─┐   
   q_0: ──────░─┤M├───
        ┌───┐ ░ └╥┘┌─┐
   q_1: ┤ X ├─░──╫─┤M├
        └───┘ ░  ║ └╥┘
meas: 2/═════════╩══╩═
                 0  1 
{'10': 1024}
```

The optimization fully removes the `H-CZ-H` sequence wrongly, breaking the semantics equivalence of the transformation.

### What is the expected behavior?

I'm not fully sure if the original paper deals with phase (maybe the root of the problem). From what I remember, it seems to me that the qubit `q_1` falls into a "trivial condition" and the CZ should be replaced by a Z gate in `q_0`.

Notice that `circuit_in.cz(1, 0)` (instead of `circuit_in.cz(0, 1)` does not break the counting, since `HoareOptimizer` does not detect any optimization, which is also unexpected. Maybe the problem is related to #4980?

**Comment by georgios-ts** [comment]
Same issue is caused if you use `CRZ` or `CU1`. 

What's happening is that `HoareOptimizer` thinks these gates act trivially and removes them. Rephrasing lines [125-133](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/optimization/hoare_opt.py#L125), one of the above gates is considered  to act trivially if whenever the control qubits are in $$\inline | 1 \rangle$$ state, the target qubit is in a definite state, meaning  always in $$\inline | 0 \rangle$$ or $$\inline | 1 \rangle$$ but not in a superposition. But the problem is that

$$ CZ_{01} \Big((a | 0 \rangle + b | 1 \rangle)_0 \otimes | 1 \rangle_1 \Big) = (a | 0 \rangle - b | 1 \rangle)_0 \otimes | 1 \rangle_1 \Big  $$

which is not actually a trivial action,  unless only measurements follow, (neither i think it's considered trivial in the original paper, see [Def 5.3](https://arxiv.org/pdf/1810.00375.pdf)) and so `CZ` should not be removed.

I think the correct statement would be that these controlled gates act indeed trivially if:
* the control qubits are always in state  $$\inline | 1 \rangle$$ and the target qubit is in a definite state, or
* the control qubits are in a state orthogonal to $$\inline | 1 \rangle$$ state.
(i am talking more generally about multiple-controlled versions of these gates.)
Specifically, it's currently missing a test which  should assert that if the control qubits can be in $$\inline | 1 \rangle$$ then it's the only state that they can be.

Furthermore, as you are suggesting an other optimization step could be to replace a Controlled-Unitary gate with the Unitary if the control qubits are always in $$\inline | 1 \rangle$$ state. But as far as i understand, this isn't the initial intention of `HoareOptimizer`.

If you think this is correct, i will try to implement it.

**Comment by georgios-ts** [comment]
Same issue is caused if you use `CRZ` or `CU1`.

What's happening is that `HoareOptimizer` thinks these gates act trivially and removes them. Rephrasing lines [127-133](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/optimization/hoare_opt.py#L127), one of the above gates is considered to act trivially if whenever the control qubits are in |1> state, the target qubit is in a definite state, meaning always in |0> or |1> but not in a superposition. But the problem is that
 
<img src="https://render.githubusercontent.com/render/math?math=CZ_{0,1} (a |0 > %2B b |1>)_0 \otimes 1>_1 = (a |0 > - b |1>)_0 \otimes 1>_1">

which is not actually a trivial action, unless only measurements follow, (neither i think it's considered trivial in the original paper, see [Def 5.3](https://arxiv.org/pdf/1810.00375.pdf)) and so CZ should not be removed.

I think the correct statement would be that these controlled gates act indeed trivially if:
* the control qubits are always in state |1> and the target qubit is in a definite state, or
* the control qubits are in a state orthogonal to |1> state.
(i am talking more generally about multiple-controlled versions of these gates.)
Specifically, it's currently missing a test which should assert that if the control qubits can be in |1> then it's the only state that they can be.

Furthermore, as you are suggesting an other optimization step could be to replace a Controlled-Unitary gate with the Unitary if the control qubits are always in |1> state. But as far as i understand, this wasn't the initial intention of `HoareOptimizer`.

If you think this seems right, i will try to implement it.

**Comment by 1ucian0** [comment]
Hmm.. you are right that this case is not the paper's trivial case. So the original papers removes gates only but cannot replace gates? Probably @ajavadia has an opinion here.

**Comment by ajavadia** [comment]
the H-CZ-H part is a CNOT (with control on the bottom). So the correct optimization would be to replace it with an X, meaning the whole circuit becomes 2 X gates (one top, one bottom). If the Hoare optimizer considers gates one-by-one then it might not detect that.
