### ISSUE TITLE
Warning for deprecated makefile targets?

### ISSUE THREAD

**Issue by levbishop** [Qiskit/qiskit-terra#5045]
Following from #4942 #4939 :

Since `make test` is deprecated and not everyone checks CONTRIBUTING.MD for updates, perhaps the makefile target should emit a deprecation message? Are there other deprecated targets?

**Comment by 1ucian0** [comment]
Is `make test` deprecated?

**Comment by levbishop** [comment]
Actually 'deprecated' is too strong a term since we don't have plans to remove it as far as I know, but if tox is the preferred route for testing (for the reasons explained in CONTRIBUTING) we could emit a message to that effect. (I don't have a very strong opinion about it in case people think it's not a good idea)

**Comment by 1ucian0** [comment]
Do you think `make test` should run tox?

**Comment by 1ucian0** [comment]
Can this one be closed @levbishop @mtreinish ?

**Comment by mtreinish** [comment]
I would be in favor of adding a warning or something, but I don't think the makefile will be going away. I've been trying to get people to use tox more for a long time because it solves the dependency and install problems and sets up isolated envs for testing (basically everything I outlined in the PRs and the contributing guide). But, there are some active contributors who prefer using the Makefile and I've never been able to convince them to abandon the `make test` alias for unittest.run to manually invoke a test runner (whether it be pytest, unittest.run, stestr, etc).

**Comment by 1ucian0** [comment]
Something like #5290 ?

**Comment by nonhermitian** [comment]
I only use the `make` file.
