### ISSUE TITLE
FakeTokyo properties does not match coupling map

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5111]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
The properties for `FakeTokyo` does not match the coupling map; there are 2Q gates in the properties that are not in the coupling_map, e.,g.

```
[1, 7]
[17, 18]
[18, 17]
```

I believe some valid ones are also missing.

This is blocking #5105.

**Comment by mtreinish** [comment]
Looking at the git log for the snapshot of the properties: https://github.com/Qiskit/qiskit-terra/commits/master/qiskit/test/mock/backends/tokyo/props_tokyo.json it hasn't been updated in a while. I assume this is because the device isn't online anymore. We've periodically run updates of the snapshots to get new parameters and updated data (for example: https://github.com/Qiskit/qiskit-terra/pull/4567 ) but tokyo doesn't get updated because there is nothing in the backends list for it anymore (or at least for the provider I typically use for updating things).

I think we can fix this a couple of ways, either hand edit the properties, delete the properties for tokyo, or if someone has access to the last properties payload for the device before it was retired we can use that.
