### ISSUE TITLE
Consider replacing problematic language

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-terra#5152]
I noticed in the release notes that two new classes, `AncillaRegister` and `AncillaQubit` have been added. There was some discussion with the community a while back that 'ancilla' is potentially problematic as [it comes from 'maid, slave-girl'](https://en.wiktionary.org/wiki/ancilla).

Although 'ancilla' is a very common term in quantum computing (and I imagine most users will not be aware of its etymology) it seems 'auxiliary' could be a direct replacement in this context, which would be an easy fix that does not have the same connotations.

It would be great if there was a way to slowly wean 'ancilla' out of qiskit in favour of something else.

**Comment by delapuente** [comment]
Ey @1ucian0, any news on this?  Did you have any conversation?

**Comment by mtreinish** [comment]
So I think this would be fine to do, but before we can start to do anything here it's necessary to settle on standard terminology (which is arguably a larger concern than just qiskit because ancilla is standard term in quantum computing).

That being said we can start to take a look at the ancilla usage in qiskit to size the work. Using grep on the repo yields the following usage of ancilla (case-insensitive):

```
qiskit/__init__.py:1
qiskit/dagcircuit/dagcircuit.py:2
qiskit/extensions/quantum_initializer/isometry.py:49
qiskit/extensions/quantum_initializer/mcg_up_to_diagonal.py:13
qiskit/transpiler/passes/layout/__init__.py:2
qiskit/transpiler/passes/layout/apply_layout.py:1
qiskit/transpiler/passes/layout/enlarge_with_ancilla.py:4
qiskit/transpiler/passes/layout/full_ancilla_allocation.py:15
qiskit/transpiler/passes/layout/sabre_layout.py:4
qiskit/transpiler/passes/layout/trivial_layout.py:1
qiskit/transpiler/passes/__init__.py:4
qiskit/transpiler/preset_passmanagers/level0.py:5
qiskit/transpiler/preset_passmanagers/level1.py:5
qiskit/transpiler/preset_passmanagers/level2.py:4
qiskit/transpiler/preset_passmanagers/level3.py:4
qiskit/opflow/gradients/circuit_gradients/lin_comb.py:1
qiskit/circuit/gate.py:1
qiskit/circuit/quantumregister.py:5
qiskit/circuit/__init__.py:3
qiskit/circuit/quantumcircuit.py:43
qiskit/circuit/add_control.py:8
qiskit/circuit/library/arithmetic/functional_pauli_rotations.py:3
qiskit/circuit/library/arithmetic/integer_comparator.py:21
qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py:18
qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py:18
qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py:5
qiskit/circuit/library/arithmetic/weighted_adder.py:16
qiskit/circuit/library/arithmetic/piecewise_chebyshev.py:9
qiskit/circuit/library/boolean_logic/quantum_and.py:8
qiskit/circuit/library/boolean_logic/quantum_or.py:8
qiskit/circuit/library/generalized_gates/mcmt.py:25
qiskit/circuit/library/standard_gates/x.py:62
qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py:19
qiskit/circuit/library/grover_operator.py:17
qiskit/visualization/gate_map.py:2
qiskit/algorithms/amplitude_estimators/estimation_problem.py:1
qiskit/algorithms/amplitude_estimators/iae.py:2
qiskit/algorithms/amplitude_estimators/mlae.py:1
qiskit/algorithms/linear_solvers/matrices/tridiagonal_toeplitz.py:17
qiskit/algorithms/linear_solvers/hhl.py:10
test/python/compiler/test_sequencer.py:1
test/python/compiler/test_transpiler.py:1
test/python/algorithms/test_linear_solvers.py:1
test/python/visualization/test_pass_manager_drawer.py:5
test/python/visualization/references/pass_manager_standard.dot:2
test/python/visualization/references/pass_manager_style.dot:2
test/python/visualization/references/test_latex_partial_layout.tex:2
test/python/visualization/test_circuit_text_drawer.py:17
test/python/transpiler/test_enlarge_with_ancilla_pass.py:11
test/python/transpiler/test_full_ancilla_allocation.py:43
test/python/transpiler/test_preset_passmanagers.py:77
test/python/circuit/library/test_mcmt.py:8
test/python/circuit/library/test_piecewise_chebyshev.py:3
test/python/circuit/library/test_weighted_adder.py:1
test/python/circuit/library/test_boolean_logic.py:7
test/python/circuit/library/test_functional_pauli_rotations.py:4
test/python/circuit/library/test_grover_operator.py:2
test/python/circuit/library/test_linear_amplitude_function.py:3
test/python/circuit/test_controlled_gate.py:49
test/python/circuit/test_circuit_registers.py:28
test/python/circuit/test_equivalence.py:1
test/python/circuit/test_piecewise_polynomial.py:3
test/python/circuit/test_register.py:11
test/python/circuit/test_registerless_circuit.py:8
test/ipynb/mpl/test_circuit_matplotlib_drawer.py:1
```
The majority of these would be a simple find and replace (especially everything in the tests) as they're internal variables, but there are several things like the `AncillaQubit` class and kwargs for functions and classes that we would need to deprecate before we can change. For example,
places like: https://github.com/Qiskit/qiskit-terra/blob/a026b627b3462ee116357a7042641cc1c2186af4/qiskit/extensions/quantum_initializer/isometry.py#L66 will need to deprecate the old name to allow any users passing any of those arguments by name a chance to adjust. There are a bunch of places and things like this mixed into that list.

I'd say once there is a decision on a new standard terminology we can start by doing the simple find replace on internal variables and tests as a first pass and then do follow on PRs to start adding new things and deprecations.

**Comment by jakelishman** [comment]
Given that we're now 2.5 years on from this issue, and (to the best of my knowledge) neither we nor the quantum-computing community has really converged on any other terminology, I'll close this discussion as staled.

If there's renewed interest in continuing this discussion with a view to actually effecting a change, please feel free to re-open this.
