### ISSUE TITLE
Integrate QFAST

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5202]
Integrate QFAST (Quantum Fast Approximate Synthesis Tool) into qiskit for unitary synthesis. @edyounis is QFAST author.

Check out these resources:
- https://pypi.org/project/qfast/
- https://github.com/BQSKit/qfast

**Comment by mtreinish** [comment]
What advantages does this provide on top of the KAK decomposition we have in terra already? Is it faster, more deterministic, etc? I could see it easily being an improvement over the existing decomposition code, but I think we should make those advantages clear before working on integrating this.

Although, before we can include a dependency like this we have to make sure it's under a compatible license. Right now there is no license information available for the package (besides the copyright that says all rights reserved) so I don't think we can use this package without it being released under a compatible open source license.

**Comment by nonhermitian** [comment]
Was about to say the sane thing about the license. "Contact the Berkeley IP office" is not a good omen.

**Comment by 1ucian0** [comment]
They recently added [a license](https://github.com/BQSKit/qfast/blob/master/LICENSE.txt): BSD-3-Clause-LBNL

From what I understand, it is compatible.

**Comment by edyounis** [comment]
I can't speak for the Qiskit team, but I think the PR has been abandoned. QFAST has since been implemented inside of BQSKit, which is available on [GitHub](https://github.com/BQSKit/bqskit/). There is also a tutorial on how to use QFAST and other BQSKit synthesis and optimization tools [here](https://github.com/BQSKit/bqskit-qce-tutorial).

Qiskit has created a synthesis plugin mechanism, and @mtreinish started on a BQSKit plugin which you can follow [here](https://github.com/mtreinish/bqskit-qiskit-synthesis-plugin).

**Comment by HuangJunye** [comment]
Thanks for the reply and providing the additional information. In this case, should we close the issue and the PR #5573?
