### ISSUE TITLE
Backend configuration should include max_parallel_threads and max_parallel_experiments

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5208]
From https://quantumcomputing.stackexchange.com/questions/14082/how-to-set-max-parallel-threads-max-parallel-experiments-for-backend-option#comment19173_14083
> Wondering whether the backend I am using supports parallel-threads or experiments and how to use this features? How do I find out whether my backend supports this?

**Comment by mtreinish** [comment]
This should not be part of backend configuration. `BackendConfiguration`  is for the immutable properties of a device, both `max_parallel_threads` and `max_parallel_experiments` are user options (think like shots) for a running a circuit on qiskit-aer. These do not belong in backend configuration. It looks like the original post it is because these are exposed as top level kwargs in Aqua's quantum instance which is a wrapper around of this (and imo makes everything more confusing). 

That being said I agree in the v1 interface there is no standardized interface for knowing and tweaking the user configurable options of a Backend, That's why in #5086 we added a standardized interface for options in the Options class. Each provider defines the options supported by a backend (and their default values) when the backend is initialized. Things will start being migrated to this after 0.16.0 is released (for example see #5128) which will expose this interface. Although in the case of that OP the interface in aqua still won't make any of this clear.

I'm going to close this since I don't think there is anything to do here. Please feel free to reopen if I'm missing something or there is more to discuss.
