### ISSUE TITLE
Performance regression in ConsolidateBlocks (optimization_level=3)

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5264]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

https://qiskit.github.io/qiskit/#ripple_adder.RippleAdderTranspile.time_transpile_simulator_ripple_adder?p-size=10&p-size=20&p-level=0&p-level=1&p-level=2&p-level=3&commits=2bd49408

Introduced in #4763 , likely at https://github.com/Qiskit/qiskit-terra/blob/ee854fb/qiskit/transpiler/passes/optimization/consolidate_blocks.py#L150 .

**Comment by kevinhartman** [comment]
@kdk is this possibly fixed by #7185?

**Comment by mrvee-qC** [comment]
# Update for Santa- QGoGP
❓ PR https://github.com/Qiskit/qiskit/pull/1186 seems to have removed `time_transpile_simulator_ripple_adder` and all tests depending on BasicAer entirely. Original link posted by OP needs an update. 

Closest equivalent benchmark -https://qiskit.github.io/qiskit/#ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder?p-level=3. For these tests, there are quite a few performance improvements since the posting of this issue!

The block mentioned by OP resulted due to adding synthesis-based translation method in PR #4763 still exists but there have been significant changes since then as mentioned above also in #7185
#### Older check
https://github.com/Qiskit/qiskit-terra/blob/ee854fb/qiskit/transpiler/passes/optimization/consolidate_blocks.py#L150
#### Current implementation
https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/transpiler/passes/optimization/consolidate_blocks.py#L109

Will update comment/add more comments if cause is found/fixed!

> Python version 3.9.7
> qiskit-terra version: 0.19.1

**Comment by jakelishman** [comment]
Since #7185, `ConsolidateBlocks` is faster than it's ever been, so I'll close this as "almost certainly fixed".
