### ISSUE TITLE
Add interactive drawer

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#5326]
### What is the expected enhancement?

add interactive drawing backend for pulse. there is MVP based on Bokeh.

**Comment by jakelishman** [comment]
I'm going to close this request now as "stale", and because there's insufficient developer/maintainer time to commit to significantly expanding visualisation capabilities in this regard.  The current Qiskit position is that full-featured visualisation modules should probably be maintained in a separate ecosystem package, rather than being in the core library.

If there's more to say, please feel free to discuss or open new issues.
