### ISSUE TITLE
Circuit drawers do not respect classical conditional ordering

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5387]
### Information

- **Qiskit Terra version**: 0.16.0
- **Python version**:
- **Operating system**:

### What is the current behavior?
Having gates conditioned on measurements performed earlier are moved before the measurements in the circuit drawing

eg

```
qr = QuantumRegister(3)
cr = ClassicalRegister(2)
qc = QuantumCircuit(qr,cr)
qc.reset(range(3))
qc.h(1)
qc.cx([1,0],[2,1])
qc.h(0)
qc.measure([0,1], [0,1])
qc.z(2).c_if(cr, 1)
qc.x(2).c_if(cr, 2)
```
```
                            ┌───┐┌─┐       
q6_0: ─|0>──────────────■───┤ H ├┤M├───────
           ┌───┐      ┌─┴─┐ └┬─┬┘└╥┘       
q6_1: ─|0>─┤ H ├──■───┤ X ├──┤M├──╫────────
           └───┘┌─┴─┐ ├───┤  └╥┘  ║  ┌───┐ 
q6_2: ─|0>──────┤ X ├─┤ Z ├───╫───╫──┤ X ├─
                └───┘ └─┬─┘   ║   ║  └─┬─┘ 
                     ┌──┴──┐  ║   ║ ┌──┴──┐
c9: 2/═══════════════╡ = 1 ╞══╩═══╩═╡ = 2 ╞
                     └─────┘  1   0 └─────┘

```

<img width="467" alt="Screen Shot 2020-11-11 at 19 14 01" src="https://user-images.githubusercontent.com/1249193/98878880-1305d680-2452-11eb-9d5e-2c2900babe1e.png">

**Comment by enavarro51** [comment]
This is interesting. I believe the problem is in `_get_layered_instructions` which builds the list of layers for the drawers to use. There are apparently several problems here. Using simplified circuits, I get these different results. So I'm working on it.
![image](https://user-images.githubusercontent.com/16268251/98965695-33b84580-24bf-11eb-9eaa-13bc1c62815f.png)
![image](https://user-images.githubusercontent.com/16268251/98966034-9f9aae00-24bf-11eb-9a70-f71ee0785a1d.png)
![image](https://user-images.githubusercontent.com/16268251/98965827-5ba7a900-24bf-11eb-9a03-1b24b0b6e5bc.png)

**Comment by enavarro51** [comment]
@nonhermitian, I found the bug that was causing the inconsistency in the placement of the Z with condition in my circuits 1 and 3 above. I am now working on your original issue.

Given this circuit,
```
qr = QuantumRegister(3)
cr = ClassicalRegister(3)
qc = QuantumCircuit(qr,cr)
qc.h(range(2))
qc.measure(0, 0)
qc.measure(1, 1)
qc.z(2).c_if(cr, 4)
qc.draw('mpl')
```
I assume that since the bit that the Z is conditioned on is not affected by the measures, that the Z can shift to the left under the H gates.

But if we replace the Z line with `qc.z(2).c_if(cr, 2)`, then the Z gate will have to be to the right of the qc.measure(1,1). If that's the way it should work then I can implement that in `_get_layered_instruction`.

**Comment by nonhermitian** [comment]
Yes that is correct. You cannot be conditioned on a measurement value and displayed before that measurement occurs

**Comment by enavarro51** [comment]
Thanks.

**Comment by 1ucian0** [comment]
Maybe an issue in the DAG topological order?

**Comment by enavarro51** [comment]
The `circuit_to_dag `call in `_get_layered_instructions` puts the nodes in the right order. The problem comes in the `slide_from_left` call. There are no checks for `node.condition` which means a node with condition behaves the same as one without.

My idea is to create a `measure_map` with an entry for each clbit. Then for each measure, the appropriate clbit entry would record the layer number of that measure. Then any subsequent nodes with condition on that clbit would only be allowed in positions following that measure's layer.

It's doable, but I'm open to a simpler solution if one exists.

**Comment by nonhermitian** [comment]
I would also just make sure that a conditional is not moved if the user makes a mistake and puts it before a measurement; the drawing is faithful to the circuit instructions even if wrong.

**Comment by enavarro51** [comment]
> I would also just make sure that a conditional is not moved if the user makes a mistake and puts it before a measurement; the drawing is faithful to the circuit instructions even if wrong.

Yes, that's how #5397 is implemented. It follows the DAG, so unless a measure is seen first on a particular register, it will not change where to put a subsequent conditional on that register.
