### ISSUE TITLE
SparsePauliOp.__getitem__ causes a problematic behavior with numpy’s __mul__

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-terra#5408]
### Information

- **Qiskit Terra version**:master (b5d5a3b)
- **Python version**: 3.8.5
- **Operating system**: macOS

### What is the current behavior?

SparsePauliOp does not support a multiplication with np.int64, np.float64, and...

### Steps to reproduce the problem

For example,
```python
from qiskit.quantum_info import SparsePauliOp, Pauli
import  numpy as  np
print(np.int(2) * SparsePauliOp(Pauli(label='X')))
print('--------')
print(np.int64(2) * SparsePauliOp(Pauli(label='X')))
```
outputs
```
SparsePauliOp([[ True, False]],
              coeffs=[2.+0.j])
--------
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[SparsePauliOp([[ True, False]],
              coeffs=[2.+0.j])]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
```

### Suggested solutions

There are many solutions.
One is `__getitem__` returns a tuple of Pauli and coeff.
Current SprsePauliOp can get an item again and again. e.g. sp is instance of SparsePauliOp and we can get `sp[0][0][0][0]...`

I found this in https://github.com/Qiskit/qiskit-terra/pull/5261

**Comment by chriseclectic** [comment]
It looks like numpy ufunc `np.multiply(val, op)` is getting called before the `op.__rmul__(val)`, because somehow it thinks it can treat SparePauliOp as an array. 

I don't really understand how numpy ufuncts interact with the getitem method, but one fix is telling numpy dispatch to use the correct method by adding this to the SparsePauliOp class:

```python
    def __array_ufunc__(self, ufunc, method, *args, **kwargs):
        if (ufunc == np.multiply and method == '__call__') and not kwargs:
            value = args[0] if isinstance(args[1], SparsePauliOp) else args[1]
            return self._multiply(value)
        return NotImplemented
```

Separately it might be good to make getitem return a tuple if the key is an integer rather than a range or slice to prevent the recursion you discovered.

**Comment by ikkoham** [comment]
I didn't know `__array_ufunc__`, so I learned it via this issue. 
I hope you consider the other issue (return a tuple). Thank you.
