### ISSUE TITLE
Result.utils.marginal_counts returns inconsistent creg structure for multiple cregs

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#5424]
### Information

- **Qiskit Terra version**: master @ d26f273d
- **Python version**: 3.6
- **Operating system**: osx

### Steps to reproduce the problem

```python
from qiskit import *

qr_data = QuantumRegister(3, 'qr_data')
qr_anc = QuantumRegister(2, 'qr_anc')
cr_data = ClassicalRegister(3, 'cr_data')
cr_anc = ClassicalRegister(2, 'cr_anc')

qc = QuantumCircuit(qr_data, qr_anc, cr_data, cr_anc)
qc.x(qr_data)
qc.measure(qr_data, cr_data)
qc.measure(qr_anc, cr_anc)
qc.draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/101812675-aaaa2380-3ae9-11eb-9d8a-cfe8c0afc6d1.png)

```python
result = execute(qc, Aer.get_backend('qasm_simulator')).result()
result.get_counts()
```
```
{'00 111': 1024}
```

```python
from qiskit.result.utils import marginal_counts
marginal_counts(result, [0, 1, 2]).get_counts()
```
```
{'11 1': 1024}
```

**Comment by enavarro51** [comment]
@kdk Just to confirm. The right answer should be `{'111': 1024}` and if the indices are changed
 to `[0, 1, 2, 3]`, it would be `{'0 111': 1024}` and `[0, 2, 4]` would be `{'011': 1024}` or `{'0 11': 1024}`?

**Comment by kdk** [comment]
> @kdk Just to confirm. The right answer should be `{'111': 1024}` and if the indices are changed
> to `[0, 1, 2, 3]`, it would be `{'0 111': 1024}` and `[0, 2, 4]` would be `{'011': 1024}` or `{'0 11': 1024}`?

The first two examples are consistent with what I'd expect. For the last, I'd expect `0 11`.

**Comment by enavarro51** [comment]
Thanks. I think I've found where the problem is, and right now I'm working on finding a reasonable solution. It's weird, there are about a dozen tests for marginal counts, but none of them seem to set memory_slots to less than the number of cregs.

**Comment by enavarro51** [comment]
This is meant as the start of a discussion about `marginal_counts()` which grows out of this issue.

The problem with a solution for the case above is that the final output, say [0, 2, 4] giving you `'0 11'` is that it is not unique. [0, 1, 4], [1, 2, 3], etc. will give you the same `'0 11'`. If this is passed to another function, all the original indices info is lost.

As an alternative, first consider how `marginal_counts()` currently works.
- If it is passed a counts dict as an arg, it removes the spaces from any count strings and computes the marginal counts. For example, returning `'011'` in the case above.
- If it is passed a Result object, it takes the counts from there and does the same marginal counts computation and then converts the returned string to a hex value in the counts dict and reduces the `memory_slots` count to the number of bits in the string. It then returns the modified Result object. 

There are 2 problems here,
- The counts string, `'011'` in our case, loses information of what indices were used. As a solution it would be possible to post-format the counts by adding spaces between cregs and a placeholder, maybe _ or x, for non-indices. So in our example the post-format string would be `'0_ 1_1'` or `'0x 1x1'`. Now it's clear what indices were chosen and these strings should work properly for any plot labels, since spaces are already used.
- The second problem is that passing a Result object to `marginal_counts()` and then modifying it (or a copy of it) does not currently work if `get_counts()` is called on that Result. It might be possible to modify the `creg_sizes` along with `memory_slots`, but this creates a fair amount of overhead and in the end you are just left with `'0 11'` as output with no indices information.
A solution here would be to deprecate passing a Result object to `marginal_counts()` and instead add an `indices` kwarg to `get_counts()`. Then `get_counts()` will call `marginal_counts()` if `indices` is not None, and the post-formatted output returned, resulting in `'0_ 1_1'` or `'0x 1x1'` as the string part of the `get_counts()` output.

Any feedback would be appreciated.
