### ISSUE TITLE
Explicitly construct C3X and C4X in MCXGrayCode

### ISSUE THREAD

**Issue by hay-k** [Qiskit/qiskit-terra#5447]
### Information

- **Qiskit Terra version**: latest GitHub code
- **Python version**: N/A
- **Operating system**: N/A

### What is the current behavior?
The docstring of the `MCXGate` constructor says "creates an explicit CX, CCX, C3X or C4X instance or a generic MCX gate", however it explicitly creates CX and CCX only.

### Steps to reproduce the problem
N/A

### What is the expected behavior?
Create C3X and C4X gates explicitly as well.

**Comment by Cryoris** [comment]
We have different implementations for MCX gates depending on the number of additional qubits available, namely based on gray-code (no additional qubits), recursion (one additional qubit) or a v-chain (several additional qubits). If we have one or two controls then all these methods generate a CX and CCX gate. However starting from three controls, the implementations start to differ in depth and width. Since the C3X and C4X gates don't use additional qubits, we should only explicitly construct them for the gray-code variant of MCX, i.e. in the `MCXGrayCode` class.

**Comment by enavarro51** [comment]
@Cryoris I have an implementation of this ready if no one else is working on it.

**Comment by Cryoris** [comment]
I'm not aware on anyone else working on it, feel free to open a PR! 🙂

**Comment by enavarro51** [comment]
Thanks.
