### ISSUE TITLE
Migration guide of Qiskit Aqua

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#5493]
### What is the expected enhancement?

The core module of Qiskit Aqua is migrating to Qiskit Terra now. 
https://github.com/Qiskit/qiskit-terra/pull/5422
https://github.com/Qiskit/qiskit-terra/pull/5460
https://github.com/Qiskit/qiskit-terra/pull/5479
https://github.com/Qiskit/qiskit-terra/pull/5477

Because it is a big change for developers, we need a migration guide for developers, e.g., how to replace import names, etc.

**Comment by mtreinish** [comment]
We probably should wait until things are more finalized before we start writing a migration guide in the documentation. Those PRs are just the initial migration of the code with history form aqua into terra. There is still a bunch of refactors that need to happen. When we've finalized the API of what's been migrated then I think we can write a guide. I was planning to do this as part of the standard elease notes we write for terra 0.17.0 and aqua 0.9.0. We'll need this in release notes too because everything we added in terra and everything we deprecate in aqua needs to be documented in the release notes. But, if you'd like to write it as standalone documentation that is a good idea, but shouldn't be done in place of release notes either.

**Comment by t-imamichi** [comment]
I agree. It's no problem if we have the migration guide when we finalize the API and release the next version.

**Comment by mtreinish** [comment]
Just an update here, the working plan is that we will include this as part of the aqua documentation (as a separate entry on the bottom of the toc in the combined qiskit docs) then the release notes will link to it. I have a draft of the releasenotes for the aqua migration parts up here: https://github.com/Qiskit/qiskit-terra/pull/6075/files#diff-1d9683ea4d50d5e6a4534f0ced11afeb594e0a17f13468ead0051868320c0c82 (I'll add the internal reference after the aqua PR is up)
