### ISSUE TITLE
Older pickle files no longer loading

### ISSUE THREAD

**Issue by coruscating** [Qiskit/qiskit-terra#5523]
### Information

- **Qiskit Terra version**: 0.16.0
- **Python version**: 3.7.3
- **Operating system**: Catalina

### What is the current behavior?

A results object pickle file exported in 0.15.0 cannot be imported in 0.16.0+.

### Steps to reproduce the problem

Create QV ideal results in 0.15.0:

```
qubit_lists = [[0,1,3],[0,1,3,5],[0,1,3,5,7],[0,1,3,5,7,10]]
ntrials = 5
qv_circs, qv_circs_nomeas = qv.qv_circuits(qubit_lists, ntrials)
qv_circs_nomeas[0] = qiskit.compiler.transpile(qv_circs_nomeas[0], basis_gates=['u1','u2','u3','cx'])

backend = qiskit.Aer.get_backend('statevector_simulator')
ideal_results = []
for trial in range(ntrials):
    ideal_results.append(qiskit.execute(qv_circs_nomeas[trial], backend=backend).result())
pickle.dump( ideal_results, open( "test_pickle.pkl", "wb" ) )
```

When loading the pickle file in 0.16.0 and above, I get this error:

```
AttributeError: Can't get attribute 'QobjExperimentHeader' on <module 'qiskit.qobj.qasm_qobj' from 'PATH/.../qiskit/qobj/qasm_qobj.py'>
```

### What is the expected behavior?

The old pickle file should be able to be loaded, or at the very least, there should be a graceful error telling the user of the version incompatibility.

**Comment by mtreinish** [comment]
This is not something we can fix in qiskit and is a big part of why you shouldn't use pickle as a general serialization format (which it's not and the stdlib pickle docs try to make clear). Pickle is executing python code and assumes the state of the code is identical on both the serializer and the deserializer. If the environment is not the same it will fail. What is happening here is pickle deserialize is literally calling `getattr(qiskit.qobj.qasm_qobj, 'QobjExperimentHeader')` while trying to reconstruct the object and that class was moved in 0.16.0 so it raises an attribute error. Just as if you tried to do that in a python shell. We can't really change this error message since it's internal to pickle's operation and is why we can and do not assert pickle compatibility between versions since it's sensitive to any internal api change like this.

If you need a serialized result object just use json. The output from `to_dict()` is more or less directly usable with `json.dumps()` (since the object started as just a python class mapping to the iqx wire format currently) with the exception of numpy arrays and datetime objects which you can handle with a custom serializer easily enough.

I'm going to close this issue since there is nothing we can do here. Feel free to reopen if you think that I'm missing something or there is something else to discuss.
