### ISSUE TITLE
VQE: more shots on last iteration; stop iteration on-demand

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit-terra#5709]
### What is the expected behavior?
Two independent but related VQE feature requests important for experiments on quantum hardware:

1) **More shots on final cost-function evaluation**
There should be an option to increase the number of shots for the final evaluation of the cost function in VQE. For example, in this modern IBM experiment: https://arxiv.org/pdf/1805.04492.pdf, they set the number of shots to 10^4 while VQE was converging, and then increased the shots to 10^5 for the final evaluation at the converged parameters.

2) **Manually tell VQE it has converged.** 
Some of the optimizers, including SPSA which is the optimizer of choice in modern IBM experiments, do not have a convergence criterion, but instead run for a fixed number of iterations. This can lead to situations where the user separately plots the energy vs iteration so far and sees that convergence has been obtained, but still has to wait a long time (~hours) for SPSA to finish all `max_iter` number of iterations before a final energy value is returned. It would be nice if the user could tell VQE that it has already run enough iterations and should go ahead and return a final value. This could be implemented for example by catching a single KeyboardInterrupt from the user, which VQE could interpret as an indication that convergence has been reached. In the case of SPSA, the desired effect would be that the current iteration would be abandoned, and the final evaluation (without any +/- perturbation of the parameters) would be run immediately to obtain a final result, without having to wait the extra hours.

**Comment by Cryoris** [comment]
Hi @aeddins-ibm, what you're describing above should both be possible now:

1. With the runtime primitives, you can re-submit an estimation job after the VQE, still within the same session. Since you anyways have to wait until you converged to know when to turn up the number of shots there should, and you're still in an active session and avoid queuing, it seems this fits your need 🙂 
2. The `SPSA` optimizer now allows a `termination_checker` argument which can be used to stop the optimization early. I'm not sure if that could be made to capture a `KeyboardInterrupt` but you could make it check if a key has been pressed I think -- or just implement a termination criterion based e.g. on the change in the loss function.

**Comment by woodsp-ibm** [comment]
As noted above you can do the functions should be doable today. Indeed with the Estimator and an optimizer its easy enough to roll your own VQE that can have that custom behavior built into it - though its doable after the fact with a single execution of the Estimator with increased shots using the converged result params. As such I am going to close this.
