### ISSUE TITLE
Y-gate gets transposed to 2x SX verses one X

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5722]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
qc = QuantumCircuit(1)
qc.y(0)
transpile(qc,backend).draw()
```
gives:

```
global phase: -π/2
                 ┌────┐┌────┐┌───────┐
        q_0 -> 0 ┤ √X ├┤ √X ├┤ RZ(π) ├
                 └────┘└────┘└───────┘
```

which is twice as long in duration as directly using `x` since both `sx` and `x` have the same duration on the backend.

### Suggested solutions
Perhaps `x` goes before `sx` in the basis gates?

**Comment by naezzell** [comment]
I have the same inquiry (still true as of qiskit 0.23.4).  But I'd like to add that this behavior is more general than just Y. In particular, they occur for `\pi` rotations with axis in the `xy` plane which I explain below. 

In my own work, I need to define both gates like X and -X. To make sure the phases come out right across updates, I define all single qubit rotations `R_n(\alpha)` where `n = (\theta, \phi)` is just unit vector in spherical coordinates and `\alpha` is rotation angle as,
```
circ = QuantumCircuit(1)
circ.rz(-phi, 0)
circ.ry(-theta, 0)
circ.rz(alpha, 0)
circ.ry(theta, 0)
circ.rz(phi, 0)
```

Hence, `X` corresponds to `theta = \pi / 2, \phi = 0, \alpha = \pi` and `-X` to `theta = \pi / 2, \phi = np.pi, \alpha = \pi`. When I implement X and -X (called Xb in my code), I get the following
<img width="790" alt="Screen Shot 2021-01-28 at 2 00 27 PM" src="https://user-images.githubusercontent.com/29308150/106204102-41ea3980-6171-11eb-9341-69976858623a.png">
where I've used my own custom class wrapper/ functions, but the idea should be clear from the above, I hope. 

For rotations defined as above, then this "bug" happens for all `\pi` rotations with rotation axis in the `xy` plane, e.g.
<img width="817" alt="Screen Shot 2021-01-28 at 2 06 21 PM" src="https://user-images.githubusercontent.com/29308150/106204614-1ddb2800-6172-11eb-9bff-a0086bc3894a.png">
where `eta` is angle from x-axis that determines rotation axis.

On the other hand, for a completely arbitrary rotation, we generally expect an `RZ` gate to between the `sx` gates, as follows
<img width="1034" alt="Screen Shot 2021-01-28 at 2 08 56 PM" src="https://user-images.githubusercontent.com/29308150/106204838-76aac080-6172-11eb-8507-3508a24bbfb3.png">

Hopefully this helps clarify in what cases this transpiler bug occurs--it's probably not exhaustive, but more general than just `Y`.

**Comment by mtreinish** [comment]
Looking at this briefly I don't think the transpiler is currently capable of simplifying an arbitrary 1q gate to anything with an X gate. For the new IBMQ basis set of `["id", "rz", "sx", "x", "cx"]` the transpiler is using the [`Optimize1qGatesDecomposition` ](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py) pass which under the covers is just using the [`OneQubitEulerDecomposer`](https://qiskit.org/documentation/stubs/qiskit.quantum_info.OneQubitEulerDecomposer.html#qiskit.quantum_info.OneQubitEulerDecomposer) to decompose a 1 qubit unitary for a run of >1 1q gates in the circuit into a simplified form with a compatible basis. Since the `OneQubitEulerDecomposer` doesn't have any basis that use the `X` gate it never ends up simplifying any runs into a form that uses it. The order of the basis gates doesn't matter here.

For example using the Y example from the original issue, this gets translated with the basis translator to:
 ``` 
      ┌─────────┐┌────┐┌────────┐┌────┐┌──────────┐
q_0: ┤ RZ(π/2) ├┤ √X ├┤ RZ(2π) ├┤ √X ├┤ RZ(7π/2) ├
      └─────────┘└────┘└────────┘└────┘└──────────┘
```
Then this gets simplified to 
```
     ┌─────────┐┌────┐┌────┐┌──────────┐
q_0: ┤ RZ(π/2) ├┤ √X ├┤ √X ├┤ RZ(3π/2) ├
     └─────────┘└────┘└────┘└──────────┘
```

and then

```
     ┌────┐┌────┐┌───────┐
q_0: ┤ √X ├┤ √X ├┤ RZ(π) ├
     └────┘└────┘└───────┘
```

after two runs of `Optimize1qGatesDecomposition` and the pass can't simplifying it beyond that.

The simplest fix here might be to add explicit handling for the case when X is in the basis gates and there are 2 SX gates next to each other in the output decomposition as a simplification. (similar to #5554)

**Comment by nkanazawa1989** [comment]
Can we implement a pass that merges general consecutive instructions such as Rz-Rz, X-X, SX-SX, ....? @itoko 

With pulse gate (add calibration) we can easily create custom calibration. For example,
```
ZI(-1,2) @ YI(-1,1)  @ IX(1,2)  @ ZX(1,4)  @ XI(1,1)  @ ZX(-1,4)
```
This is current backend CX pulse definition. As you can see there is Y pulse on control qubit but this is decomposed into two SXs. This visibly affect the RB fidelity as CR pulse duration become shorter due to the coherence limit. Thus I should use
```
XI(1, 1) @ ZI(-1, 2) @ IX(1, 2) @ ZX(1, 4) @ XI(1, 1) @ ZX(-1, 4)
```
this instead. This is really annoying and discourage to use pulse gate though this is really great feature.

**Comment by itoko** [comment]
@nkanazawa1989 It's possible but I prefer the solution suggested by @mtreinish to fix issues reported here.

**Comment by mtreinish** [comment]
@nkanazawa1989 I think most consecutive gate cases (including Rz-Rz and X-X) should currently be covered by the existing `Optimize1qGatesDecomposition`  optimization pass. The pass works by collecting runs of 1q gates on a qubit taking the unitary of those gates and decomposing that unitary into the shortest set of gates it can (over all the compatible basis that it knows how to decompose with). For example:

```
qc = QuantumCircuit(1)
qc.x(0)
qc.x(0)
print(transpile(qc, basis_gates=["id", "rz", "sx", "x", "cx"]))
```
returns:

```
q_0: 
```

and

```
qc = QuantumCircuit(1)
qc.rz(pi/2)
qc.rz(pi)
print(transpile(qc, basis_gates=["id", "rz", "sx", "x", "cx"]))
```

returns:

```
     ┌──────────┐
q_0: ┤ RZ(3π/2) ├
     └──────────┘
```

This is not really a general issue but more of a specific case here around a limitation in the 1q euler decomposer that it isn't actually aware of the full ibmq basis and doesn't know that it can use an X gate to further simplify things.

**Comment by naezzell** [comment]
As per @mtreinish 's suggestion, I put together this hack which I put here for anyone else who comes across this issue. 

```
def replace_sx_sx_with_x(circ):
    """
    Given a [circ], replace sx-sx motif with
    a single x gate.
    """
    qasm_string = circ.qasm()
    new_qasm_string = ""
    prev_was_sx = False
    replace_sx_idxs = []
    
    # find and keep track of sx-sx motifs
    for idx, inst in enumerate(qasm_string.split('\n')):
        if 'sx' in inst:
            if prev_was_sx == True:
                replace_sx_idxs.append(idx - 1)
            else:
                prev_was_sx = True
                new_qasm_string += inst + "\n"
        else:
            new_qasm_string += inst + "\n"
            prev_was_sx == False

    # replace sx values with x if applicable
    if replace_sx_idxs != []:
        qasm_split = new_qasm_string.split('\n')
        for idx in replace_sx_idxs:
            qasm_split[idx] = "x" + qasm_split[idx][2:]
        new_qasm_string = "\n".join(qasm_split)
        
    return QuantumCircuit.from_qasm_str(new_qasm_string)
```
