### ISSUE TITLE
Measurements in opflow should return real numbers

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#5738]
### Information

- **Qiskit Aqua version**: 0.8.0.dev0+b040e2c
- **Python version**: 3.8.3
- **Operating system**: linux

### What is the current behavior?

The documentation says

https://github.com/Qiskit/qiskit-aqua/blob/b040e2c2f90f49a401551190475f4dc0f3706c7a/qiskit/aqua/operators/__init__.py#L62

### Steps to reproduce the problem

Read the docs.

### What is the expected behavior?

The documentation should say something like

> 3. An n-qubit Measurement is a functional taking an n-qubit State function to a real number.

### Suggested solutions

See the comment above.

In fact expectations of observables in operator flow do return real values represented as a python `complex` (a complex floating point number). Unless there is a good reason to do this, they should return python type `float`.

**Comment by Cryoris** [comment]
@jlapeyre is this still open? With the primitives as main workflow to evaluate expectation values, can we close this?
Otherwise we add a sentence saying that the values can be complex due to coefficients or if the left and right state are not the same (as supported by opflow by e.g. directly evaluating and not going via hardware/simulators).

**Comment by jakelishman** [comment]
Closing now as stale, especially with the deprecation of opflow.  Feel free to re-open if there's more to say.
