### ISSUE TITLE
packaging reorganization

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5896]
Plan:
 - `pip install qiskit` install what today is `qiskit-terra`
 - current `qiskit-terra` should be renamed to `qiskit-core`
 - Remove `qiskit-aqua` from the `qiskit` metapackage
 - `qiskit-aqua` should split in domain specific packages
 - `qiskit-ignis` renames to `qiskit-experiments`

**Comment by woodsp-ibm** [comment]
`qiskit-experimental-tools` reads to me as if experimental is an adjective of tools - which might be inferred, by someone coming new, that these are a bunch of work-in-progress tools that are being experimented with. Would `qiskit-experiment-tools` not look more like tools for experiments, which is what ignis provides, no?

**Comment by 1ucian0** [comment]
ups.. sorry. A typo. I corrected to match the current working title:  `qiskit-experimentalist-tools`

**Comment by kdk** [comment]
Is this complete as of the 0.19 terra/0.33 qiskit release? If not, do we know what remains here?

**Comment by jakelishman** [comment]
I guess `pip install qiskit` is still the metapackage rather than specifically being Terra only.  If we still want to change it so `pip install qiskit` _only_ installs Terra now, we'll have some weird versioning problems, since the metapackage's versioning is far ahead of Terra.

**Comment by mtreinish** [comment]
@jakelishman yeah, it's not viable to do that for the reason you've said and also the upgrade path is non-existent to do that in python packaging. This issue is just incorrect in what it's asserting. This really should be about slimming down the metapackage to not have aqua, ignis, or the ibmq provider by default. This is the wrong place to track this and also its well underway as @kdk pointed out so I'm going to close this we can always re-open it if needed.
