### ISSUE TITLE
transpile does not remove reset when that reset is inside initialize

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5974]
Take the following example:
```
from qiskit import QuantumCircuit, transpile

qc = QuantumCircuit(1)
qc.initialize([1, 0], [0])
transpiled = transpile(qc)
transpiled.draw()
```
```
     ┌─────────────────┐
q_0: ┤ initialize(1,0) ├
     └─────────────────┘
```
The reset is still there:
```
transpiled.decompose().draw()
```
```
          ┌─────────────────┐
q_0: ─|0>─┤ disentangler_dg ├
          └─────────────────┘
```

I suggest to run `Decompose(Initialize)` before `RemoveResetInZeroState()` in levels 1, 2, and 3.

**Comment by wmurphy-collabstar** [comment]
I'm interested in this issue, could I work on it?

**Comment by 1ucian0** [comment]
assigned! thanks!

**Comment by poig** [comment]
@wmurphy-collabstar @1ucian0  just fix it, because I am working on Decompose.

**Comment by 1ucian0** [comment]
You mean this issues should be marked as solved by https://github.com/Qiskit/qiskit-terra/pull/8129 ?

**Comment by poig** [comment]
@1ucian0 I make the suggested change on #8142 , but haven't merged yet.

**Comment by jakelishman** [comment]
This isn't actually a bug.  The `transpile` call given doesn't have any basis gates, so `initialize` is treated as a basis gate, which means it does not necessarily contain a reset (for example, a simulator will directly jump the state to the correct thing).  `transpile` doesn't fail to remove the `reset` because there's no `reset` to remove until the call to `decompose`.  If the `basis_gates` argument is passed, the reset will correctly not appear in the output from `transpile`.

**Comment by 1ucian0** [comment]
closing as `wontfix`. Thanks!
