### ISSUE TITLE
Gradients crash in case of a ListOp where elements have non-identical sets of parameters

### ISSUE THREAD

**Issue by stefan-woerner** [Qiskit/qiskit-terra#5992]
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: MacOS

### What is the current behavior?

Suppose a `ListOp` that contains of 2 expected values (PauliSumOps with at least 2 Pauli terms) that are based on parametrized circuits with different parameter sets. Then, evaluating the ListOp is fine, but evaluating its gradient crashes since it first realizes that one element does not contain a certain parameter and replaces the partial derivative by 0.0 (float, not operator), which doesn't work in some of the following steps where the opflow assumes to get an operator and not a number (e.g. if it tries to `reduce` it or something like that). 

### Steps to reproduce the problem

The following code reproduces the problem:

```python
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from qiskit.opflow import StateFn, CircuitStateFn, ListOp, PauliSumOp, Gradient

x, y = Parameter('x'), Parameter('y')
param_values = {x: 1, y: 3}

# observable
H = StateFn(PauliSumOp.from_list([('Z', 1.0), ('X', 1.0)]))

qc_x = QuantumCircuit(1)
qc_x.ry(x, 0)
op_x = ~H @ CircuitStateFn(qc_x)

qc_y = QuantumCircuit(1)
qc_y.ry(y, 0)
op_y = ~H @ CircuitStateFn(qc_y)

op = ListOp([op_x, op_y])

# evaluating the 2-element ListOp works
print(op.bind_parameters(param_values).eval())

# but evaluating its gradient crashes
gradient = Gradient()
grad_op = gradient.convert(op, [x, y])
grad_op.bind_parameters(param_values).eval()
```

### What is the expected behavior?

The correct behavior would not replace the partial derivative (lets say `d/dx <psi(y)|Hpsi(y)>` by 0.0 (float) but e.g. by `~Zero @ One`. 

### Suggested solutions

A possible workaround is to include the following lines into `qiskit/optlfow/gradients/gradient.py` (around line 170):

```python
[...]
# Handle the chain rule
elif isinstance(operator, ListOp):

    grad_ops = [self.get_gradient(op, param) for op in operator.oplist]

    # replace 0 by 0-operator --> although this works, it likely is not the right place for the fix
    for i, op in enumerate(grad_ops):
        if op == 0:
            grad_ops[i] = ~Zero @ One

    # Note: this check to see if the ListOp has a default combo_fn
    [...]
```

**Comment by jlapeyre** [comment]
It's not 100% clear how to fix this. But, this problem is of immediate practical concern, so it needs to be addressed. The immediate problem is that an element of a  `ListOp` is initialized as floating point number, `0.0`. But, much of opflow assumes that anything in a `ListOp` (and its subclasses) is an instance of `OperatorBase` and calls methods of `OperatorBase`. The mypy parameter annotation in `ListOp.__init__` indicates that all elements are `OperatorBase`. But, this is not enforced or validated anywhere.

* The doc string for method `OperatorBase.reduce` suggests that it should return an `OperatorBase`. But, in fact `SummedOp([]).reduce()` returns `0.0`. This is the immediate cause of this bug.
*  `ComposedOp([]).reduce()` and `TensoredOp([]).reduce()` raise an error because an attempt to call functools reduce on `[]` is made.
* Some intermediate calculations in the gradient code also involve setting opflow expressions that represent either `0.0` or a matrix or tensor with all zero entries. This expression `~Zero @ One`, which evaluates to `0.0` is used for both of these purposes.
* Before returning a `SummedOp`, the gradient code removes occurrences of `~Zero @ One`. If no terms are left, `SummedOp([]).reduce()` is returned, which is `0.0`.

Some things we can consider to clean this up. All of these should be quick to implement once it is decided what to do.

* Make subclasses of `ListOp` method `reduce` behave uniformly for empty lists. In particular, consider returning an `OperatorBase` equivalent to 0.0 rather than 0.0. Note that `SummedOp([])`, etc. doesn't have a clear meaning. Also the bevahior of `eval` is not consistent across subclasses and should be reconsidered; `eval` either returns 0 or throws an error. Also `num_qubits` needs to be made uniform.
    * `reduce` on empty `ListOp`s could all return `SummedOp([])` or `0.0` or a new class `ZeroExpr`.

* Validate `ListOp` on construction. This also involves making a serious decision on what can be in the lists.
* Somehow get rid of `~Zero @ One` in the code.
* We need to think about where allowing 0.0 or `ZeroExpr` in `ListOp` leads us. It needs to be exposed to users and then supported. Will users start to use it in expressions, and how?
