### ISSUE TITLE
Swap mapper regression from stable to master

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5997]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Following onto #5996 the master version of Qiskit is about 67% slower at swap mapping the Shor circuit from #5996:

```python

N = 5
shor = Shor()
qc = shor.construct_circuit(N)
trans_qc = transpile(qc, backend)
```
when compiling to a 27Q backend.  Example, reproducible timings:

On master: `1    0.071    0.071    9.878    9.878 stochastic_swap.py:271(_mapper)`

On stable: `1    0.065    0.065    5.948    5.948 stochastic_swap.py:271(_mapper)`

### What is the expected behavior?
Things should not get slower

**Comment by mtreinish** [comment]
Looking at the nightly benchmark runs:

https://qiskit.github.io/qiskit/#mapping_passes.PassBenchmarks.time_stochastic_swap?commits=9040bb9c&machine=qiskit-benchmarking

This was casued by: https://github.com/Qiskit/qiskit-terra/pull/5486 So I think this is a duplicate of #5965 which is what we're using to track the regressions caused by the api changes for optional registers.

**Comment by nonhermitian** [comment]
Will close as duplicate than.
