### ISSUE TITLE
Examples seem to be broken

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#6025]
### Information

- **Qiskit Terra version**: '0.17.0.dev0+33b8215'
- **Python version**:
- **Operating system**:

### What is the current behavior?

I tried running `https://github.com/Qiskit/qiskit-terra/blob/master/examples/python/ibmq/using_qiskit_terra_level_2.py`, but got a couple layers of errors.

### Steps to reproduce the problem

Run the example. The first error is because `armonk` is least busy, but also unavailable (zero qubits? not enough qubits?) `qiskit.transpiler.exceptions.TranspilerError: 'Number of qubits greater than device.'`

Then, I edited the file to use another device I have access to.

Running `LookaheadSwap` yields `TranspilerError: 'Lookahead swap runs on physical circuits only'`

If I comment that out, we get an error on a pass a few lines down on `CXDirection`: `TranspilerError: "CXDirection expects a single qreg input DAG,but input DAG had qregs: OrderedDict([('q', QuantumRegister(4, 'q')), ('ancilla', QuantumRegister(16, 'ancilla'))])."`

### What is the expected behavior?

Should execute without errors.

**Comment by mtreinish** [comment]
FWIW, we run the examples through tests, but because we don't have credentials in PR CI (and also don't want a reverse dependency on the ibmq provider) we skip the ibmq example test: https://github.com/Qiskit/qiskit-terra/blob/master/test/python/test_examples.py#L58-L80

Honestly I'm wondering if we should just delete those examples and the corresponding test. They've pretty much been superseded by the ibmq tutorials anyway and clearly nobody is running them if this went unnoticed for so long.

**Comment by ecpeterson** [comment]
Removing dead examples sounds fine to me, provided their contents is covered elsewhere. I was looking at this one because I wanted to hit a non-Aer backend, as a check that my local configuration was totally sane. I guess this is exactly the thing that's allowed to drift under the testing conditions you describe.

Clicking around the tutorials now, I don't see an analogous non-Aer example — perhaps for the same reason. Am I missing it? If there isn't one, I'd like to see a stock non-Aer example _somewhere_, whether or not it's this one / located here.

**Comment by 1ucian0** [comment]
Closing this as unplanned, since the broken example was removed in https://github.com/Qiskit/qiskit-terra/pull/8975

**Comment by 1ucian0** [comment]
Closing this as unplanned, since the broken example was removed in https://github.com/Qiskit/qiskit-terra/pull/8975
