### ISSUE TITLE
compose should not unroll (by default) when using the circuit library

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#6147]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

The idea of having a circuit library is to build up larger circuits and have simple visualizations that we can recognize when using them. I am fine having a non default option to unroll circuit when you compose it but by default the combined circuit should look like building blocks of the libraries. 

As an example see this figure 
<img width="796" alt="Screen Shot 2021-04-03 at 11 07 27 AM" src="https://user-images.githubusercontent.com/15731369/113482441-c789ae80-946c-11eb-9fb1-6261b562e021.png">

It should make output (by default)

<img width="750" alt="Screen Shot 2021-04-03 at 11 08 06 AM" src="https://user-images.githubusercontent.com/15731369/113482475-eab45e00-946c-11eb-9f72-6064e9e4143b.png">

@ajavadia I know we talked about this but just making issue so we remember.

**Comment by 1ucian0** [comment]
The problem is that `QFT` returns the decomposition, not the "box".

```
QFT(3).draw('text')
```
```
                                          ┌───┐   
q_0: ───────────────■─────────────■───────┤ H ├─X─
                    │       ┌───┐ │P(π/2) └───┘ │ 
q_1: ──────■────────┼───────┤ H ├─■─────────────┼─
     ┌───┐ │P(π/2)  │P(π/4) └───┘               │ 
q_2: ┤ H ├─■────────■───────────────────────────X─
     └───┘      
```

**Comment by enavarro51** [comment]
I think this is a fairly easy change to `compose`, if `compose` knew which `QuantumCircuit`'s are from the library. One simple idea is to just add an attribute, say `library`, to each library class that produces a `QuantumCircuit` (or to every library class). Then maybe add a `kwarg` to compose that gives the user the option to unroll or not. For example,
```
qc = QuantumCircuit(3)
qc.h(0)
qc2 = QuantumCircuit(2)
qc2.h(1)
qc2.x(0)
qc = qc.compose(QFT(num_qubits=3), range(3))
qc = qc.compose(qc2, range(2))
qc.h(0)
qc.draw()
```
![image](https://user-images.githubusercontent.com/16268251/113622848-5dab0980-9612-11eb-8ffa-fd865ae905bb.png)
The `library` attribute might also help in the drawers, since we might want to display internally created gates differently than user-generated ones in some cases.

**Comment by jaygambetta** [comment]
@1ucian0 I dont want to use the to_gate long term that needs to be removed in my opinion.

@enavarro51 im good have a kwargs to unroll if the use wants to but by default it should not. 

@1ucian0 I agree it just a box to implement it :-)

**Comment by enavarro51** [comment]
Agreed on default not to unroll. So the remaining question is, how does compose identify library circuits?
1 - Add `library` attribute on all library classes
2 - Import all library classes into `quantumcircuit.py` and see if `other` is instance of library class
3 - Create list of library `name`s and see if `other.name` or `other.base_gate.name` in list.
For me, '1' seems the cleanest and easiest to maintain. Or maybe there's another one I'm missing.

**Comment by kdk** [comment]
In my understanding, `append` is the way to do this. e.g. from @1ucian0 's example

```
circuit = QuantumCircuit(3)
circuit.initialize(Statevector.from_label('+++'))
circuit.append(QFT(3), range(3))
circuit.draw('mpl')
```

![image](https://user-images.githubusercontent.com/2241698/114251614-a72b8980-996f-11eb-9a18-adb2b930bbfe.png)




As defined now, `append` is loosely "add this object as a boxed instruction within my circuit" and `compose` is "add all the instructions from this object to my circuit".

**Comment by jaygambetta** [comment]
Append works but my view is we don’t need both.  And I would rather have compose work the way we expect. Long term I don’t see why we need append.

**Comment by Cryoris** [comment]
I agree it's a bit weird to have two methods to do almost the same. So how about removing `append` in favor of
```python
def compose(self, other, qubits=None, clbits=None, unroll=False, front=False, inplace=False):
    # if unroll is False, behave like append (with some few changes to accomodate front/inplace/optional qubits/clbits)
    # if unroll is True, behave like current compose
```
We could keep most of the code as is I think but just add a proxy do decide how to append.

**Comment by jaygambetta** [comment]
im good with this we should only have one and compose makes more sense since we also use in the operators. 

I am good having keyword but I would use decompose as it is only going one length when it unrolls anyway.

**Comment by jlapeyre** [comment]
It looks like `compose` and `append` are roughly the same, but differ (at least) in details. For example on offers an option to operate in place, the other is only in place. They also apparently share no code! My intuition is that it would be beneficial to do refactoring in conjunction with reconsidering the API. For example, for backward compatibility, one might be a light wrapper on the other.

**Comment by Cryoris** [comment]
@jaygambetta we discussed this internally again and came to the conclusion that instead of wrapping upon composition we should wrap all library circuits directly. The reason being: If we want to be able to choose the implementation of a library circuit at compile-time, the library circuits must be opaque blocks from the beginning. And if we wrap the library circuits per default, compose doesn't need to wrap on top of that.

E.g. say we have several QFT implementations, then we could think that
```python
qft = QFT(3)  # not specifying a decomposition here, we just want some QFT implementation
circuit.compose(qft, inplace=True)  # add the opaque QFT block to our circuit
transpiled = transpile(circuit, ...)  # now choose the optimal QFT implementation
```
With that we also fix the behavior described in this issue.

We can still add an option that let's compose wrap the circuits, but it probably shouldn't wrap per default to avoid unnecessary "double-wrapping".
