### ISSUE TITLE
Plotting a circuit with matplotlib interferes with global figure

### ISSUE THREAD

**Issue by peendebak** [Qiskit/qiskit-terra#6367]
### Information

- **Qiskit Terra version**: 0.18.0.dev0+98b4a1f
- **Python version**: 3.8
- **Operating system**: Windows 10

### What is the current behavior?

Plotting a circuit diagram with matplotlib resizes the figure window

### Steps to reproduce the problem

Here is a minimal example. We create a matplotlib window with a specified size and layout and we require qiskit to draw into the specified axis `ax2`. 
```
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit

Fig=plt.figure(1, figsize=(4,6))
plt.clf()
ax1=Fig.add_subplot(1,2,1)
ax2=Fig.add_subplot(1,2,2)
ax1.plot([1,2,3], [4,7,4])
print(Fig.get_size_inches())

circ = QuantumCircuit(2, name='test')
for ii in range(10):
    circ.h(1)
circ.cz(0,1)
circ.draw(ax=ax2, output='mpl')
print(Fig.get_size_inches())
```
After plotting the figure window has been resized.

### What is the expected behavior?

Plotting on a specified axis should not interface with the other axis on a figure and the figure itself.

### Suggested solutions

The problem is at this line: https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/visualization/matplotlib.py#L912
There the global figure properties are updated.

**Comment by enavarro51** [comment]
@peendebak This is what I get when making the change to use the 'ax' that's passed in.
[4. 6.]
![image](https://user-images.githubusercontent.com/16268251/117502986-2db69500-af35-11eb-8567-c11c621e496d.png)
[4. 6.]

The reason the circuit looks bad is that the fonts don't scale with the image. This is something I noticed some time ago when trying to use the 'figwidth' style parameter and actually lobbied for removing the 'figwidth' option, but using an existing 'ax' and setting 'figwidth' are essentially the same thing. In either case you're telling the 'mpl' drawer to output an image of a specific width, and using an existing 'ax' is probably a more important feature.

We're able to use a 'scale' parameter for the drawer by scaling the fontsize at the beginning of the drawing process and then drawing the image. The problem with 'figwidth' and using 'ax' is that since you don't know the width of the finally drawn image until it's already drawn, there's currently no way to scale the fonts before things are drawn. 

It would be possible to compute the overall width of the circuit before drawing it so that the scale could be computed. This would require some restructuring of the code, but it is doable.

**Comment by enavarro51** [comment]
@peendebak I did some structural changes to the mpl drawer and was able to get this. I just wanted to confirm this was the output you were looking for since the circuit image is so small. Thanks. 
![image](https://user-images.githubusercontent.com/16268251/118286078-f42ae000-b486-11eb-9275-a0ccf0285711.png)

**Comment by peendebak** [comment]
@enavarro51 That is indeed what I was looking for! The fact that the images are small is something the drawer cannot help off course. The second image already looks better btw!

Is there are PR for these improvements already?

**Comment by enavarro51** [comment]
Unfortunately not. I've completed the work, but haven't submitted it yet as I'm waiting on several other PRs to get merged before mine goes through. The change required a significant reorg of the mpl drawer, so to avoid a lot of merge conflicts, I'm waiting for some intermediate PRs to get merged.

**Comment by enavarro51** [comment]
@peendebak Just to let you know there's now a PR for this - #6675. Don't know when it will get merged, but feel free to copy the qiskit.visualization.matplotlib.py code from my branch and run it with the current main, if you want to try it out.
