### ISSUE TITLE
Two Local 'reps' doesn't raise 'TypeError' for string input

### ISSUE THREAD

**Issue by ishworii** [Qiskit/qiskit-terra#6515]
### Information

- **Qiskit Terra version**:0.17.2
- **Python version**:3.8.5
- **Operating system**:Linux Mint 20

### What is the current behavior?
When a string is supplied to reps parameter of TwoLocal , it tries raising ValueError which raises another error

### Steps to reproduce the problem
Working Example
```
import qiskit
two = qiskit.circuit.library.TwoLocal(3, 'ry', 'cx', 'full', reps='1', insert_barriers=True)
```

### What is the expected behavior?
If possible the string value should be converted to int and if not possible TypeError should be raised.

### Suggested solutions
Try converting string to int, if error occurs raise TypeError

**Comment by ishworii** [comment]
Is it possible for me to work on this myself?

**Comment by woodsp-ibm** [comment]
> Is it possible for me to work on this myself?

Of course, that would be great if you could do a PR that fixes this - also please include a unit test that asserts the error that is thrown, when you pass in such a value, is as expected. That way we can make sure it continues to work as expected since evidently this was missed in the unit testing before. You will find a set of tests already for TwoLocal here https://github.com/Qiskit/qiskit-terra/blob/e122c9c0cef78d1ba4ac57442cd03fb0363ba93c/test/python/circuit/library/test_nlocal.py#L402 and you can simply add another there.

**Comment by ishworii** [comment]
Sorry , I am little confused. I have to fix that issue and write a unit test ? Can you explain? @woodsp-ibm

**Comment by ishworii** [comment]
I have implemented the change and written the unit test , how can I run tests locally? @ @woodsp-ibm

**Comment by ishworii** [comment]
@woodsp-ibm I have linked a PR, can you kindly review it?
