### ISSUE TITLE
Factor quantum_info-dependent code out of `opflow.AbelianGrouper`

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-terra#6624]
The code in [abelian_grouper.py](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/opflow/converters/abelian_grouper.py) does not depend in an essential way on any part of opflow. It could be factored out and moved to quantum_info, or to some organized code whose only qiskit dependency is quantum_info.  The opflow class could then call this factored-out code.

**Comment by woodsp-ibm** [comment]
Let me link this since it was about the grouping code Qiskit/retworkx#347 in that the groups being returned is not deterministic and under Aer, which uses the seed with RNG once per job, a change in ordering of groups, and hence the circuits that were executed to measure their expectations, led to different unit test outcomes.

**Comment by mtreinish** [comment]
While we working on the retworkx issue couldn't you just do `sorted()` on the output dict? The issue is the insertion order is unordered (because the underlying result object is a HashMap that doesn't define an order) so iteration order is different but the output should be deterministic, it's just a different insertion order.

**Comment by jlapeyre** [comment]
@irajput will be working on this.

**Comment by ikkoham** [comment]
Thanks. Nice proposal. I think it is better after the internal data of `SparsePauliOp` is replaced by `PauliList`.

**Comment by t-imamichi** [comment]
FYI This is the issue Matthew mentioned https://github.com/Qiskit/retworkx/issues/347

**Comment by jlapeyre** [comment]
> I think it is better after the internal data of SparsePauliOp is replaced by PauliList

Yes. The first step would be to implement grouping for `PauliList` in quantum_info. This is independent of opflow.

**Comment by jlapeyre** [comment]
Since OpFlow is deprecated, reorganizing grouping of Paulis is better addressed elsewhere.

Note however that a part of this work that will continue to be useful was done in #6690
