### ISSUE TITLE
Cannot target certain sub-graphs on a faulty backend

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6647]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Building on #6646, if I use a 7-qubit mock Casablanca system with Q3 disabled so that it is now two 3Q cmaps then I cannot target the first sub-graph [0,1,2], only [4,5,6] works:

```python
qc = QuantumCircuit(3)
qc.h(0)
qc.cx(0,1)
qc.cx(1,2)
qc.measure_all()
backend = FakeCasaQ3()
trans_qc = transpile(qc, backend, initial_layout=[0,1,2])

```
gives

TranspilerError: 'The initial_layout parameter refers to faulty or disconnected qubits'

### What is the expected behavior?

It looks like the route selects the largest and last sub-graph to use and raises for others.  This is not intuative nor makes any sense as the qubits in the other sub-graph are operational.

**Comment by mtreinish** [comment]
I think the underlying issue is that the some of the transpiler passes were checking for a fully connected coupling map and would error if it wasn't. That restriction should be finally relaxed with #9840. If that wasn't the issue (I don't know what FakeCasaQ3 is so I can't test) then I expect it's related to the faulty qubits code in transpile() which I've proposed removing in #9900.
