### ISSUE TITLE
3-qubit Grover's Algorithm Results

### ISSUE THREAD

**Issue by Mystery8226** [Qiskit/qiskit-terra#665]
### Informations

- **Qiskit (Python SDK) version**: 0.5.7
- **Python version**: 3.6.6
- **Operating system**: Windows 10 Enterprise

### What is the current behavior?
I ran a 3-qubit Grover's Algorithm searching for '111' on the ibmqx5 backend and did not get even remotely similar results to the simulated runs.

My code:
![image](https://user-images.githubusercontent.com/10801224/42950333-c47f31ba-8b41-11e8-8b0a-ee053be39040.png)
Simulated Run:
![image](https://user-images.githubusercontent.com/10801224/42950374-da0b9ed8-8b41-11e8-9397-66ab872516d1.png)
Actual Run:
![image](https://user-images.githubusercontent.com/10801224/42950392-e3a77048-8b41-11e8-870f-13e4346c2818.png)

### Steps to reproduce the problem
I tried 2-qubit Grover's Algorithm which worked - 0.72 probability of '11'.

### What is the expected behavior?
A decently high probability of '111' whereas, in actuality, '111' had the lowest number of counts. Running it on the simulator, I got 0.9484 probability of '111' and on ibmqx5, I got 0.1035.

### Suggested solutions
None.

**Comment by chriseclectic** [comment]
The grovers circuit is not going to run well on current hardware as it has 4 Toffoli (ccx) gates in it. Since this is not a native gate for the hardware, each of these gates is implemented on the device as 6 CNOT (cx) gates and single qubit rotations. You can see the equivalent circuits here:

```python
q = QuantumRegister(3, name='q')
qc = QuantumCircuit(q)
qc.ccx(q[0], q[1], q[2])
circuit_drawer(qc)
``` 

is implemented as

```python
q = QuantumRegister(3, name='q')
qc = QuantumCircuit(q)
qc.cx(q[1], q[2])
qc.tdg(q[2])
qc.cx(q[0], q[2])
qc.t(q[2])
qc.cx(q[1], q[2])
qc.tdg(q[2])
qc.cx(q[0], q[2])
qc.t(q[2])
qc.h(q[2])
qc.t(q[1])
qc.cx(q[0], q[1])
qc.t(q[1])
qc.tdg(q[1])
qc.cx(q[0], q[1])
circuit_drawer(qc)
```

To see why this would cause such a high error rate we can look at the gate times and T1 times of the device. The time for a CNOT gate in the Rueschlikon (ibmqx5) device is around 400ns depending on qubit pair so the grover circuit could take close to 10 microseconds to run all the pulses. T1 times for qubits in that device range  30-50 microseconds so you are already at around 25% error rate for that just from T1-relaxation alone. T1 isn't the only error present either, there are measurement errors (around 5-10% per measurement), other gate errors (around 3-5% per CNOT), and cross-talk errors for example. If you add all those together you can see why the results start to look like random noise.

**Comment by Mystery8226** [comment]
Are there any workarounds to this? I want to be able to run the 3-qubit Grover's Algorithm without such high errors.

**Comment by chriseclectic** [comment]
You could see if you can find an equivalent circuit with fewer 2-qubit gates to implement the algorithm, and also try running it on a the Tenerife (ibmqx4) device since it has lower error rates
