### ISSUE TITLE
Avoid production code depending on tests

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#669]
### What is the expected enhancement?
Find a better way of resolving this:
https://github.com/Qiskit/qiskit-terra/pull/547/files#diff-c3448a8c2134a492e0f08f2131d5552dR248

**Comment by diego-plan9** [comment]
Can you edit the issue and elaborate a bit? I _believe_ you actually want to refer mostly to the [tearDown()](https://github.com/Qiskit/qiskit-terra/blob/0.5.7/test/python/common.py#L61) method, which was introduced due to the implications of `import qiskit` bringing the wrappers' `_DEFAULT_PROVIDER` as it is a module variable, and ends up being initialized only once per test suite.

**Comment by delapuente** [comment]
You're right but I don't know for sure. That's part of the issue, I think. When I gain more insight, I will elaborate on the description.

**Comment by delapuente** [comment]
I did not realize this is not product-code but part of the testing infrastructure. My bad, sorry.
