### ISSUE TITLE
qpy not recognizing complex number as a parameter for Initialize 

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-terra#6710]
### Information

- **Qiskit Terra version**: 0.18.0
- **Python version**:
- **Operating system**:

### What is the current behavior?
When trying to serialize a QuantumCircuit using qpy, I got

```
~/Documents/Q/Github/qiskit-terra/qiskit/circuit/qpy_serialization.py in _write_instruction(file_obj, instruction_tuple, custom_instructions, index_map)
    722             size = len(data)
    723         else:
--> 724             raise TypeError(
    725                 f"Invalid parameter type {instruction_tuple[0]} for gate {type(param)},"
    726             )

TypeError: Invalid parameter type <qiskit.extensions.quantum_initializer.initializer.Initialize object at 0x103fd6dc0> for gate <class 'complex'>,
```

### Steps to reproduce the problem
The circuit I used:

```
import io
import numpy as np
from qiskit.circuit import QuantumCircuit, qpy_serialization
from qiskit.circuit.library import QFT
from qiskit.quantum_info import Statevector

k = 5
state = (1/np.sqrt(8))*np.array([np.exp(-1j*2*np.pi*k*(0)/8),np.exp(-1j*2*np.pi*k*(1)/8),
                                 np.exp(-1j*2*np.pi*k*(2)/8),
 np.exp(-1j*2*np.pi*k*3/8),np.exp(-1j*2*np.pi*k*4/8),np.exp(-1j*2*np.pi*k*5/8),
 np.exp(-1j*2*np.pi*k*6/8), np.exp(-1j*2*np.pi*k*7/8)])

qubits = 3 

circuit = QuantumCircuit(qubits, qubits)
circuit.initialize(state)
circuit.append(QFT(qubits),range(qubits))
circuit.measure(range(qubits),range(qubits))
buffer = io.BytesIO()
qpy_serialization.dump(circuit, buffer)
```

**Comment by mtreinish** [comment]
There are actually 2 bugs here. The first is that initialize takes it's statevector as a single parameter on init but stores it as a list internally. This is why we get the conversion error on `complex` because every other instruction that takes complex does it as a numpy array as a single parameter. The other half though is with `qft` (and I think all blueprint circuits from the circuit library) passing the stored parameters to the constructor doesn't build an equivalent circuit object that can be appended to the reconstructed circuit in the deserializer. The only way I could come up with for handling this.  I'll push a fix for this in a few minutes (it might have to wait for 0.18.1 though).

One thing you can do while waiting for the fix to merge is I think if you decompose() both initialize and qft prior to saving the qpy circuit it should work fine. Granted it's not exactly the same but it will at least work around the hard failure (I think).
