### ISSUE TITLE
Drawing error in circuits with isolated qubits

### ISSUE THREAD

**Issue by TharrmashasthaPV** [Qiskit/qiskit-terra#6732]
### Information

- **Qiskit Terra version**: 0.18
- **Python version**: 3.7

### What is the current behavior?

When a `QuantumCircuit` is initialized as `QuantumCircuit([Qubit(), Qubit()])`, the `draw()` method has some errors

- [ ] `qc.draw('text')` draws the qubit labels as `_0`, `_1`, ... without a name.
- [ ] Latex and MPL drawers fail. (from #6574 )

### Steps to reproduce the problem

```python
from qiskit import *
from qiskit.circuit import Qubit

qc = QuantumCircuit([Qubit(), Qubit(), Qubit()])
qc.draw('text')
```
returns
```
    
_0: 
    
_1: 
    
_2: 
    
```

### What is the expected behavior?

It would be better if the qubit labelling is done similar to that in the registerless circuits.

**Comment by kdk** [comment]
Using `_0:` for the text drawer was an attempt to mirror the existing convention of `{reg_name}_{reg_index}` with `_{circ_index}`, but I agree it's not clear that this is drawing a registerless bit and not just a bug. Suggestions welcome! (Maybe `__{circ_index}`?)

**Comment by TharrmashasthaPV** [comment]
@kdk `__{circ_index}` does look like a good idea. But then I think we might also need a way to distinguish between registerless qubits and registerless clbits. For instance,
```python
from qiskit.circuit import *
qc = QuantumCircuit([Qubit(), Qubit()], [Clbit(), Clbit()])
qc.draw()
```
draws
```
_0:

_1:

_0:

_1:
```
which I feel might be confusing.

**Comment by enavarro51** [comment]
@kdk @TharrmashasthaPV The `_` probably doesn't work as well in mpl and latex drawers, since the numbers there are subscripts. I think it would be best to have a solution common to the 3 drawers. I kind of like the raw numbers and maybe a `*` for classical. Like,
```
 0:
 1:
 2:
*0:
*1:
```
Any other non-alphanumeric character could be used. If we can get a consensus on this, I can make the change for all 3 drawers.

**Comment by kdk** [comment]
@TharrmashasthaPV @enavarro51 I don't think we need to distinguish between classical and quantum bits in the labels, since they are distinguished by their line type (`-` vs `=`) for all three drawers (except empty circuits, but that seems okay to me.)

I do like the suggestion of using raw numbers better than using `_N` or `__N`, so let's try that way.

**Comment by enavarro51** [comment]
Thanks, Kevin. I started looking at this and realized the 3 circuit drawers approach getting the bit names and numbers somewhat differently even though the displayed output is the same. This means for something like this, fixing the problem 3 ways. So I'd like to take a stab at putting the acquisition of bit names and numbers for display into a function in utils.py, that can be called by the 3 drawers, which will fix this and hopefully make maintenance easier in the future.
