### ISSUE TITLE
Incomplete documentation for VQE

### ISSUE THREAD

**Issue by eendebakpt** [Qiskit/qiskit-terra#6777]
### Information

- **Qiskit Terra version**: 0.18
- **Python version**: 3.8
- **Operating system**: Windows 10

### What is the current behavior?

The documentation for `VQE` (`qiskit.algorithms.VQE`) states that for the ansatz a parameterized quantumcircuit can be used. But when passed such a circuit, the class gives an error.

### Steps to reproduce the problem

A minimal example:
```
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit_nature.drivers.second_quantization import PySCFDriver
from qiskit_nature.problems.second_quantization import ElectronicStructureProblem
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit.algorithms.optimizers import COBYLA
from qiskit.algorithms import VQE
from qiskit_nature.mappers.second_quantization import ParityMapper
from qiskit_nature.drivers import UnitsType, Molecule
from qiskit.circuit.library import TwoLocal
from qiskit.aqua.algorithms import NumPyMinimumEigensolver, VQE

molecule = Molecule(geometry=[['H', [0., 0., 0.]],
                              ['H', [0., 0., 0.735]]],
                     charge=0, multiplicity=1)
driver = PySCFDriver(molecule = molecule, unit=UnitsType.ANGSTROM, basis='sto3g')

es_problem = ElectronicStructureProblem(driver)
second_q_op = es_problem.second_q_ops()
qubit_converter = QubitConverter(mapper = ParityMapper(), two_qubit_reduction=True)
qubit_op = qubit_converter.convert(second_q_op[0], num_particles=es_problem.num_particles)

optimizer = COBYLA(maxiter=10000)

theta = Parameter('theta')
var_form = QuantumCircuit(2)
var_form.rx(theta, 1)

# fails, no set_max_evals_grouped
algo = VQE(qubit_op, var_form, optimizer)
```` 

### What is the expected behavior?

The construction of the `VQE` should be possible with a user defined ansatz.

### Suggested solutions

The documentation for `VQE` should be updated with information on what type of object can be used as the ansatz. Also an example notebook would be nice.

**Comment by woodsp-ibm** [comment]
VQE in the past to have operator on the constructor but that is no longer the case so you are constructing it incorrectly see https://qiskit.org/documentation/stubs/qiskit.algorithms.VQE.html

The ansatz can indeed be a parameterized circuit. However the usual circuits supplied are Blueprint circuits, templates of how to build them if you will, that do not yet have the num_qubits set. Often, while you can select a type of ansatz you may not know the number of qubits in which case VQE will set it later. In your example since you build out the operator and act with it directly, you can build an ansatz to match it number of qubits - which you have hard coded.

There are example notebooks on how to call/use VQE - see here https://qiskit.org/documentation/tutorials.html#algorithms where several show how to setup/use VQE in various ways including the very introductory one.
