### ISSUE TITLE
Passing seed to compile does not fix output circuit

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#681]
### Informations

- **Qiskit (Python SDK) version**: 0.5.4
- **Python version**: 3.6
- **Operating system**: OSX

### What is the current behavior?
Passing a seed to the compiler should result in the same circuit being generated.  Currently this is not the case.  This is what happens in `0.5.4`.  I am assuming it happens in `0.6` as well, however #680 blocks me from verifying that.

### Steps to reproduce the problem
```python

import qiskit
from qiskit.dagcircuit._dagcircuit import DAGCircuit

q = qiskit.QuantumRegister(16, name='q')
c = qiskit.ClassicalRegister(1, name='c')
qc = qiskit.QuantumCircuit(q, c)
#-----
h_list1 = [k for k in range(16)]
h_list1.pop(4)
for kk in h_list1:
    qc.h(q[kk])
qc.cx(q[3],q[4])
qc.cx(q[5],q[4])
qc.cx(q[13],q[4])
qc.cx(q[2],q[3])
qc.h(q[3])
qc.h(q[14])
qc.cx(q[3],q[14])
qc.h(q[3])
qc.h(q[14])
qc.cx(q[6],q[5])
qc.cx(q[12],q[5])
qc.cx(q[1],q[2])
qc.cx(q[15],q[2])
qc.h(q[6])
qc.h(q[7])
qc.cx(q[6],q[7])
qc.h(q[6])
qc.h(q[7])
qc.cx(q[6],q[7])
qc.h(q[6])
qc.h(q[11])
qc.cx(q[6],q[11])
qc.h(q[6])
qc.h(q[11])
qc.h(q[0])
qc.h(q[1])
qc.cx(q[1],q[0])
qc.h(q[0])
qc.h(q[1])
qc.cx(q[8],q[7])
qc.h(q[7])
qc.h(q[10])
qc.cx(q[7],q[10])
qc.h(q[7])
qc.h(q[10])
qc.cx(q[9],q[8])
for kk in range(16):
    qc.h(q[kk])
    
qc.measure(q[0],c[0])
#-----

seed = 123
for _ in range(10):
    out = qiskit.compile(qc, 'ibmqx5', seed=seed)
    compiled_qasm = out['circuits'][0]['compiled_circuit_qasm']
    compiled_qc = qiskit.load_qasm_string(compiled_qasm)
    CD = DAGCircuit.fromQuantumCircuit(compiled_qc)
    print('Number of gates:', CD.size())
    print('Circuit depth:', CD.depth())
    print()
```

### What is the expected behavior?
The output circuit should be the same if the seed is fixed.

**Comment by diego-plan9** [comment]
Could it just be a misconception about what the `seed` parameter for the `compile()` method represents? In your example:
```
qiskit.compile(qc, 'ibmqx5', seed=seed)
```

this `seed`, per the docstring (and the code), is actually
```
seed (int): random seed for simulators
```

And if memory serves it has always been the case since introduced (~0.5?) - could you trace back the point in time where we had a configurable seed for _the compilation_? The closest seems to be #482, but it seems those changes did not really affect the callers of the  `compile_circuit()` method, which might have inadvertently rendered the generation non-deterministic. I think there is value indeed in making it deterministic again one way or another, although reusing the current `compile(seed)` parameter might be slightly problematic depending on how the discussion about the `compile()` arguments as a whole evolves.

**Comment by nonhermitian** [comment]
It turns out that it was an issue in `0.5.4` where the `seed` was not passed to `compile_circuit` by `compile`.  Since `0.6` moves to the transpiler, this bug was removed in the process.
