### ISSUE TITLE
Cannot compose circuits with different numbers of measurements

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#6816]
### Information

- **Qiskit Terra version**: 0.17.4
- **Python version**:
- **Operating system**:

### What is the current behavior?
Compose fails when combining circuits with no measurements together with those that do, e.g.

```python
ansatz = TwoLocal(2, rotation_blocks='ry',
                  entanglement_blocks='cx')  

qc = QuantumCircuit(2)
qc.measure_all()

ansatz.compose(qc)
```

gives:

CircuitError: "Trying to compose with another QuantumCircuit which has more 'in' edges."

while `+` works, but is deprecated in favor of `compose`.

**Comment by nonhermitian** [comment]
Ok, it makes sense although a bit confusing.  Namely, I cannot add a measurement circuit onto an ansatz, but rather I must append the needed measurement rotation gates to the ansatz itself before adding the measurements to it.  It would be nice if this could work if `self` has no cregs given that there is no ambiguity in that case and it is a common situation to be in.

**Comment by quantumjim** [comment]
I agree with Paul. Adding a measurement circuit onto the end of a non-measurement circuit is something I do quite often.

For my own purposes, I just construct the non-measurement circuit with a classical register so that it works. But when writing educational materials, it wouldn't be great to say "here we put in a classical register just so Qiskit doesn't complain".
