### ISSUE TITLE
Warn users if compiled circuit is longer than noise timescales of device

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#683]
### What is the expected enhancement?
We have had many instances of people saying that the output of their circuit, when run on the devices, does not agree with what they think it should be.  Usually, this is because the depth of their circuit is well beyond the noise timescales of the device (usually as a result of decomposing many Toffoli gates or many swap gates inserted) and the output consists of pure noise.

It is possible to get a rough idea as to when this limitation occurs, and warn the user that the output is likely noise limited.  For example, one could define a rough threshold for such behave as `fastest_gate_time * depth > min(T1, T2)`, where `T1` and `T2` are averages computed from `backend.parameters`.

**Comment by nelimee** [comment]
The exact time could be easily computed if #498 is solved.
I am not sure about what represents the `gateTime` in the backend `parameters`, but informations on pulses may be required also (?).

**Comment by 1ucian0** [comment]
The backend needs to validate the depth as part of `run(self, qobj)`.

**Comment by ajavadia** [comment]
There is some disagreement on whether this should be done in qiskit, or in the backend.

Advantage of doing it in Qiskit:
- It's done in the open, and only in one place. All `IBMQBackend.run()` calls will go through it.

Disadvantage:
- It may slow things down, because each `run()` will be blocked on a call to `backend.properties()`.
- Not all validations can be done in the backend, because not every relevant information is returned via `backend.properties()`. For example RAM size of the backend electronics. So some visualizations definitely belong to the backend.

**Comment by 1ucian0** [comment]
An option is to have an analysis pass that makes the validation. Does it make sense?

**Comment by ajavadia** [comment]
No because the transpiler does not know about a backend, only about the options it is transpiling to (like basis_gates and coupling_map).

Anyway this is the same as #1057
