### ISSUE TITLE
Implement storing (intermediate) results in a file. (Quantum Time Evolution)

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-terra#6935]

**Comment by ewinston** [comment]
What is the approach for storing you are considering?

**Comment by woodsp-ibm** [comment]
As algorithms are being moved I am simply going to close this. While I could see some form of callback to provide intermediate results that a user could do with what they will, including writing them to a file, this seems fairly specific/limited. Also given its been almost 2 years since this was raised if its something that's still needed/wanted another issue can be done.
