### ISSUE TITLE
Sympy and ProjectQ simulators re-integration

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-terra#699]
Continuing from the now closed #425, this is an issue to keep track of the status of the Sympy and ProjectQ simulators - even if work is most likely needed to be implemented in their repositories, this is a meta issue for keeping track of the effort:

Remaining items:
* [x] Sympy: update for supporting Qobj
~Sympy: create the pip package~
* [x] ProjectQ: update for supporting Qobj
~ProjectQ: create the pip package~
~terra: add them as dependencies (to be decided)~

@yaelbh feel free to update and comment! Otherwise, I'll chase the repository changes myself :)

https://github.com/QISKit/qiskit-addon-sympy
https://github.com/Qiskit/qiskit-addon-projectq

**Comment by ajavadia** [comment]
@yaelbh do you think this is doable within a week or two to make it for the 0.6 release?

**Comment by yaelbh** [comment]
@ajavadia Yes. The main work is to finish and merge @diego-plan9's pull requests about 0.6 (https://github.com/Qiskit/qiskit-addon-sympy/pull/28 and https://github.com/Qiskit/qiskit-addon-projectq/pull/11). The merge by the way will probably be able to be carried out only after 0.6 is launched, because addons Travis will fail until then.

I'd like not to take a central role in this effort because I'm leaving on vacation next Wednesday until the end of August.

**Comment by yehuda-naveh** [comment]
@ajavadia  @jaygambetta  are we going to release/announce JKU addon as part of 0.6? from code/wrappers/pip/benchmarking point of view I think we are all done (not including Windows which JKU don't support). If we are going to release, i'd like to first ask/inform our JKU partners so no surprises

**Comment by diego-plan9** [comment]
Closing this issue, as the original plan has been changed.
