### ISSUE TITLE
building circuits with many Parameters per gate scales superlinearly

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#7027]
Creating a circuit with many Parameter objects per gate scales worse than instead creating many gates with fixed parameters per gate. For this test the following function was profiled,

```python
def build_parameterized_circuit(width, depth, param_per_gate):
    qr = QuantumRegister(width)
    qc = QuantumCircuit(qr)
    counter = itertools.count()
    
    for i in range(depth):
        for j in range(width):
            expr = Parameter(f'p{next(counter)}')
            for k in range(1, param_per_gate):
                expr += Parameter(f'p{next(counter)}')
            qc.rx(expr, j)
    return qc
```
This function was run with two of the arguments fixed at 4 and the third varied from the list [8, 32, 128, 512, 2048, 8192]. In all cases the total number of parameters in the circuit remains the same but when the argument scaled is `param_per_gate` the scaling is worse.

![image](https://user-images.githubusercontent.com/25756217/133595356-c3ba48e8-63a5-4509-ae30-d110685a918c.png)
![image](https://user-images.githubusercontent.com/25756217/133595406-38d93d1f-3f12-4728-807c-9997274c9494.png)
![image](https://user-images.githubusercontent.com/25756217/133595457-ef407fa9-b705-450e-9e77-a7e995b8ce05.png)

Here is the function call dependency where one can see most of the time is taken in `parameterexpression.py`,
__add__ ---> _apply_operation ---> _raise_if_parameter_names_conflict ---> dictcomp ---> name

![image](https://user-images.githubusercontent.com/25756217/133596225-fd4fbc5c-9c20-4f4b-8917-1a81ad1a1e46.png)
In the diagram the format is,
+------------------------------+
|        function name         |
| total time % ( self time % ) |
|         total calls          |
+------------------------------+
where:
total time % is the percentage of the running time spent in this function and all its children;
self time % is the percentage of the running time spent in this function alone;
total calls is the total number of times this function was called (including recursive calls).

### What is the expected enhancement?
Improve performance of adding many parameters to a gate.

**Comment by mtreinish** [comment]
Which OS are you testing on? If it's spending most of the time in `__add__` my first thought was this could be all time in symengine or sympy (sympy would scale terribly as the number of variables in the expression grows). If you were on windows it would use sympy instead of symengine by default.

But I don't think that's what's going on. After looking at the profile call graph and the code, the issue is in: https://github.com/Qiskit/qiskit-terra/blob/4030839248237c223ce857c861f1762716798157/qiskit/circuit/parameterexpression.py#L205-L222
is iterating over the parameters in the expression multiple times which gets worse as the number of parameters in the expression grows. I feel like we need to leverage the `self._names` cache a bit more there so we're not traversing over all the params on every operation and just doing set lookups. Especially since we know the names of all the parameters when we create the output object we can prepopulate that and make the conflict detection scale better

**Comment by ewinston** [comment]
@mtreinish I was running on linux with qiskit version 0.19.0.dev0+7ea4d6e
