### ISSUE TITLE
QuantumVolume circuits are not directly exported to QASM2

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#7051]
### Information

- **Qiskit Terra version**: main
- **Python version**: 3.8
- **Operating system**: MacOS

### What is the current behavior?

```
from qiskit.circuit.library.quantum_volume import QuantumVolume
circuit = QuantumVolume(5, 6, seed=10)
circuit.qasm()
```
```
TypeError: can only concatenate str (not "NoneType") to str
```

Notice that `circuit.decompose().qasm()` works and `isinstance(circuit, QuantumCircuit)` is `True`.

### What is the expected behavior?

There should note be exception. `QuantumVolume` should be dump as any custom gate.

### Suggested solutions

`_insert_composite_gate_definition_qasm` call in `~/repos/qiskit-terra/qiskit/circuit/quantumcircuit.py` seems to return `None` instead of the definition. But not sure why. My a class inheritance issue?

**Comment by jakelishman** [comment]
Ultimately, this is because `UnitaryGate` defines `self._qasm_definition = None`, and there's a check in the QASM-ifier that simply uses `instruction._qasm_definition` if the attribute is defined.  Since `QuantumCircuit.qasm` is accessing a private attribute, it's not really fair to say that `UnitaryGate` is violating the API, so it's probably best just to fix the check for now, and overhaul the QASM definition bits when we handle QASM 3.

**Comment by jakelishman** [comment]
Also, this then causes the duplicate declaration bug of #7029.

**Comment by jakelishman** [comment]
This _should_ work, so there should be no error thrown at all.  I'll look into fixing the check now - my initial quick-and-dirty fix yesterday uncovered some more annoying bugs, then I had to put it aside to do other things.
