### ISSUE TITLE
unexpected behaviour of pad/MemorySlot has same prefix as MeasureChannel

### ISSUE THREAD

**Issue by stuckmar** [Qiskit/qiskit-terra#7078]
### Information

- **Qiskit Terra version**:
- 18.2
- **Python version**:
- 3.8.11
- **Operating system**:
- Windows 10 Home 20H2

### What is the current behavior?
Starting with a Schedule containing an Acquire, with the Acquire using a MemorySlot, and any Delay or Pulse, which is longer than that of the Acquire. Now using the pad function on this Schedule will return a Schedule, which contains Delays on both the AcquireChannel and MemorySlot. When the padded schedule is now assembled and converted, using the QobjToInstructionConverter and again a new schedule is created from the converted instructions, the new Schedule does not contain a Delay on the AcquireChannel, nor on the MemorySlot, but a Delay on the MeasureChannel with the same index as the MemorySlot used.

### Steps to reproduce the problem
    from qiskit.pulse import Schedule, Play, Acquire, MemorySlot, AcquireChannel, DriveChannel
    from qiskit.pulse.library.parametric_pulses import Constant
    from qiskit.pulse.transforms import pad
    from qiskit.qobj.converters.pulse_instruction import QobjToInstructionConverter
    from qiskit import assemble
    
    sched=Schedule()
    sched+=Play(Constant(4, 0.1), DriveChannel(0))
    sched+=Acquire(3, AcquireChannel(0), MemorySlot(0))
    sched=pad(sched, inplace=False)
    
    qobj=assemble(sched, qubit_lo_freq=[4.5e9], meas_lo_freq=[5e9], parametric_pulses=['constant'])
    
    converter = QobjToInstructionConverter([])
    sched2=Schedule(*[converter(inst) for inst in qobj.experiments[0].instructions])
    
Now sched and sched2 contain different instructions:

    sched.instructions
((0, Acquire(3, AcquireChannel(0), MemorySlot(0))),
 (0, Play(Constant(duration=4, amp=(0.1+0j)), DriveChannel(0))),
 **(3, Delay(1, AcquireChannel(0))),
 (3, Delay(1, MemorySlot(0))))**
    
    sched2.instructions
((0, Acquire(3, AcquireChannel(0), MemorySlot(0))),
 (0,
  Play(Constant(duration=4, amp=(0.1+0j), name='constant_e3a2'), DriveChannel(0), name='constant_e3a2')),
 **(3, Delay(1, MeasureChannel(0))))**

### What is the expected behavior?
Assembling, converting, and creating a Schedule should return the same Schedule, which was assembled.

### Suggested solutions
First, I am not sure if it is expected from the pad function to create Delays on AcquireChannels and MemorySlots. Since both of them are not PulseChannels and the assembled Qobj does not contain the Delay on the AcquireChannel.

Second, the prefix of the MemorySlot is 'm', which is the same as for MeasureChannel. Therefore, the conversion of these channels happen. I suggest a different prefix for MemorySlot, for example 's'. Then in qiskit\qobj\converters\pulse_instruction.py the get_channel  method of QobjToInstructionConverter needs to be expanded to include MemorySlots, if Delays make sense on MemorySlots. Alternatively, a Delay on a MemorySlot could be skipped entirely by the assembler, similiar how it is done with Delays on AcquireChannels.

**Comment by javabster** [comment]
hi @stuckmar thanks for raising this issue, it is currently unclear if `AcquireChannel`s should allow `Delay` instructions and there are pros and cons to allowing it. If you would like to submit a PR with your suggested solution and some more justification for your solution choice please go ahead 😄 Otherwise the core team will look into it when they have capacity

**Comment by Osmanilge** [comment]
Hello I want to assigned for this issue. I am new in qiskit but I am interested in Qiskit so may you inform me about issue? I hope this issue is suitable for me.

**Comment by 1ucian0** [comment]
Hi @Osmanilge I think the best way to assess If the issue is suitable for you, have a look to the *suggested solution*. If it sounds like greek, check a different one less obscure. Otherwise, let me know and I can assign it to you!

**Comment by HuangJunye** [comment]
Hey @Osmanilge, are you still working on this issue? Let us know if you need any help :smiley: If you’re not working on this anymore let us know and we will un-assign you so others can pick it up.

**Comment by Osmanilge** [comment]
> this anymor

I am really sorry. I could not realize I am assigned for this issue. I will look this issue if you want me to still assigned otherwise if it needs to finished quickly , you can un-assign me.

**Comment by jakelishman** [comment]
Don't worry about it - it's not urgent, and you were never formally assigned.  If something becomes urgent for us, we can solve things in-house as well.

If you'd like to work on the issue and have time to do so, let us know, otherwise no worries.

**Comment by pollyshaw** [comment]
Please could I be assigned to this? I have put in a PR.

**Comment by HuangJunye** [comment]
@pollyshaw Sure, I have assigned you. Thanks for making the contribution!

**Comment by wshanks** [comment]
@taalexander @nkanazawa1989 Isn't the problem really that here:

```
>>> Acquire(3, AcquireChannel(0), MemorySlot(0)).channels
(AcquireChannel(0), MemorySlot(0))
```

`MemorySlot(0)` is being reported as a channel even though it is not one? Do you think anything is using the fact that the `MemorySlot` is getting reported in the acquire channels or can `Acquire.channels` be changed to only report the acquire channel?

**Comment by nkanazawa1989** [comment]
Oh, you're right! This should appear in Qiskit programs and thus memory slot and register slot are actually scheduled. Probably we need to update this method to return only acquire channel? Since these slots are always sync with the acquire channel and thus even not visualized. I don't think removing them breaks code execution.
https://github.com/Qiskit/qiskit-terra/blob/8061cfe04e33cc2827120b3aa1e2ddabcab38c6f/qiskit/pulse/instructions/acquire.py#L90-L93

Anyways, in Qobj converter, each instruction kind is separately handled and the memory slots are generated in a part of acquire serialization. So missing timeslot for memory slot should be fine.
https://github.com/Qiskit/qiskit-terra/blob/8061cfe04e33cc2827120b3aa1e2ddabcab38c6f/qiskit/qobj/converters/pulse_instruction.py#L502

**Comment by pollyshaw** [comment]
OK it sounds like I should revert these changes and instead change the implementation of Acquire.channels(). Will do so tomorrow.

**Comment by pollyshaw** [comment]
I have made the change to only return the channel from an Acquire channel, and made a minor modification to lowering.py as it used Acquire.channels to retrieve the memory slot index. I think the alternative way of finding it does the same thing.

There is still one failing test which is the reason for my delayed update of this PR. It is in test_schedule.py:

```python    
        def test_overlapping_schedules(self):
        """Test overlapping schedules."""

        def my_test_make_schedule(acquire: int, memoryslot: int, shift: int):
            sched1 = Acquire(acquire, AcquireChannel(0), MemorySlot(memoryslot))
            sched2 = Acquire(acquire, AcquireChannel(1), MemorySlot(memoryslot)).shift(shift)

            return Schedule(sched1, sched2)

        self.assertIsInstance(my_test_make_schedule(4, 0, 4), Schedule)
        self.assertRaisesRegex(
            PulseError, r".*MemorySlot\(0\).*overlaps .*", my_test_make_schedule, 4, 0, 2
        )
        self.assertRaisesRegex(
            PulseError, r".*MemorySlot\(1\).*overlaps .*", my_test_make_schedule, 4, 1, 0
        )
```
The reason this fails is because MemorySlots no longer appear in the schedule objects' dictionaries of timeslots, as those are derived from the channels, which now don't contain Memory Slots. The remaining AcquireChannels have overlapping schedules, but as they are different channels (indexed 1 and 2) these don't cause an exception, *even though* they share the same MemorySlot, which may well be problematic under execution. 

I am not quite sure what to do here. Should we be changing the way time slots work, so that they use objects other than those returned from instruction.channels? Or is the behaviour of making a shared MemorySlot have responsibilities overlapping in time OK, or at least not something that the model should check for?

If I make the Acquire channels the same and make modifications to the expected message I can make the test pass:

```python
     def test_overlapping_schedules(self):
        """Test overlapping schedules."""

        def my_test_make_schedule(acquire: int, memoryslot: int, shift: int):
            sched1 = Acquire(acquire, AcquireChannel(0), MemorySlot(memoryslot))
            sched2 = Acquire(acquire, AcquireChannel(0), MemorySlot(memoryslot)).shift(shift)

            return Schedule(sched1, sched2)

        self.assertIsInstance(my_test_make_schedule(4, 0, 4), Schedule)
        self.assertRaisesRegex(
            PulseError, r".*AcquireChannel\(0\).*overlaps .*", my_test_make_schedule, 4, 0, 2
        )
        self.assertRaisesRegex(
            PulseError, r".*AcquireChannel\(0\).*overlaps .*", my_test_make_schedule, 4, 1, 0
        )
```
But I can't tell if the test is now testing all the intended behaviour.

I've changed the PR to [WIP] as I haven't checked if I need new tests for Acquire now that I've changed the behaviour of the channels but I thought it would be good to check in and ask for advice on this test before I polished up the rest.

I suspect also that 'good first issue' may no longer be an accurate tag for this ticket, so, whilst I'm happy to continue, if the maintainers would prefer to take this off me I'd also be fine with that.

**Comment by nkanazawa1989** [comment]
Thanks for updating the PR! I understand the problem. Sounds like it depends how backend controller handles this situation. If it allows simultaneous access to the same buffer memory then it should be okey to remove this test with release note. Otherwise we should not remove memory slots from instruction channels. In this case, perhaps we can add validation to each instruction constructor so that they only accept pulse channel subclass, e.g. `Delay` instruction doesn't take memory slots, except for `Acquire` instruction. I'm fine with replacing memory slot prefix as long as we can execute job on real backends.

It would be great if you could continue. I'm happy to continue the discussion and review :)

**Comment by wshanks** [comment]
In the backend code, I see that currently only a single measurement per channel is supported for pulse jobs or for circuits with pulse gates with acquire instructions in them. Also, across channels, all the acquire instructions need to begin at the same time. These  constraints are somewhat due to the implementation (developer time for implementing multiple measurements with pulse gates has not been allocated) but also due to hardware (I think IBM hardware does not support overlapping acquisitions on different channels). Related to this, the backend actually ignores the acquisition duration. Since there is only one acquisition, this is okay.

So the backend is more strict but I think it is good to assume that one day multiple acquisitions could occur within a schedule, perhaps even partially overlapping acquisitions on different acquire channels. Testing that no two acquisitions can overlap and use the same memory slot seems reasonable to me.

I think it might be best to have `Schedule` track memory slots along with channels in the `timeslots` that it tracks internally. The change would probably be here (check for a `mem_slot` attribute?): https://github.com/Qiskit/qiskit-terra/blob/a18df1456c79dbbd52dae1bd1185c68a0b3e891a/qiskit/pulse/schedule.py#L1486-L1504

The alternative would be to promote memory slots to `Channel`s but then there would need to be special casing to make sure instructions are never added to them.

**Comment by nkanazawa1989** [comment]
According to @taalexander 's comment [here](https://github.com/Qiskit/qiskit-terra/pull/8166#issuecomment-1155127401), the first option seems reasonable to me. We can remove memory slots and reg slots from acquire instruction `.channels`, and instead we implicitly expose them to the schedule timeslots. We also remove these slots from here because `Schedule.channels` is generated based on the key of timeslots dictionary.
https://github.com/Qiskit/qiskit-terra/blob/ed4e1a397d7faa38274f98c54ba5750043c32929/qiskit/pulse/schedule.py#L237-L240

**Comment by taalexander** [comment]
@wshanks

Personally, I would like to avoid major changes to classical IO behaviour right now. The reason being that the advent of control-flow in hardware is going to have an impact on the timing and memory semantics we currently expose and I don't think we yet know what changes to make.

I do think that to a degree it will look like representing memoryslots as channels but I also think the problem of timing access to memory resources could be avoided by using immutable SSA value semantics instead and not focusing on sharing a memory resource in time.

**Comment by wshanks** [comment]
@taalexander just to clarify -- you are saying you don't want memory slots promoted to pulse channels? Does the other suggestion of removing `MemorySlot` from `Acquire.channels` but still tracking it internally in `Schedule` seem okay? I wasn't sure what counted as a major change for you.

**Comment by pollyshaw** [comment]
@nkanazawa1989 Thanks for approving this! Is there anything else I need to do now? I don't seem to have a 'merge' button so perhaps a contributor needs to merge it.

**Comment by nkanazawa1989** [comment]
I'll merge if other people are happy with the changes. @wshanks @taalexander ?

**Comment by nkanazawa1989** [comment]
congrats @pollyshaw ! Thanks for your contribution :)
