### ISSUE TITLE
Are test/qobj files valid?

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#716]
### Informations

- **Qiskit Terra version**: 0.6
- **Python version**: 3.6
- **Operating system**: OSX

### What is the current behavior?
I am trying to clean up depreciation warnings from the tests but have run into errors where by I cannot get results from running the qobj in `test/qobj`

### Steps to reproduce the problem

```python

import qiskit
import json
from qiskit.qobj._qobj import Qobj

with open('test/python/qobj/cpp_conditionals.json', 'r') as file:
    qobj = qiskit.qobj._qobj.Qobj.from_dict(json.load(file))

backend = qiskit.get_backend('local_statevector_simulator')
job = backend.run(qobj)
job.result()
```

```python

     95             qobj.config.shots = 1
     96         for experiment in qobj.experiments:
---> 97             if getattr(experiment.config, 'shots', 1) != 1:
     98                 logger.info("statevector simulator only supports 1 shot. "
     99                             "Setting shots=1 for circuit %s.", experiment.name)

AttributeError: 'QobjItem' object has no attribute 'config'
```
### What is the expected behavior?
Should be able to get back results

### Suggested solutions
It seems like a `config` section is needed for each `experiment`, but is not in the original input qobj.

**Comment by diego-plan9** [comment]
No, I don't really think we can assume the files in `test/python/qobj` are 100% valid at the moment. They should be only "valid according to the usage that is made of them in `test/python/test_qasm_simulator_cpp.py`", since it is the only place they were used, and have been briefly touched in the successive updates to the schema (#709 , #655, etc) but _only_ for making the tests pass.

It might be worth considering adding it as a subtask of #664, although I'm not sure of the importance, as they are basically helpers for the C++ simulator tests rather than examples of valid Qobjs. @chriseclectic , any suggestions?

**Comment by nonhermitian** [comment]
Ok.  Currently the test example in question gives a depreciation warning, and switching to the statevector simulator results in an error.

**Comment by delapuente** [comment]
@nonhermitian @diego-plan9 is this a bug?

**Comment by nonhermitian** [comment]
I would say yes.  If a depreciation warning says use another backend, but the backend fails due to an invalid qobj then I would say we have an issue.

**Comment by 1ucian0** [comment]
So, this issue is about updating the files in `test/python/qobj/`, am I wrong?

**Comment by ajavadia** [comment]
There is no deprecation warning during these tests anymore, so I'm closing this.
