### ISSUE TITLE
Truncating floats in QASM dump alters circuit's functionality

### ISSUE THREAD

**Issue by burgholzer** [Qiskit/qiskit-terra#7166]
### Information

- **Qiskit Terra version**: 0.18.3 (dates back to 0.14)
- **Python version**: Any
- **Operating system**: Any

### What is the current behavior?
In #4276, the `pi_check` function was introduced for pretty printing the list of parameters when dumping a `QuantumCircuit` to `qasm`, see 
https://github.com/Qiskit/qiskit-terra/blob/637acc0c408d8199dd58780cc3dafabc14e61a0f/qiskit/circuit/instruction.py#L450-L463
This also introduced a fixed truncation (`ndigits=8`) of floating point numbers that are not close to any fraction or fraction of pi. However, *8* digits is not enough to uniquely identify a double precision floating point number. You need up to *17* significant digits for that. This leads to the following situation:

Let's say I have a circuit that contains, e.g., a phase gate with more than 8 significant digits in its rotation angle.
Then, I dump the circuit to a `.qasm` file and read that file back into a `QuantumCircuit`.
If I compare both unitary functionalities (i.e., the respective unitary matrices), these will no longer be equal due to the numerical error introduced by the truncation.

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, execute, Aer

qc = QuantumCircuit(1)
qc.p(1/4096, 0)

qasm_str = qc.qasm()

backend = Aer.get_backend('aer_simulator')

qc.save_unitary()
job = execute(qc, backend)
result = job.result()
unitary = result.get_unitary(qc)

qc_qasm = QuantumCircuit.from_qasm_str(qasm_str)
qc_qasm.save_unitary()
job = execute(qc_qasm, backend)
result = job.result()
unitary_qasm = result.get_unitary(qc_qasm)
    
print(unitary == unitary_qasm)
```
yields
```bash
[[ True  True]
 [ True False]]
```

### What is the expected behavior?

Merely dumping a file to `.qasm` should not alter a circuit's functionality.

### Suggested solutions

A quick fix for this would be to just change the default value for the `ndigits` parameter in the respective function call to `17`.

**Comment by levbishop** [comment]
I tend to agree that having lossless-as-possible mode for qasm export is a useful enhancement. Both for the reason of interfacing with external tools, and also for debug purposes.

**Comment by jakelishman** [comment]
I'm on board with adding more precision to QASM 2 output, I'm just not certain the best way to go about it here.  We can't (officially) add anything to the signature of `Instruction.qasm`, because that's a public interface that we expect people to inherit from, so starting to pass it extra keywords would break compatibility.

A couple of ways we _could_ go:
- break compatibility anyway, and just wrap calls to `Instruction.qasm` in a `try: ...; except TypeError`.
- replace the `ndigits` in all Qiskit `Instruction.qasm` definitions with a reference to a global variable, context-managed by `QuantumCircuit.qasm`, which does accept the keyword.
- change the output to always use more digits in every case

None of those are super nice to me, but there may be other options.  The last is probably the nicest, but it doesn't solve the other underlying problem that calls to `pi_check` are hard-coded, so anything that falls close to a multiple of pi will get (very) lossily converted.

This functionality will (or should) be available in the OpenQASM 3 exporter.  The way internal instructions provide their QASM definition (at the moment) is by returning AST nodes, so that's a lossless conversion, and the printer is completely separated, and can take many more options - one of the ones already implemented is to completely disable all the `pi_check` conversions (which, to me at least, might want to be the default).  It should be not too hard to ensure that the default printing behaviour for floats is "enough digits to uniquely identify a single float with the given precision".

**Comment by burgholzer** [comment]
The second option certainly provides the most flexibility. `QuantumCircuit.qasm` could then just accept `ndigits` *and* `eps` keywords. Although, I am not so sure whether this flexibility is really needed.
One possibility could be to add a `numeric` flag/keyword to the `QuantumCircuit.qasm` function that just skips the `pi_check` call all together and just emits an as precise as possible floating point representation (i.e., up to 17 decimals) for every parameter.
Or the other way around: always print the numerically-accurate representation (skipping `pi_check`) and provide a flag/keyword for pretty printing/exporting (possibly at the cost of precision).

Having `pi_check` disabled per default sounds like a good idea for OpenQASM 3 export. Then, users can decide whether they want to pretty print/export their circuit at the cost of precision.

**Comment by burgholzer** [comment]
I get that. But then I would suggest the easiest workaround/fix that does not need any kind of deprecation would just be to change the magic `ndigits` constant in the `Instruction.qasm()` from *8* to *17*. 
In addition to that it might make sense to explicitly specify a smaller `eps` (something in the range of *1e-12* to *1e-14*), in order to lessen the impact of the approximation to fractions of pi.

In this fashion, no compatibility is broken and the export to OpenQASM 2 gets a lot more accurate / less lossy.

**Comment by EliasLF** [comment]
I just ran into this bug/peculiarity of `Instruction.qasm()`, too. Any updates on @burgholzer's proposed short-time solution?
An `eps` value of 1e-12 in `pi_check` seems to work fine in my case.

**Comment by jakelishman** [comment]
Sorry this fell through the cracks.  I'm ok with accepting a PR that changes `eps` to be tighter here, if that helps people.

**Comment by burgholzer** [comment]
No worries. Would you also be willing to change `ndigits` from `8` to `17` in order to get `double` precision instead of `float` precision?
