### ISSUE TITLE
Efficiency bug in synthesis warning

### ISSUE THREAD

**Issue by epelofske-LANL** [Qiskit/qiskit-terra#7224]
### Information

- **Qiskit Terra version**:  `qiskit-terra==0.18.3`
- **Python version**: 3.9
- **Operating system**: macOS

### What is the current behavior?
Across many different circuits I am getting this error when executing jobs. 

```
//anaconda3/envs/lib/python3.9/site-packages/qiskit/transpiler/runningpassmanager.py:166: UserWarning: Resynthesized 

<qiskit.circuit.library.standard_gates.sx.SXGate object at 0x131c1de80>
<qiskit.circuit.library.standard_gates.x.XGate object at 0x131c1deb0>

and got

<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x131d96d90>
<qiskit.circuit.library.standard_gates.sx.SXGate object at 0x131d96d60>
<qiskit.circuit.library.standard_gates.rz.RZGate object at 0x131d96d00>

but the original was native (for ['id', 'rz', 'sx', 'x', 'cx', 'reset']) and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
```

### Steps to reproduce the problem
The warning does not provide much useful information on what exactly the bug is.

**Comment by jlapeyre** [comment]
@epelofske-LANL Thanks for reporting this!

**Comment by levbishop** [comment]
Thanks for the report. In this particular case you pasted above the warning is overzealous and is safe to ignore. Z.SX.Z is indeed a longer sequence in terms of gate count, but nevertheless actually preferable over SX.X in terms of fidelity (Z gates do not cause infidelity for common hardware platforms). We changed this message to a DEBUG level log message in #7124 Since the warning can still in certain cases indicate an actual problem, we hope to have a more complete solution once #7084 merges.

Closing as already-fixed but feel free to reopen if there's something I missed.
