### ISSUE TITLE
Review the API of the `DAGCircuit`

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#728]
### What is the expected enhancement?
It seems a lot of DAG manipulation [requires accessing the underlying multigraph](https://github.com/Qiskit/qiskit-terra/issues/289#issuecomment-410714542). Common operations should be supported at the `DAGCircuit` level.

**Comment by eddieschoute** [comment]
Let's see if I can list some uses of DAGCircuit that should be supported:

1. Constructing a DAGCircuit is still quite hairy. You need to manually add bases and gates, especially the later is very obscure. (Qiskit internally also has a list of hardcoded "gate data" to set this up).
2. To Better support (1), I wrote my own method to construct an empty DAGCircuit from an existing circuit that just copies the bases and gates.
3. #289 
4. Iterating and access operations should hide the DAGCircuit internals. Currently, the only way to inspect the nodes efficiently is to access `multi_graph` directly. Existing methods are limited to iterating over _all_ layers, getting _all_ nodes of a name (`get_named_nodes`),  and some various operations for deleting _all_ ancestors or descendants of a node. These are very heavy-handed interactions.
5. Inspecting node information is currently not abstracted away. I need to access the node data of the multi-graph to find out what the operation is (`qargs` and `name`). So I end up with code like: 
    ```
    if len(op_node['qargs']) == 2 and op_node['name'] != "barrier":
    ```
    and
    ```
    # Reshape the nodes to their qargs.
    binops_qargs: Set[Tuple[Reg, Reg]] = {
        # only keep qargs field as an immutable tuple.
        n["qargs"] for n in node_data
        # Filter out op nodes that are not barriers and are 2-qubit operations
        if n["type"] == "op" and n["name"] != "barrier" and len(n["qargs"]) == 2}
  
    ```

**Comment by 1ucian0** [comment]
Here is a list of DAG methods/attributes. Am I missing something? Comment!

### Currently supported
 - `node(node_id)`
Get the node data by node id
 - `qubits()`
Return a list of qubits as (QuantumRegister, index) pairs
 - `clbits()`:
Return a list of bits as (ClassicalRegister, index) pairs
 - `add_qreg(qreg)`
Add all wires in a quantum register.
 - `add_creg(creg)`
Add all wires in a classical register.
 - `size()`
Return the number of operations.
 - `depth()`
Return the circuit depth
 - `width()`
Return the total number of qubits used by the circuit.
 - `num_cbits()`
Return the total number of bits used by the circuit
 - `__eq__(other)`
Are they isomorphic?
 - `substitute_node_with_dag(node, input_dag, wires=None)`
Replace one node with dag.
 - `named_nodes(*names)`
Get the set of "op" nodes with the given name.
 - `twoQ_nodes()`
Get list of 2-qubit nodes.
 - `successors(node)`
Returns the successors of a node.
 - `descendants(node)`
Returns the descendants of a node.
 - `bfs_successors(node)`
Returns successors of a node in BFS order.
 - `quantum_successors(node)`
Returns the successors of a node that are connected by a quantum edge.

### Needs modification
 - `apply_operation_back(op, qargs=None, cargs=None, condition=None)`
Apply an operation to the output of the circuit. **It should extend the qargs and cargs if there were not in the DAG before**.
 - `apply_operation_front(op, qargs=None, cargs=None, condition=None)`
Apply an operation to the input of the circuit. **It should extend the qargs and cargs if there were not in the DAG before**.
 - `compose_back(input_circuit, wire_map=None)`
Apply the input circuit to the output of this circuit. **Should automatically extend the qregs/cregs**.
 - `compose_front(input_circuit, wire_map=None)`
Apply the input circuit to the input of this circuit. **Should automatically extend the qregs/cregs**.
 - `op_nodes(self, op=None, data=False)`. **The flag `data` should be removed, since always returns an DAGNode**.
 - `threeQ_or_more_nodes()` Now returns (id, data), and it should return DAGNode.

### Should be added
 - `nodes()`
Iterator for node values. PR #1916.
 - `remove_node(node)`
Like the current `_remove_op_node(n)`, but taking a DAGNode.

### Should be removed
 - `get_qubits()` Deprecated.
 - `get_bits()` Deprecated.
 - `node_counter()` Property. Deprecated.
 - `rename_register(regname, newname)` Unused.
 - `remove_all_ops_named(opname)` Unused and untested.
 - `extend_back(dag, edge_map=None)` Its functionality should be covered by `compose_back`.
 - `num_tensor_factors()` Unused.
 - `qasm()` Deprecated.
 - `node_nums_in_topological_order()` Its functionality should be covered by `nodes()`.
 - `substitute_circuit_all(op, input_circuit, wires=None)` Unused.
 - `get_op_nodes(op=None, data=False)` Deprecated.
 - `get_gate_nodes(data=False)` Deprecated.
 - `gate_nodes(data=False)` Its functionality should be covered by `nodes()`.
 - `get_named_nodes(*names)` Deprecated.
 - `get_2q_nodes()` Deprecated.
 - `get_3q_or_more_nodes()` Deprecated.
 - `remove_ancestors_of(node)` Unused and untested.
 - `remove_nonancestors_of(node)` Unused and untested.
 - `remove_nondescendants_of(node)` Unused and untested.
 - `remove_edge(node1, node2)`. Breaks invariants. PR #1879
 - `has_edge(node1, node2, wire=None)` Its functionality is covered by `successors(node)`.

### Hmm... I'm not sure...
 - `ancestors(node)` It should be discouraged. I'm not sure if we should have a double linked list just for this. Candidate to be removed?
 - `layers()`
Yield a shallow view on a layer of this DAGCircuit for all d layers of this circuit

**Comment by ajavadia** [comment]
this is pretty old and all addressed as far as I can tell
