### ISSUE TITLE
ImportError on Google Colab

### ISSUE THREAD

**Issue by Harrison-Tsai** [Qiskit/qiskit-terra#7370]
### Informations

- **Qiskit version**: newest version
- **Python version**: 3.7
- **Operating system**:
- Platform: Google Colab

### What is the current behavior?
After the update, the following pops up

/usr/local/lib/python3.7/dist-packages/pennylane_qiskit/qiskit_device.py in <module>()
25 from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister
26 from qiskit import extensions as ex
---> 27 from qiskit.circuit.measure import measure
28 from qiskit.compiler import transpile
29 from qiskit.converters import circuit_to_dag, dag_to_circuit

ImportError: cannot import name 'measure' from 'qiskit.circuit.measure' (/usr/local/lib/python3.7/dist-packages/qiskit/circuit/measure.py)

The original code worked well before the update in 06/12/2021.

**Comment by jakelishman** [comment]
This looks like `pennylane_qiskit` is importing a function that was never meant to be public ik that location in the first place - the old function `qiskit.circuit.measure.measure` should actually have been accessed by the name `QuantumCircuit.measure`.

Regardless, we shouldn't have removed that without first issuing a deprecation warning (I'm pretty sure I'm the culprit here), so we can add the function back for 0.19.1 with a deprecation warning.

**Comment by Harrison-Tsai** [comment]
Ok I see. Thank you for your prompt reply!
