### ISSUE TITLE
qasm method fails on QuantumCircuit with delay element

### ISSUE THREAD

**Issue by dmiracle** [Qiskit/qiskit-terra#7452]
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**: 3.8.12
- **Operating system**: osx

### What is happening?

When trying to return the QASM string from a `QuantumCircuit` with a `delay` element using the `qasm` method, qiskit returns `TypeError: 'NoneType' object is not iterable`.  I have included a simple example here and a couple more examples of working and non-working code at this [gist](https://gist.github.com/dmiracle/a5aa5705bf11f2e3e66bb2cac14a0911)

### How can we reproduce the issue?

Here is a simple example that fails
```
import qiskit

qc = qiskit.QuantumCircuit(1)
qc.delay(10, unit='dt')
qc.delay(10, unit='s')

qasm = qc.qasm()

print(qasm)
```

This results in the following error traceback

```
Traceback (most recent call last):
  File "delay-qasm.py", line 23, in <module>
    qasm = qc.qasm()
  File "/Users/dylan/.../venv/lib/python3.8/site-packages/qiskit/circuit/quantumcircuit.py", line 1696, in qasm
    _add_sub_instruction_to_existing_composite_circuits(
  File "/Users/dylan/.../venv/lib/python3.8/site-packages/qiskit/circuit/quantumcircuit.py", line 4728, in _add_sub_instruction_to_existing_composite_circuits
    for sub_instruction, _, _ in instruction.definition:
TypeError: 'NoneType' object is not iterable
```

### What should happen?

The output from the above should look like this 
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[1];
delay(10) q[0];
delay(10) q[0];
```

### Any suggestions?

This can be fixed by adding `"delay"` to the list `existing_gate_names` [here](https://github.com/Qiskit/qiskit-terra/blob/9cc9225f249d3a895d9f3944175ea7b681d248c0/qiskit/circuit/quantumcircuit.py#L1591-L1637)

**Comment by jakelishman** [comment]
`delay` isn't a known instruction in QASM 2, and it's not defined in `qelib1.inc`, so we can't really just add it to the known gates list.  In principle, we could have some mechanism for declaring instructions with no definition as `opaque` in the output QASM, but I think we'd need to have `QuantumCircuit.qasm` accept a list of names that it should declare like that; it also wouldn't be great if we just pass through _all_ gates with no definition as `opaque`, since that might just be masking bugs in the input.

**Comment by dmiracle** [comment]
Ok, thanks for the info. Might be useful to have an error that says something for instructions that aren't qasm but makes sense as is also.
