### ISSUE TITLE
'_' makes matplotlib to render the following character as subscript

### ISSUE THREAD

**Issue by MozammilQ** [Qiskit/qiskit-terra#7455]
### Environment

- **Qiskit Terra version**:  0.19.1
- **Python version**:  3.9.9
- **Operating system**: Linux(Fedora 34)

### What is happening?

The '_' in the name of QuantumRegister forces the following character to be rendered as subscript
In this example see the 'r' is rendered as a subscript. 

![issue_01012022](https://user-images.githubusercontent.com/54737489/147839273-e1afa3b0-4b36-4cf5-9c77-8256223eb666.png)

The problem vanishes when the number of qubits is increased to 2 or more.

![issue_01012022_4](https://user-images.githubusercontent.com/54737489/147839502-27cd3634-d237-4f65-bb28-81522044d4f8.png)

### How can we reproduce the issue?

from qiskit import QuantumRegister, QuantumCircuit
num_of_qubits=1
q_reg=QuantumRegister(num_of_qubits, 'q_reg')
qc=QuantumCircuit(q_reg)
qc.draw(output='mpl')

### What should happen?

This should be the output:
![issue_01012022_3](https://user-images.githubusercontent.com/54737489/147839433-fab0ef9f-7e72-4d0f-9518-c35f88572162.png)

**Comment by enavarro51** [comment]
Thanks for spotting this. Actually the second case is incorrect as well. It should be q_reg<sub>0</sub>.
@javabster Can you assign this to me? Thanks.

**Comment by MozammilQ** [comment]
@enavarro51 , actually I was working on this, now, since you have asked for the permission. You go ahead with this and I tell you my recent progress in this:

Go to qiskit/visualization/matplotlib.py#L456
I changed this: 
 words = [word.replace("_", r"\_") if word.count("_") > 1 else word for word in words]
to this:
 words = [word.replace("_", r"\_") if word.count("_") >= 1 else word for word in words]
and got the image I mentioned in the what should happen section above.

and you put "^" in place of "_" and see new hosts of problems

Now, you take it from here :)

**Comment by enavarro51** [comment]
Thanks, @MozammilQ. I believe this is a bit of a deeper problem with register naming. We'll probably need to get some input from the IBM side for this. OpenQASM 3.0 says this about names.

"Names of gates, variables, and constants — In OpenQASM 2, the names of registers
and gates must begin with a lower-case alphabetic ASCII character. This constraint is
relaxed in OpenQASM 3: identifiers may now begin with other characters, such as capital
letters, underscores, and a range of unicode characters. For example, angular values used
as gate arguments may now be represented by greek letters. (The identifier π is reserved in
OpenQASM 3 to represent the same constant as pi.) Note that OpenQASM 3 has a slightly
different set of keywords from OpenQASM 2. This may cause errors in OpenQASM circuits
which happen to use a keyword from version 3 as an identifier name: such identifiers would
have to be renamed in order for the source to be valid OpenQASM 3."

In OpenQASM 2.0, names were restricted to alphanumeric and underscores. This means '^' should not have been allowed in register names. In #3827 an attempt was made to fix more than one underscore in a name displaying with matplotlib. But that solution was not complete and no tests were added, so part of that problem is showing up now. 

The final problem is that the text_width calculation in matplotlib strips out the underscores, which for multiple underscores in a name, results in an incorrect text_width which can lead to letters being cut off to the left.

So a solution could be to put a validity check for what are proper 2.0 and 3.0 names., do the replacement of '\_' with '\\\_', and finally fix the text_width calcs to properly handle '\_'.

**Comment by MozammilQ** [comment]
Oh Nice! I didn't know that the problem could be this deep, @enavarro51 thanks for sharing the information, you do have a deeper understanding of the problem :)
