### ISSUE TITLE
User-entered register names can create invalid OpenQASM

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#7458]
### Environment

- **Qiskit Terra version**: 0.20.0
- **Python version**: 3.8
- **Operating system**: Ubuntu

### What is happening?

There is a regex check for proper register names in register.py, but it uses match instead of fullmatch, which means it really only checks that the first char is a lower-case alpha. This means a user can enter invalid OpenQASM register names.

It can also cause several different problems with the matplotlib and latex drawers.

### How can we reproduce the issue?

```
qr = QuantumRegister(3, "a*$(%@)")
qc = QuantumCircuit(qr)
print(qc.qasm())

OPENQASM 2.0;
include "qelib1.inc";
qreg a*$(%@)[3];
```

### What should happen?

Invalid register names should not be allowed.

### Any suggestions?

I think a solution like #7157 for the register names would be good. In that PR, instead of raising if an invalid name is entered, names are converted to a valid form.

**Comment by jakelishman** [comment]
I don't think we should require register names to be valid OpenQASM 2 identifiers; QASM is a separate thing, and OpenQASM 3 will make many more identifiers valid anyway, by expanding into various parts of Unicode.  The solution in #7157 is still appropriate, though; we can just require the exporter to escape any names that it outputs.

**Comment by enavarro51** [comment]
Actually I was following this from `register.py`. It doesn't really work since it uses `match` instead of `fullmatch`. As long as the first char is lower alpha, it matches, so the rest can be anything. If we don't want to restrict register names, then this code should probably be removed. We'd still need to address the issue with the drawers.
```
30    # Register name should conform to OpenQASM 2.0 specification
31    # See appendix A of https://arxiv.org/pdf/1707.03429v2.pdf
32    name_format = re.compile("[a-z][a-zA-Z0-9_]*")

102            if self.name_format.match(name) is None:
103               raise CircuitError(
104                    "%s is an invalid OPENQASM register name. See appendix"
105                    " A of https://arxiv.org/pdf/1707.03429v2.pdf." % name
106                )
```

**Comment by jakelishman** [comment]
Oh, my mistake sorry - I didn't realise that we were already restricting the names on creation.  If it were up to me, I'd remove that provision entirely and have the QASM exporters handle escaping register names, but since we've got it for now, I think improving the verification would be better, rather than escaping the names.  If we escape the names, you'd get more confusing errors, where say `my register` and `my_register` might both be escaped to the same string, and you'd see "can't have two registers of the same name" rather than "`my register` is an invalid name".

If we defer escaping to the exporters, they can handle naming collisions by appending a counter or something, because they'll be working with the full context.

**Comment by enavarro51** [comment]
I think these are the issues.
- Register name restriction doesn't work as is.
- If we restrict names now, some existing circuits may not work. Can do deprecation.
- If we leave unrestricted, some names can crash the mpl and latex drawers, won't work for qasm, but will work otherwise.
- As far as escaping is concerned, I think that should be left to the exporter level.

So I think this just needs a decision as to what is the least worse.
