### ISSUE TITLE
Ket convention statevector drawer ignores max_size

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-terra#7516]
### Environment

- **Qiskit Terra version**: 0.34.0
- **Python version**: 3.9.8
- **Operating system**: OSX

### What is happening?

Currently, `Statevector.draw('latex')` ignores the `max_size` parameter.

### How can we reproduce the issue?

```
from qiskit.quantum_info import Statevector
from qiskit.visualization.state_visualization import state_drawer

sv = Statevector.from_label('++++')
state_drawer(sv, 'latex', max_size=3)
```
<img width="906" alt="Screenshot 2022-01-11 at 12 41 42" src="https://user-images.githubusercontent.com/36071638/148944414-c982f2cc-eb9f-4ab9-a66a-98049e0ed3c6.png">

We get 12 terms, but I expect to get 3.

### What should happen?

The drawer should change its behaviour according to the `max_size` parameter.

### Any suggestions?

I think adding `**args` to this line might do it.
https://github.com/Qiskit/qiskit-terra/blob/5ea6e9557655b144228c29d7099375f5d2c91120/qiskit/visualization/state_visualization.py#L1183

**Comment by frankharkins** [comment]
Happy to look at this properly, can you assign me please?

**Comment by jakelishman** [comment]
I think the solution will be very slightly different to what Frank originally suggested, because the options to `array_to_latex` and `_state_to_latex_ket` are different, so we'll need to only pass the right options to each of those, but in principle that's the only change needed.

I'll just ping @frankharkins to check if you've got time to work on it?  If not, I'll return it to the pool of good first issues for somebody else to take a look at.

**Comment by IFWork** [comment]
Oh and in case it isn't the same bug in the code, the same issue occurs with .draw(output="latex_source")

**Comment by frankharkins** [comment]
Sorry I completely forgot about this, I'll have a look this week

**Comment by IFWork** [comment]
Has there been any luck at all?

**Comment by frankharkins** [comment]
Yes, sorry- I've fixed and am just writing a test now.
