### ISSUE TITLE
Local simulators should generate results according to the result schema

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#755]
### What is the expected enhancement?
In order to transition to using common standards, local simulators should report results following the proper schemas.

**Comment by delapuente** [comment]
Not sure if the original commentary wanted to say this should be high-priority or it was just pressing for moving to a separate issue as soon as possible. @ajavadia can you confirm this?

![captura de pantalla 2018-08-08 a las 19 36 45](https://user-images.githubusercontent.com/757942/43855193-24cf8a34-9b45-11e8-8309-22a1b3d930b5.png)

**Comment by jaygambetta** [comment]
@delapuente and @ajavadia I think we make this 0.7.

**Comment by diego-plan9** [comment]
I think it makes sense - at the moment, they still use the old result format internally, and make use of `result_from_old_style_dict()` for converting to the new result schema. Eventually they need to be updated, but since they _do_ work, let's assign it to the 0.7 milestone - @delapuente and @ajavadia , please revert if this is not correct.
