### ISSUE TITLE
Add date attribute to BasicAer job result

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#7781]
### What is the expected enhancement?

This is a practical improvement because it aligns the API with AerJob. It is also required according to https://arxiv.org/abs/1809.03452. See https://github.com/Qiskit-Partners/mthree/issues/94 for context.

**Comment by mtreinish** [comment]
The job objects in terra are explicitly decoupled from that specification. It has been since `JobV1` was introduced in #5086 which made the provider interface a terra construct and not a leaky object model abstraction of the IBM quantum API json payloads. As we improve the interface between qiskit and backends the object models become increasingly vendor agnostic and qiskit specific (for example if you look at `BackendV2` it has very little in common with that spec). If you want a standard date attribute as part of the job object that will need to be added to the abstract interface. However, for compatibility reasons if you want to make this a required field it would have to be part of `JobV2` we can start drafting, there is a wish list of things that will happen as part of the that effort (like flattening the job and result objects). I think we can transform this issue into a tracking one to add a `JobV2` interface that defines a better interface for job and result management and not specifically about adding a date field to basic aer.

As a random aside I also don't understand the use case for mthree  with basic aer, basic aer doesn't have any noise so you have no errors to mitigate.
