### ISSUE TITLE
The basis gate listed in the Transpiler document doesn't match the gates generated by qc.decompose()

### ISSUE THREAD

**Issue by yuttai** [Qiskit/qiskit-terra#7796]
### What is the expected enhancement?

When I read [the Transpiler document](https://qiskit.org/documentation/apidoc/transpiler.html), it says the basis_gates are ['id', 'rz', 'sx', 'x', 'cx'] which matches the basis gates for ibmq_manila. However, when this document uses `qc.decompose()` to transpile gates later, it transpiles the circuit to 'u2', 'u3', and 'p' which are not listed in the given basis gates. Should we change `qc.decompose()` to `transpile(qc, backend)` to make sure they use the basis gates listed previously?

**Comment by Cryoris** [comment]
Yeah I would agree. We should probably exchange all the `qc.decompose()` occurances to transpilations since e.g. the final decomposition of the Toffoli also doesn't use the actual basis gates of the device. Using the decomposition method is outdated (and far from optimal!) now that we don't have U1/2/3 as basis gates anymore.

**Comment by prakharb10** [comment]
Hi, did #8129 fix this or is there still work to be done?
