### ISSUE TITLE
CZ Gate output is not displayed correctly in qsphere diagram

### ISSUE THREAD

**Issue by Prakash3008** [Qiskit/qiskit-terra#7816]
### Informations

- **Qiskit version**: 0.34.2
- **Python version**: 3.9.7
- **Operating system**: Windows 10

### What is the current behavior?
![image](https://user-images.githubusercontent.com/45827034/160063162-71fc6694-e8f4-4c69-98bf-303bf95ac91a.png)
This is the output of cz-gate of two qubits with state of |11>

### Steps to reproduce the problem
Code:
```python
from qiskit import *;
from qiskit.quantum_info import *;
from qiskit.visualization import *;
czq3 = QuantumCircuit(2);
czq3.x(0);
czq3.x(1);
czq3.draw('mpl');
plot_state_qsphere(czq3);
czq3.cz(0,1);
czq3.draw('mpl');
plot_state_qsphere(czq3);
```

### What is the expected behavior?

Display CZ Gate output value of |11> = |-11> in qsphere diagram.

**Comment by jakelishman** [comment]
The image isn't _wrong_ per se, it's just fixed the gauge of the global phase - there's no difference between `|11>` and `-|11>` in a 2q Hilbert space.  I don't know the original reasoning behind that design choice, but I would expect it's to make it easier to compare two separate plots to each other.

I'll close this issue now, but there was a bit of on-going discussion in #7512, of which this issue is a duplicate.
