### ISSUE TITLE
The eval_observables function could accept a quantum_instance of type None

### ISSUE THREAD

**Issue by Anthony-Gandon** [Qiskit/qiskit-terra#7861]
### What should we add?

In QEOM, we want to use the eval_observables() function from aux_ops_evaluator.py 
after a call to a VQE or any other minimum eigensolver.
The following test case of QEOM runs with a non-quantum MinimumEigensolver.

```
def test_numpy_mes(self):
    """Test NumPyMinimumEigenSolver with QEOM"""
    solver = NumPyMinimumEigensolver()
    gsc = GroundStateEigensolver(self.qubit_converter, solver)
    esc = QEOM(gsc, "sd")
    results = esc.solve(self.electronic_structure_problem,
                        expectation=MatrixExpectation())
    for idx, energy in enumerate(self.reference_energies):
        self.assertAlmostEqual(results.computed_energies[idx], energy, places=4)
```
The qeom tries to retrieve the quantum_instance of the solver but **fails** in that case.

Also note that the evaluate_operators() method of the ground state_eigensolver had additional if/else conditions
to account for a missing quantum_instance.

**Comment by Cryoris** [comment]
This might be interesting in the broader context of algorithms and not just QEOM. It would for instance allow us to remove the logic inside `NumPyEigensolver` that currently evaluates auxiliary operators. So I think this would be a good idea.

@woodsp-ibm @dlasecki do you have an opinion on this? 🙂

**Comment by woodsp-ibm** [comment]
One thing that needs to be sorted is how does this fit in with the upcoming Estimators and which I can see VQE transitioning over to using exclusively. Having this extracted from current VQE and made more general in the interim to allow the evolution logic to use it seemed ok. I had suggested in the PR where this was created that a "better" place for this, if this is perhaps a more general method with opflow level objects that is viable in the longer term, that the method would better be located in opflow (rather than in algorithms).

**Comment by woodsp-ibm** [comment]
The aux_ops_evalutor is now deprecated pending removal. There is a newer utility that was done for the primitive based algos - and of course Estimator can much more directly be used. I am closing this as no new feature like this will be added to deprecated code.
