### ISSUE TITLE
Generating UCCSD circuit in Terra 0.20.0 returns empty circuit with zero qubits

### ISSUE THREAD

**Issue by JoelHBierman** [Qiskit/qiskit-terra#7868]
### Environment

- **Qiskit Terra version**: 0.20.0
- **Python version**: 3.9
- **Operating system**: Fedora 35

### What is happening?

When attempting to generate an instance of the `UCCSD` class object, the returned object is an empty circuit with zero qubits. I am posting this issue here and not in Qiskit nature because this seems to be a breaking change that was introduced in Terra 0.20.0. Previously this worked fine. (I am using Qiskit-nature 0.3.1).

### How can we reproduce the issue?

The following code reproduces the issue:

```
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit_nature.mappers.second_quantization import JordanWignerMapper, ParityMapper, BravyiKitaevMapper
from qiskit_nature.circuit.library import UCCSD, HartreeFock
import qiskit

ansatz_reps = 1

qubit_converter = QubitConverter(JordanWignerMapper())

HF_state = HartreeFock(num_spin_orbitals=10,
                                                       num_particles=(1,1),
                                                       qubit_converter=qubit_converter)

ansatz = UCCSD(qubit_converter=qubit_converter, num_particles=(1,1), num_spin_orbitals=10, reps=ansatz_reps, initial_state=HF_state)
print(ansatz)
print(ansatz.num_qubits)
print(HF_state.num_qubits)
```

This will return:
```

0
10
```

### What should happen?

Generating a `UCCSD` object like this should not return an empty circuit with zero qubits. This seems somewhat specific to how `UCCSD` is generated because the same issue does not show up for the `HartreeFock` class.

**Comment by Cryoris** [comment]
So I tracked this down and this issue was introduced in #7216. Before that, we were checking if `_data` is None to see if a blueprint circuit has been built or not. In #7216 we introduced a variable called `_is_built` for that check and changed `_data` to be an empty list when the circuit was not built instead of None. Now the `UCCSD` circuit in Qiskit Nature still does check `_data` -- but that argument is now never `None` and the circuit doesn't get built correctly.

The good news is that in the new Qiskit Nature release this is not a problem anymore but we should still fix this version incompatibility.

**Comment by JoelHBierman** [comment]
Ah great, thank you! I installed the main GitHub branch of qiskit-nature and that does seem to fix the problem.

**Comment by jakelishman** [comment]
Ok, by my understanding I think we can close this on the Terra side (breaking the subclass API in `BlueprintCircuit` wasn't a great choice on our part, but it'd be even more trouble to go back on that now), and if it's fixed in dev Nature, we're ok on that front too.  Feel free to re-open if there's more to discuss here.

**Comment by Cryoris** [comment]
In case someone sees this, with Nature 0.3.2 released this issue is also fixed on the current stable install.
