### ISSUE TITLE
Method validate_parameter() of GaussianSquare raises PulseError if you call it on a created pulse

### ISSUE THREAD

**Issue by Duumbo** [Qiskit/qiskit-terra#7882]
### Environment

- **Qiskit Terra version**: 0.19.2
- **Python version**: 3.10
- **Operating system**: MacOS

### What is happening?

The validate_parameter() method of the GaussianSquare pulse will raise an error if you call it after the pulse is created. This happen because the `width` and the `risefall_sigma_ratio` are both set.

### How can we reproduce the issue?

```python
import qiskit.pulse as ps

# For any given acceptable pulse it will raise an error.
out_pulse = ps.GaussianSquare(100, 0.3+0.3j, 2, 10). # Or any other param, that is not the focus.
out_pulse.validate_parameters()
```

### What should happen?

After looking at the source code, I figured this was an internal function that is called before the pulse if completed. It should be expected that you can't call this function for any given pulse (Drag or Gaussian too for exemple.)
Perhaps raise a different error in this case (the case of having a completed pulse.)

### Any suggestions?

Perhaps two solutions that are both equivalent, one that I don't really know what it represent to change the name of this particular function.
- Make this function private.
- Document the function to explain that it is not client-side code.

**Comment by jakelishman** [comment]
This is mostly a question of how we design interfaces for subclassing.  In this case, it perhaps would have been better to make this internal hook function private, as you mention, but since it's now out there in the wild, it's hard for us to walk that back.  The documentation route you mentioned is a good solution, though - we can just add some text to the docstring of `ParametricPulse.validate_parameters` (which should largely be inherited by the other classes) to say that it's an internal check for subclasses, and not part of the user-facing API.
