### ISSUE TITLE
Detail more  latex error messages when plotting circuit.

### ISSUE THREAD

**Issue by Scinawa** [Qiskit/qiskit-terra#792]
### What is the expected enhancement?
I would expect to have more debug information for errors in the generation of circuits plotted by qiskit.
For instance, I would like to know that the name i gave to a register contain unallowed character, instead of guessing.
Instead I received a generic "is Qcircuit library installed?" error.

**Comment by delapuente** [comment]
Related to #601

**Comment by mtreinish** [comment]
@delapuente I actually would say this isn't really related to #601.

 The fundamental issue here is that when we subprocess out to call pdflatex here: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/tools/visualization/_circuit_visualization.py#L282-L291 we don't do anything with the actual output from the pdflatex command. Instead we just assume that the error is because pdflatex isn't installed and print the message @Scinawa is referring to.

The fix here would be probably to just print the pdflatex output on error (or alternatively write it to a log file since pdflatex is fairly verbose) so that there is actually debug info on what went wrong.

**Comment by ajavadia** [comment]
@mtreinish Right, I agree that logging the error is the way to go. Then we can probably simplify the current error catching hierarchy which tries to catch known errors.

@Scinawa it would be helpful if you could provide a code example to reproduce the error (for example what disallowed characters did you use?)
