### ISSUE TITLE
Use of .to_gate() function

### ISSUE THREAD

**Issue by Snuag** [Qiskit/qiskit-terra#8015]
![image](https://user-images.githubusercontent.com/100287263/166410288-a5213260-df1a-46ef-97d4-7da5b30244bd.png)

I am new to this field. I have seen using .to_gate()  function in Deutsch Dozsa Algorithm and searched for it but haven't really understood the exact use after googling. Can anyone help me out

**Comment by jakelishman** [comment]
This is an instance method on the `QuantumCircuit` class.  It lets you build up a custom gate by constructing a circuit, and then turn the resulting circuit into a `Gate` object, which you can add to a larger circuit with `QuantumCircuit.append`.  For example:
```python
In [1]: from qiskit import QuantumCircuit
   ...: my_gate = QuantumCircuit(2, name="make_bell")
   ...: my_gate.h(0)
   ...: my_gate.cx(0, 1)
   ...: my_gate = my_gate.to_gate()
   ...:
   ...: qc = QuantumCircuit(4, 4)
   ...: qc.append(my_gate, [0, 1], [])
   ...: qc.append(my_gate, [2, 3], [])
   ...: qc.measure_all()
   ...: qc.draw()
Out[1]:
        ┌────────────┐ ░ ┌─┐
   q_0: ┤0           ├─░─┤M├─────────
        │  make_bell │ ░ └╥┘┌─┐
   q_1: ┤1           ├─░──╫─┤M├──────
        ├────────────┤ ░  ║ └╥┘┌─┐
   q_2: ┤0           ├─░──╫──╫─┤M├───
        │  make_bell │ ░  ║  ║ └╥┘┌─┐
   q_3: ┤1           ├─░──╫──╫──╫─┤M├
        └────────────┘ ░  ║  ║  ║ └╥┘
   c: 4/══════════════════╬══╬══╬══╬═
                          ║  ║  ║  ║
meas: 4/══════════════════╩══╩══╩══╩═
```

In general, you're better asking this sort of question [in our public Slack channels](https://ibm.co/joinqiskitslack) - this is a bug tracker for Qiskit, rather than a help channel.

**Comment by Snuag** [comment]
Thank you.Sure,  I will post such questions on slack from next time!

**Comment by mvirts** [comment]
I found this bug before I found how to use qiskit.circuit.gate.Gate. Maybe a documentation update could help?
