### ISSUE TITLE
Install Error (Editable mode, Py 3.7)

### ISSUE THREAD

**Issue by Rcuz8** [Qiskit/qiskit-terra#8135]
### Environment

- **Qiskit Terra version**: 0.20.2
- **Python version**: 3.7.13
- **Operating system**: macOS 12.0.1
- **PIp version***: pip 22.1.2 

### What is happening?

There is an error installing the requirements in editable mode.

### How can we reproduce the issue?

```
pip install -e .
```

```
...
Collecting scipy>=1.5
  Using cached scipy-1.7.3.tar.gz (36.1 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
 ...
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Terminal session permalink: https://app.warp.dev/block/8tDR0kwXIxGM446zCJf9Gk

### What should happen?

Requirements should install

### Any suggestions?

It is likely a version support issue. When I [run the same commend](https://app.warp.dev/block/0fbEJOxwDKyAFwYZmqoM6T) using python `3.10.0` it works perfectly fine.

**Comment by mtreinish** [comment]
The underlying error is not actually coming from installing qiskit, it never gets that far along as it's starting by processing the dependencies. The errors you're hitting are trying to build scipy from source because pip doesn't think that any of the versions it can find are compatible with your python 3.7 environment. This normally points to a local python environment issue. As such I'm going to close this issue as it's not anything we can fix directly in qiskit.

That being said to debug this what you can try to minimally recreate this is by running `pip install "scipy>=1.5"` in your 3.7 environment. Normally using the verbose flags for pip will tell you why pip is rejecting the precompiled scipy wheels from pypi. You can also try `pip install --prefer-binary scipy "scipy>=1.5"``to see if that helps. Normally when this happens it's because your pip version is out of date and it doesn't know how to handle the tags on the wheels, but if you're running with 22.1.2 on 3.7 that is the latest version.
