### ISSUE TITLE
Qiskit crashes when attempting to translate an 'rz' gate to 'u'

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-terra#8175]
### Environment

- **Qiskit Terra version**: main
- **Python version**: 3.8.10
- **Operating system**: Linux

### What is happening?

I build a short circuit with only 2 `rz` gates, and try to check if it is equivalent to `Id`. Qiskit crashes because it attempts to translate the `rz` gates to `u`.

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit
from qiskit.quantum_info import Clifford
from qiskit.test import QiskitTestCase
import numpy as np

class TestRZ(QiskitTestCase):
    def assertAllIdentity(self, circuit):
        """Test if all experiment circuits are identity."""
        num_qubits = circuit.num_qubits
        iden = Clifford(np.eye(2 * num_qubits, dtype=bool))
        self.assertEqual(
            Clifford(circuit), iden, f"Circuit {circuit.name} doesn't result in the identity matrix."
            )

    def test_rz(self):
        qc = QuantumCircuit(1,1)
        qc.rz(np.pi/2, 0)
        qc.rz(np.pi/2, 0)

        self.assertAllIdentity(qc)
```

### What should happen?

No crash.

**Comment by ShellyGarion** [comment]
The reason that this code fails is since it calls `Clifford(circuit)` where `circuit` contains non-clifford gates (`rz` or `u`).

According to the following documentation of the Clifford class (see: https://qiskit.org/documentation/stubs/qiskit.quantum_info.Clifford.html)

> Clifford operators can be initialized from circuits containing only Clifford gates

If you want to check that this circuit is equivalent to identity, you can call `Operator(circuit)` to get its unitary matrix,
see: https://qiskit.org/documentation/stubs/qiskit.quantum_info.Operator.html

**Comment by merav-aharoni** [comment]
Thanks, will try that.
