### ISSUE TITLE
Faster U3 composition

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8217]
### What should we add?

Recently dealing with circuits with large numbers of U / U3 gates has become important.  When looking into the composition of U3 gates Optimize1qGates it was noted that (if you use U over U3 due to overheads in the latter) that `Optimize1qGates.compose_u3`, and in particular calls to `Quaternion` become the bottleneck.  It would be nice to push this bit of code down into Rust to get an easy 100x improvement in `compose_u3`.  Here is some example Cython code that is a drop in replacement for the current code, and is hopefully easy for someone to port over:

```python

import numpy as np
cimport numpy as np
cimport cython

from libc.stdlib cimport malloc, free
from libc.math cimport cos, sin, atan2, acos, M_PI, abs

@cython.boundscheck(False)
@cython.cdivision(True)
def cy_compose_u3(double theta1, double phi1, double lambda1, double theta2, double phi2, double lambda2):
    cdef double[::1] out_angles = np.zeros(3, dtype=float)
    cdef size_t kk
    
    # temp arrays
    cdef double * q = <double *>malloc(3*sizeof(double))
    cdef double * r = <double *>malloc(3*sizeof(double))
    cdef double * s = <double *>malloc(3*sizeof(double))
    cdef double * temp = <double *>malloc(4*sizeof(double))
    cdef double * out = <double *>malloc(4*sizeof(double))
    cdef double * mat = <double *>malloc(9*sizeof(double))
    cdef double * euler = <double *>malloc(3*sizeof(double))
    
    q[0] = cos(theta1/2.0)
    q[1] = 0
    q[2] = sin(theta1/2.0)
    q[3] = 0
    
    r[0] = cos((lambda1 + phi2)/2.0)
    r[1] = 0
    r[2] = 0
    r[3] = sin((lambda1 + phi2)/2.0)
    
    s[0] = cos(theta2/2.0)
    s[1] = 0
    s[2] = sin(theta2/2.0)
    s[3] = 0
    
    # Compute YZY decomp (q.r.s in variable names)
    temp[0] = r[0] * q[0] - r[1] * q[1] - r[2] * q[2] - r[3] * q[3]
    temp[1] = r[0] * q[1] + r[1] * q[0] - r[2] * q[3] + r[3] * q[2]
    temp[2] = r[0] * q[2] + r[1] * q[3] + r[2] * q[0] - r[3] * q[1]
    temp[3] = r[0] * q[3] - r[1] * q[2] + r[2] * q[1] + r[3] * q[0]
    
    out[0] = s[0] * temp[0] - s[1] * temp[1] - s[2] * temp[2] - s[3] * temp[3]
    out[1] = s[0] * temp[1] + s[1] * temp[0] - s[2] * temp[3] + s[3] * temp[2]
    out[2] = s[0] * temp[2] + s[1] * temp[3] + s[2] * temp[0] - s[3] * temp[1]
    out[3] = s[0] * temp[3] - s[1] * temp[2] + s[2] * temp[1] + s[3] * temp[0]
    
    # out is now in YZY decomp, make into ZYZ
    mat[0] = 1 - 2 * out[2] * out[2] - 2 * out[3] * out[3]
    mat[1] = 2 * out[1] * out[2] - 2 * out[3] * out[0]
    mat[2] = 2 * out[1] * out[3] + 2 * out[2] * out[0]
    mat[3] = 2 * out[1] * out[2] + 2 * out[3] * out[0]
    mat[4] = 1 - 2 * out[1] * out[1] - 2 * out[3]*out[3]
    mat[5] = 2 * out[2] * out[3] - 2 * out[1] * out[0]
    mat[6] = 2 * out[1] * out[3] - 2 * out[2] * out[0]
    mat[7] = 2 * out[2] * out[3] + 2 * out[1] * out[0]
    mat[8] = 1 - 2 * out[1] * out[1] - 2 * out[2] * out[2]
    
    # Grab the euler angles
    if mat[3*2+2] < 1.0:
        if mat[3*2+2] > -1.0:
            euler[0] = atan2(mat[3*1+2], mat[3*0+2])
            euler[1] = acos(mat[3*2+2])
            euler[2] = atan2(mat[3*2+1], -mat[3*2+0])
        else:
            euler[0] = -atan2(mat[3*1+0], mat[3*1+1])
            euler[1] = M_PI
    else:
        euler[0] = atan2(mat[3*1+0], mat[3*1+1])
    
    for kk in range(3):
        if abs(euler[kk]) < 1e-15:
            euler[kk] = 0.0
    
    out_angles[0] = euler[1]
    out_angles[1] = phi1+euler[0]
    out_angles[2] = lambda2+euler[2]
    
    # free pointers
    free(q)
    free(r)
    free(s)
    free(temp)
    free(out)
    free(mat)
    free(euler)
        
    return np.asarray(out_angles)
```

**Comment by jakelishman** [comment]
Thanks Paul - this is definitely a good candidate for moving into Rust.  I don't know if anybody external to Terra is using the `Quaternion` class. Perhaps we could move that entire thing into Rust, and everyone can have the speed-ups if so.

@HM0880: you mentioned you were interested in getting started on some Rust bits and bobs.  This might be another good choice for you, if you'd like.  No pressure, just flagging it so you know.

**Comment by aeddins-ibm** [comment]
I have some interest in this improvement and could potentially try porting to Rust (at least the Cython snippet, not sure about all of `Quaternion`). Just to check first:
- @HM0880 Would you like to work on this as @jakelishman suggested above? It's great if you'd like to, but if not I'm also happy to try.
- @ajavadia / @nonhermitian  Does it still make sense to move this code to Rust given other ongoing work in this area? Or e.g. do you expect this code is about to be replaced by something that also handles Parameters?
- I just started learning Rust, so while this looks straightforward I might need some feedback to optimize well.

**Comment by nonhermitian** [comment]
I think there are two different workstreams.  One is to do symbolic manipulation for special cases where it is possibly faster to do so.  The second is basically this issue here, where faster numerical manipulation is desired.  As such, I think it is fine to go head with this.  

Moving the whole class to Rust seems like something interesting to try.  That would give performance somewhere between doing it all in one shot (as the code above does) and the current NumPy code; You would still have some NumPy array creation overhead, but not as much as is there now.

**Comment by nonhermitian** [comment]
As was mentioned by @mtreinish , this particular piece of code is not used in the preset passmanagers.  Those rather use `Optimize1qGatesDecomposition`.  Unlike here, where the form of the matrix is defined by the `U` angles, `Optimize1qGatesDecomposition` works on arbitrary gates by first expressing their matrix representation and then performing multiplication.  This is more difficult to speed up then the case here.  Namely there are multiple NumPy arrays being created in the process, and that becomes the bottleneck; the `__array__` method of the gates is near the top of the profiling.  Perhaps if each gate had its decomposition in terms of `U` gate angles as an attribute then that routine could see similar benefits.

As a general statement, we are working in kind of a worst case regime for using Python and NumPy as numerics because the overheads of function calls and array creation takes longer than the floating-point evaluations for such small matrices.

**Comment by levbishop** [comment]
It would require a pretty major reorg of the circuit data structures, but if we moved the parameters out of the gate instances and into a numpy tensor. Ie the circuit has a (n1,2,2) tensor for all the 1q gates, a (n2,4,4) tensor for all the 2q gates, etc, and the gate instances have indices into the corresponding tensor. If we had that then the unroll-all-the-1q-gates-in-a-circuit type cases could be vectorized nicely and avoid all the numpy dispatch overhead. Ie, instead of the current (pseudocode):
```python
for g in oneq_gates:
    u = np.array(g)
    theta = 2 * math.atan2(abs(u[1, 0]), abs(u[0, 0]))
    phiplambda2 = cmath.phase(u[1, 1])
    phimlambda2 = cmath.phase(u[1, 0])
    phi = phiplambda2 + phimlambda2
    lam = phiplambda2 - phimlambda2
```
instead have a (n, n, 2) tensor `us` of all the 1q unitaries and do the decomposition on all of them at once:
```python
thetas = 2 * np.arctan2(abs(us[:, 1, 0]), abs(us[:, 0, 0]))
phiplambda2s = np.angle(us[:, 1, 1])
phimlambda2s = np.angle(us[:, 1, 0])
phis = phiplambda2s + phimlambda2s
lams = phiplambda2s - phimlambda2s
```

Some dirty tests with `%timeit` suggests about 200x speedup from this kind of vectorization.

I'm also assuming here that the internal working representation of gates would become the unitary matrix, which also saves a lot of time from the repeated conversions between unitary and euler representations we otherwise end up doing during compilation, delaying that to conversion just once at the final stage. I looked into using 1q unitaries internally a while back and it was complicated by `UnitaryGate` being in qiskit/extensions rather than part of the circuit library. Somehow this caused circular import problems or something - I don't remember the exact issue.

**Comment by aeddins-ibm** [comment]
> could consider moving the parameters out of the gate instances and into a numpy tensor

interesting idea, though that's a bigger project than I'm personally up for at the moment. 😅 

Since it sounds useful at least in the short term, here's a first draft of a Rust port of the Cython snippet above. It agreed with Cython on a set of random imports (further below). I have not looked at timing yet. 

```
const PI:f64 = std::f64::consts::PI;

fn compose_u3_rust(theta1:f64, phi1:f64, lambda1:f64,
                   theta2:f64, phi2:f64, lambda2:f64) -> [f64; 3] {

    let q = [(theta1/2.0).cos(), 0., (theta1/2.0).sin(), 0.];
    let r = [((lambda1+phi2)/2.0).cos(), 0., 0., ((lambda1+phi2)/2.0).sin()];
    let s = [(theta2/2.0).cos(), 0., (theta2/2.0).sin(), 0.];
    
    // Compute YZY decomp (q.r.s in variable names)
    let temp: [f64; 4] = [
    r[0] * q[0] - r[1] * q[1] - r[2] * q[2] - r[3] * q[3],
    r[0] * q[1] + r[1] * q[0] - r[2] * q[3] + r[3] * q[2],
    r[0] * q[2] + r[1] * q[3] + r[2] * q[0] - r[3] * q[1],
    r[0] * q[3] - r[1] * q[2] + r[2] * q[1] + r[3] * q[0]
    ];

    let out: [f64; 4] = [
    s[0] * temp[0] - s[1] * temp[1] - s[2] * temp[2] - s[3] * temp[3],
    s[0] * temp[1] + s[1] * temp[0] - s[2] * temp[3] + s[3] * temp[2],
    s[0] * temp[2] + s[1] * temp[3] + s[2] * temp[0] - s[3] * temp[1],
    s[0] * temp[3] - s[1] * temp[2] + s[2] * temp[1] + s[3] * temp[0]
    ];


    // out is now in YZY decomp, make into ZYZ
    let mat: [f64; 9] = [
    1. - 2. * out[2] * out[2] - 2. * out[3] * out[3],
    2. * out[1] * out[2] - 2. * out[3] * out[0],
    2. * out[1] * out[3] + 2. * out[2] * out[0],
    2. * out[1] * out[2] + 2. * out[3] * out[0],
    1. - 2. * out[1] * out[1] - 2. * out[3]*out[3],
    2. * out[2] * out[3] - 2. * out[1] * out[0],
    2. * out[1] * out[3] - 2. * out[2] * out[0],
    2. * out[2] * out[3] + 2. * out[1] * out[0],
    1. - 2. * out[1] * out[1] - 2. * out[2] * out[2]
    ];
    
    // Grab the euler angles
    let mut euler: [f64; 3] = [0.,0.,0.];
    if mat[3*2+2] < 1.0 {
        if mat[3*2+2] > -1.0 {
            euler[0] = mat[3*1+2].atan2(mat[3*0+2]);
            euler[1] = (mat[3*2+2]).acos();
            euler[2] = mat[3*2+1].atan2(-mat[3*2+0]);
        } else {
            euler[0] = -1.*(mat[3*1+0].atan2(mat[3*1+1]));
            euler[1] = PI;
        }
    } else {    
        euler[0] = mat[3*1+0].atan2(mat[3*1+1]);
    }
    for kk in 0..3 {
        if euler[kk].abs() < 1e-15 {
            euler[kk] = 0.0;
        }
    }
    
    let out_angles: [f64; 3] = [euler[1], phi1+euler[0], lambda2+euler[2]];
    out_angles
}
```

I ran the Cython code on 1000 random pairs of input u3 angles:
```
random_angles = np.random.rand(1000,6)*2*np.pi
for angles in random_angles:
    results_cython.append(cy_compose_u3(*angles))
```
and found they equaled the results of feeding the same `random_angles` into the Rust function (function call not shown):

<img width="416" alt="image" src="https://user-images.githubusercontent.com/60495383/177259012-8ca421d3-6fae-41a8-bd4b-5654422b3a16.png">

So remaining steps could be:
- check the timing & optimize as appropriate
- integrate with Qiskit (I need to learn how)
- test/verify vs original Qiskit behavior

**Comment by mtreinish** [comment]
That looks like a good start it should be pretty performant there are no obvious performance red flags to me. To integrate it into qiskit it's pretty easy, you just leverage the `#[pyfunction]` macro from pyo3 to have it generate the python c api interface function and then add that to a module (either a new one or as part of an existing one). https://github.com/Qiskit/qiskit-terra/blob/main/src/sparse_pauli_op.rs#L63-L67 is a simple example of this (with the `pyfunction` use on L39). The only other thing to do is if adding a new module (instead of putting it in an existing one) is to add that to the root `_accelerate` module here: https://github.com/Qiskit/qiskit-terra/blob/main/src/lib.rs#L41-L48 and add the submodule path to qiskit: https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/__init__.py#L23-L31

**Comment by aeddins-ibm** [comment]
Thanks, hopefully I have it configured correctly now. Seeing 20-40x speedup (may depend on the random angles chosen). I guess I'll just remove the original function definition and make a PR.

<img width="765" alt="image" src="https://user-images.githubusercontent.com/60495383/177511635-ce7b06c4-8509-4622-aa72-24d956d200d3.png">

**Comment by nonhermitian** [comment]
The original Cython code gave around 60x, so seems about right.
