### ISSUE TITLE
Two local entanglement strategies reference

### ISSUE THREAD

**Issue by poig** [Qiskit/qiskit-terra#8219]
question from https://quantumcomputing.stackexchange.com/q/26994/20884

- I am using 'Two local' form of QISKIT as a waveform ansatz in VQE to compute ground state. [QISKIT documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.TwoLocal.html) does not provide references to all the entangling options. Is there any other place where I can find references for different entangling structure: 'Full', 'Linear', 'Circular' etc?

The TwoLocal documentation doesn't have reference articles for entanglement strategies, only has references for 'sca'.

**Comment by woodsp-ibm** [comment]
'sca' has a reference article since it added based on the work from that paper. Full (all to all), linear (to nearest neighbor) and circular (liner with the wrap back to the start) have been there since the earliest days with the ansatzes. These were simple general patterns we came up with when first doing the ansatzes with VQE to allow the user to easily alter entanglement for experiments. They could, beyond these built-in patterns, always do something custom. 'sca` was added later as a pattern, influenced by the paper that came out, hence the reference.

**Comment by masaduzz1** [comment]
Thanks Poig for creating the issue, and thanks woodsp-ibm for responding. I realized that it's customizable. I can use different ansatz in a straightforward manner. I guess I can easily find out the references for specific cases by searching in the web. For example, it seems to me 'linear' option is inspired from  Hardware Efficient Approximation (HEA) used in this [paper](https://www-nature-com.libezproxy2.syr.edu/articles/nature23879) (and perhaps many others).  I am still pretty new in deploying VQE to find ground state, apologies if the concern was trivial.
