### ISSUE TITLE
How `CircuitSampler` works when computing the expectation of a `ComposedOp` object consists of `EvolvedOp`s

### ISSUE THREAD

**Issue by Firepanda415** [Qiskit/qiskit-terra#8357]
## Description of the question
I am trying to compute the expectation $\langle 0^{\otimes n} |e^{iA} H e^{-iB}|0^{\otimes n} \rangle$, where matrix $A$ and $B$ are different, as following.

```
from qiskit.opflow import X, Y, Z, I
from qiskit import QuantumCircuit
from qiskit.opflow import CircuitStateFn,PauliExpectation,CircuitSampler
from qiskit.opflow import StateFn,PauliTrotterEvolution,Suzuki
from qiskit.providers.aer import AerSimulator
from qiskit.utils import QuantumInstance 

## Backend
backend = AerSimulator(method='statevector')
q_instance = QuantumInstance(backend, shots=1024)
sampler = CircuitSampler(q_instance)

## Operators
A = (0.6*Z^X) + (0.1*Z^Y)
H =  (0.3*I^Z) + (0.6*Y^Z)
B = (0.1*I^Y) + (0.6*Y^X)
op = A.exp_i().adjoint() @ H @ B.exp_i() # e^{iA} H e^{-iB}
obs = StateFn(op).adjoint() # let Qiskit consider this as the observable

## Initial State |00>
init_state = QuantumCircuit(2)
init_state = CircuitStateFn(init_state)

## Compute expectation
measurable_expression = obs @ init_state
trotterized_op = PauliTrotterEvolution(trotter_mode=Suzuki(order=1, reps=1)).convert(measurable_expression)
expectation = PauliExpectation().convert(trotterized_op)
sampled_exp_op = sampler.convert(expectation) 
print("Expectation:", sampled_exp_op.eval())
```
The code works fine but I notice that the `CircuitSampler` only cache 1 circuit by checking `sampler._circuit_ops_cache.values()`, which is the circuit for `init_state`
![image](https://user-images.githubusercontent.com/8180315/179324455-e66dde42-4afd-4180-a93b-53c3268f4b6e.png)

Does this implies the whole computation is basically classical? I notice that once I change $A$ and $B$ to single Pauli term, such as
```
A = (0.6*Z^X)
H =  (0.3*I^Z) + (0.6*Y^Z)
B = (0.1*I^Y) 
```
the cache `sampler._circuit_ops_cache.values()` will contain 4 circuits. I suppose in this case `PauliExpectation()` is grouping the Pauli terms of  the matrix $e^{iA} H e^{-iB}$. Are there any way to apply qubit-wise commutatiy to the computation of $\langle 0^{\otimes n} |e^{iA} H e^{-iB}|0^{\otimes n} \rangle$ when $A$ and $B$ have multiple Pauli terms?

**Comment by Cryoris** [comment]
These are good questions @Firepanda415! First, to their answers:

> Does this implies the whole computation is basically classical?  

Yes 🙂 

> I notice that once I change A and B  to single Pauli term, such as [...]
the cache sampler._circuit_ops_cache.values() will contain 4 circuits

This is more a coincidence than the general case, since Qiskit recognizes it can directly replace `exp(-iB)` by a `Ry` gate on the first qubit 🙂 

While you wrote down a valid mathematical expression, this is not quite how `qiskit.opflow` behaves. The `PauliTrotterEvolution` only applies to _states_ not to operators. So while something like
```python
evolution = PauliTrotterEvolution(trotter_mode=Suzuki(order=1, reps=1))
state = A.exp_i() @ Zero
measurable_expression = ~StateFn(H) @ 
trotterized_op = evolution.convert(measurable_expression)
```
applies trotterization on A, it doesn't work if you put `A.exp_i()` on the Hamiltonian.
That's because the Trotterization acts only as a decomposition into a circuit, but the Hamiltonian which we measure in `qiskit.opflow` will remain an operator, not a circuit.

Another comment to what you're trying to measure: with a standard expectation value computations on a quantum compture we can only evaluate expressions of the form $\langle\psi|H|\psi\rangle$, but not of the form $\langle\psi|H|\phi\rangle$. That means that you can't evaluate $(\langle 0| e^{iA}) H (e^{-iB}|0\rangle)$ with circuit measurements. However you can still use Qiskit to evaluate that with statevector evaluations as
```python
left = A.exp_i() @ Zero
right = B.exp_i() @ Zero
result = (~left @ H @ right).eval()
```

If you actually want to measure your quantity as expectation value, you'll either need the same states on the left and right of the Hamiltonian, or exactly compute $e^{iA}He^{-iB}$ as sums of Paulis. I hope this clarifies things a bit!

**Comment by Firepanda415** [comment]
@Cryoris Thanks for your confirmation and detailed answer! Your explanation is exactly what I need and I believe I understand what is going on here.  I will close this issue.
