### ISSUE TITLE
`PauliList.evolve` raises exception when evolving certain Clifford circuits.

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#8438]
### Environment

- **Qiskit Terra version**:  0.21.1
- **Python version**: 3.9
- **Operating system**: MacOS 11.6.7

### What is happening?

There is a bug in the `BasePauli/PauliList/Pauli` classes where the phase vector is sometimes set as dtype `uint8` instead of `int64` leading to errors when calling the `evolve` function for circuits containing gates that modify the pauli phase vector.

Whether this happens or not seems to depend on how the Pauli is initialized (sometimes it will be initialized with uint8 phase vector, other times with int64 phase vector).

### How can we reproduce the issue?

Minimal example

```python
from qiskit import QuantumCircuit
import qiskit.quantum_info as qi

# Create circuit with gate that modifies Pauli phase
qc = QuantumCircuit(2)
qc.cz(0, 1)

# Generate random Pauli
pauli = qi.random_pauli(2, seed=123)

# Try and evolve
pauli.evolve(qc)
```

Give the exception:
```
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
/var/folders/lp/ftt3j6qs7s90j6h9wszq3jcw0000gn/T/ipykernel_71613/3628800509.py in <module>
      7 pauli = qi.random_pauli(2, seed=123)
      8 #qc = qi.random_clifford(4, seed=123).to_circuit()
----> 9 pauli.evolve(qc)

~/anaconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/pauli.py in evolve(self, other, qargs, frame)
    597             other = Pauli(other)
    598 
--> 599         return Pauli(super().evolve(other, qargs=qargs, frame=frame))
    600 
    601     # ---------------------------------------------------------------------

~/anaconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/base_pauli.py in evolve(self, other, qargs, frame)
    277         if frame == "s":
    278             return self.copy()._append_circuit(other, qargs=qargs)
--> 279         return self.copy()._append_circuit(other.inverse(), qargs=qargs)
    280 
    281     def _evolve_clifford(self, other, qargs=None, frame="h"):

~/anaconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/base_pauli.py in _append_circuit(self, circuit, qargs)
    585             # Get the integer position of the flat register
    586             new_qubits = [qargs[bit_indices[tup]] for tup in instruction.qubits]
--> 587             self._append_circuit(instruction.operation, new_qubits)
    588 
    589         # Since the individual gate evolution functions don't take mod

~/anaconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/base_pauli.py in _append_circuit(self, circuit, qargs)
    558             if len(qargs) != 2:
    559                 raise QiskitError("Invalid qubits for 2-qubit gate.")
--> 560             return basis_2q[name](self, qargs[0], qargs[1])
    561 
    562         # If not a Clifford basis gate we try to unroll the gate and

~/anaconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/base_pauli.py in _evolve_cz(base_pauli, q1, q2)
    661     base_pauli._z[:, q1] ^= x2
    662     base_pauli._z[:, q2] ^= x1
--> 663     base_pauli._phase += 2 * np.logical_and(x1, x2).T
    664     return base_pauli
    665 

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('int64') to dtype('uint8') with casting rule 'same_kind'
```

### What should happen?

The dtype of the phase vector should always be the same, so that evolution and other methods that attempt to inplace modify the vector don't cause exceptions for mismatched dtypes.

### Any suggestions?

One fix would be to explicitly cast the phase vector when initializing base pauli

**Comment by chriseclectic** [comment]
I suspect the bug might be due to this line in the `_count_y` function: https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/quantum_info/operators/symplectic/base_pauli.py#L692

```python
if dtype is None:
    dtype = np.min_scalar_type(x.shape[axis])
```

**Comment by BramDo** [comment]
I tried :
if dtype is None:
        dtype = np.int64(x.shape[axis])

No errors with this solution and the result of the print(pauli.evolve) shows ZI. So this is a solution but casting could also create bug in itself. In any cast I will start an PR and run all the tests to be sure.

**Comment by jakelishman** [comment]
@chriseclectic: I think the phase vector should always be representable in a `u8` right?  It's only 2 bits of data.  The `_count_y` dtype handling there looks correct for what the function does, so I suspect the more correct solution is to ensure that whatever's calling that is passing `np.uint8` as the dtype when it's going to bind the result to a `uint8` context.  `uint` arithmetic is guaranteed to wraparound on overflow, so there shouldn't be any issues, since the phase is just about to take the result mod 4 anyway.

@BramDo: `np.int64(val)` produces a value of type `np.int64`, whereas the `dtype` argument should be a dtype instance (e.g. the class `np.int64` itself).  I'm surprised Numpy doesn't error out on that call, but I suppose it must be trying to match the type.  Either way, I don't think this is the correct solution here - I think it's missing the real issue.

**Comment by BramDo** [comment]
I did not realize that the phase vector is only 2 bits of data. I c programming you could manipulate these bits with shift and other operations. But we don't need that because the problem is not in the _count_y handling. It seems that there might be a mismatch with the calling software or even it could be there is not a problem at all. However if you run the realistic example you get the error, and with the (not correct modification ) the pauli.evolve gives you the right answer.  Maybe the real problem could be found by debugging in vscode and set some variables and breakpoints?

**Comment by jakelishman** [comment]
Each element of the phase vector is two bits of data, but Paulis on multiple qubits use a vector of these values. The issue with your PR wasn't that the output result wasn't mathematically correct, it's that it changed the data type of the phase vector from what it logically should be (u8) to something much wider (i64). That means more data is used all the time, and it was masking the real bug, which is that something somewhere else in the code was trying to do in place mutation between two values whose types it wasn't properly controlling.

**Comment by BramDo** [comment]
As already discussed it is not necessary to modify the _count_y because dtype handling there looks correct for what the function does. The more correct solution is to ensure that whatever's calling that is passing np.uint8 as the dtype when it's going to bind the result to a uint8 context, or it manually cast. The caller can be found in the exception handling of the example:

`~/anaconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/quantum_info/operators/symplectic/base_pauli.py in _evolve_cz(base_pauli, q1, q2)
    661     base_pauli._z[:, q1] ^= x2
    662     base_pauli._z[:, q2] ^= x1
--> 663     base_pauli._phase += 2 * np.logical_and(x1, x2).T
    664     return base_pauli
    665 `

In the example we use an evolve over the phase. In line 663 the phase vector is set by:
base_pauli._phase += 2 * np.logical_and(x1, x2).T

To cast the phase vector to a unit8 context we can do:
base_pauli._phase += np.uint8(2 * (np.logical_and(x1, x2).T))

Summary 
No change in the  _count_y function but modification of the result of the  _evolve_cz function. This works, I got the mathematically correct answer as before and we don't have to change the phase vector from what it logically should be (u8) to something much wider (i64) with the problem of using to much data all the time.

I'll be happy to go further with this PR if this is the way to go.
