### ISSUE TITLE
No test requirements are listed in setup.py

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-terra#8498]
### Environment

- **Qiskit Terra version**: 2bab09c1a
- **Python version**: 3,9
- **Operating system**:  FreeBSD 13.1

For example, ```ddt``` is required by tests but isn't listed.

### What is happening?

```
ImportError while importing test module '/disk-samsung/freebsd-ports/science/py-qiskit-terra/work-py39/qiskit-terra-0.21.0rc1-58-g2bab09c1a/test/python/dagcircuit/test_compose.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/__init__.py:15: in <module>
    from ddt import data, unpack
E   ModuleNotFoundError: No module named 'ddt'
_________________________________________________________________ ERROR collecting test/python/dagcircuit/test_dagcircuit.py _________________________________________________________________
ImportError while importing test module '/disk-samsung/freebsd-ports/science/py-qiskit-terra/work-py39/qiskit-terra-0.21.0rc1-58-g2bab09c1a/test/python/dagcircuit/test_dagcircuit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/__init__.py:15: in <module>
    from ddt import data, unpack
E   ModuleNotFoundError: No module named 'ddt'
_______________________________________________________________ ERROR collecting test/python/dagcircuit/test_dagdependency.py ________________________________________________________________
```

### How can we reproduce the issue?

n/a

### What should happen?

n/a

### Any suggestions?

Add test requirements.

**Comment by Cryoris** [comment]
We split the package requirements in what you need to run Qiskit as "user" and as "developer". If you only want to use Qiskit but don't need to change anything or don't want to contribute, the `requirements.txt` lists all the requirements. Once you start to develop code you'll need some extra packages and have to install `requirements-dev.txt`. Since we assume you only run tests as developer, these requirements you're missing are in `requirements-dev.txt` and you can also just install them with
```
pip install -r requirements-dev.txt
```

**Comment by yurivict** [comment]
But most of items in requirements-dev.txt aren't required for tests.
I need to list test dependencies as TEST_DEPENDS in the port and it wouldn't make sense to list packages not needed for tests. pip isn't involved.

**Comment by Cryoris** [comment]
Yes that's right, the `requirements-dev.txt` also contains required packages for the other checks like pylint or black, the docs build, and all the packages for optional tests (if I forgot something @mtreinish certainly knows all of them). I don't think we currently have a file that lists the requirements solely to run the tests 🤔

**Comment by mtreinish** [comment]
Right, the development requirements including test requirements are part of the `requirements-dev.txt`. These are for anything a developer would need to locally install on top of what qiskit itself requires for doing any development activity. We have no need to separate out a list of specific dependencies which are required solely for running unit tests. The extra requirements in that on top of tests are pretty minimal things like pylint and black. Most of the other requirements are duplicated between the different development activities.

If having an explicit list of dependencies for testing is a requirement of the FreeBSD packaging system I would either just use `requirements-dev.txt` for the `TEST_DEPENDS` variable or manually prune that list to exclude things which are clearly not for running tests. setuptools and setup.py doesn't have a provision for explicitly defining test dependencies (you could hack it in with an optional extra I guess but there isn't a use case for that in qiskit since we don't include tests in the published package) so there isn't anything we're going to add there. I'm going to close this issue since there isn't anything to fix here on the qiskit side.
