### ISSUE TITLE
Modify the qobj schema to: rigorously specify standard gates, but also allow non-standard gates to pass.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#854]
### What is the expected enhancement?
Backends can support extensions to the instruction set. For instance, simulators offer `noise`, `snapshot`, `wait`, `save` and `load` instructions. These should not live inside the base `Qobj` schema. The base schema should allow these to pass, and it will be the responsibility of a backend to allow or prevent them from passing the backend-specific schema.

The schema validation mechanism then becomes a simple 2-step process. Validate against base qobj, validate against backend qobj.

**Comment by ajavadia** [comment]
After a few discussions with @dcmckayibm @levbishop @jaygambetta @delapuente , the plan is to do the reverse of this. The backends, instead of expanding the base qobj schema, will restrict it. Essentially they act as a second filter, and any Qobj sent to them must pass the backend-specific schema as well as the base schema. To do this, the base schema will be loosened up so that it accepts any openqasm instruction. The backend schema later has the option to say "i don't accept instruction x".

Therefore, the base qobj schema should not dictate `oneOf` for its openqasm instructions. It should however provide a schema for the common instructions (i.e. those in `qelib1.inc`). It should say for example:
If you include a `u2` gate, it should have 1 qubit and 2 parameters.
If you include a Molmer-Sorenson gate, I don't enforce anything, will leave it up to the backend.

I don't know how to write a schema like this however :)

**Comment by ajavadia** [comment]
(I updated the title and description to match my comment).

**Comment by delapuente** [comment]
I'm going to open a different issue for implementing the double check. This issue is now about implementing the correct schema but we need to implement the double check mechanism tool.

**Comment by taalexander** [comment]
So if I understand correctly you wish to:
1. Breakout the hardcoded list of accepted QASM instructions. 
2. Create a standard QASM instruction schema based on `qelib1.inc`. 
3. Allow the user to specify their own instruction schema. 

Questions I have are:
1. Do we wish to validate against the union of 2 and 3? Or does 3 supersede 2?
2. Do we wish to allow the same behaviour for OpenPulse commands? 

Rather than two separate validation steps for 1/(2&3), it should be possible to dynamically append to the initial JSON schema a `uri` reference to the schemas of 2 and 3.

**Comment by ewinston** [comment]
My understanding was implementing validation against all schemas e.g. something like;
```
{"allOf": ["$schema": "qobj_schema.json", 
           "$schema": "backend_schema.json"]}
```
