### ISSUE TITLE
ImportWarning when grabbing a FakeBackend

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#8853]
### Environment

- **Qiskit Terra version**: 0.22rc1
- **Python version**: 
- **Operating system**:  Ubuntu 22.04

### What is happening?

```python
from qiskit.providers.fake_provider import FakeMumbai
import mthree

backend = FakeMumbai()
```

gives

`<frozen importlib._bootstrap>:671: ImportWarning: QiskitLoader.exec_module() not found; falling back to load_module()`

### How can we reproduce the issue?

Run the above

### What should happen?

no warnings

**Comment by jakelishman** [comment]
What version of Python?

**Comment by mtreinish** [comment]
It's interesting because that code hasn't changed since 0.21.x, and I've never seen the warning. But reading the python docs on `Loader`  the `load_module()` method I used to implement the import redirect for aer has been deprecated since 3.4 and `exec_module()` is the recommended path forward: https://docs.python.org/3/library/importlib.html#importlib.abc.Loader

I'll take a look into this and see if I can adapt how we're using `load_module()` to the newer interface.

**Comment by nonhermitian** [comment]
3.10.5

**Comment by nonhermitian** [comment]
Oddly enough it only happens if I first import `mthree` before grabbing the backend

**Comment by nonhermitian** [comment]
But if I explicitly import `AerSimulator` before calling `mthree` there is no error again:

```python
from qiskit_aer import AerSimulator

import mthree
```
fixes it

**Comment by nonhermitian** [comment]
So it looks like it boils down to grabbing Cython extensions and then the `FakeBackend`.  Ie this causes it:

```python

from qiskit.providers.fake_provider import FakeHanoi
from mthree.matrix import _reduced_cal_matrix
backend = FakeHanoi()
```

**Comment by jakelishman** [comment]
We do some trickery in Terra to make `qiskit.providers.aer` import paths work now that Aer doesn't inject itself into the namespace. If the first time a given module is seen is with the `qiskit.providers.aer` name it will trigger an import warning due to the deprecated code Matthew's accidentally used, as shown above. If the first time we see it is as `qiskit_aer`, then we we _do_ see a `qiskit.providers.aer` name, the loader short-circuit returns the imported module without triggering the deprecated code.

The solution is what Matthew had above - we should be using `load_module` rather than `exec_module`, and it's fixable within Terra.
