### ISSUE TITLE
`Bit.index` deprecation warning doesn't mention `QuantumCircuit.find_bit`

### ISSUE THREAD

**Issue by kdk** [Qiskit/qiskit-terra#8922]
### Environment

- **Qiskit Terra version**: 0.22
- **Python version**: 3.7
- **Operating system**: osx 11.7

### What is happening?

The deprecation warning raised from the `Bit.index` and `Bit.register` [0] tell users to inspect circuit registers to find where each given `Bit` is located, but it is not clear from the message how to do that, or that there exists a convenience method `QuantumCircuit.find_bit` [1] to automate this process.

[0] https://github.com/Qiskit/qiskit-terra/blob/c3792f9d20e5307263f513b417262e4cb467172e/qiskit/circuit/bit.py#L61
[1] https://github.com/Qiskit/qiskit-terra/blob/fca8db6b86cba106ed0449a99cd10223899b6145/qiskit/circuit/quantumcircuit.py#L1497

### How can we reproduce the issue?

```python
>>> qc = qk.QuantumCircuit(1)
>>> qc.qubits[0].index
DeprecationWarning: Back-references to from Bit instances to their containing Registers have been deprecated. Instead, inspect Registers to find their contained Bits.
```

### What should happen?

The deprecation warning should inform users that they can use `QuantumCircuit.find_bit` to cover cases where they would need `Bit.index` and `Bit.register`, and potentially include an example of how to do so.

**Comment by jakelishman** [comment]
tbh I think we need to be making it a larger priority to ensure that `Bit.index` and `Bit.register` aren't ever used in any Terra code - the deprecation warning has been in since (I think?) before I even joined, yet there's still parts of Terra that use it (I assume - there's still warning suppressions for it in the test suite, which is another thing I have a problem with!).

In the interim, it certainly doesn't hurt to give users more indication of what the correct paths are now, by adding this sort of error message.

From a technical perspective: their existence perpetuates a false model of how registers in circuits work now, and it makes it too easy to attempt to work with bits incorrectly; there's lots of extant code that assumes (in many forms, not just this) that `QuantumCircuit(*qc.qregs, *qc.cregs)` is a valid way to copy all the resources from one circuit into another.  That's going to hurt us with dynamic circuits more and more, where bits might be shared between multiple registers / not in registers at all.  The old form of "bits are owned by registers" isn't true any more, and `Bit.index` and `.register` are remnants of it.

**Comment by seenivasanh** [comment]
@kdk Thanks for raising this issue.
I am currently finding hard to find the index using find_bit(bit). Did you figure our what would be the input for the (bit) part? 

Thanks in advance.

**Comment by jakelishman** [comment]
I don't know why, but something triggered this issue to re-appear in my notifications.  It's especially pertinent, since there was an outage of Qiskit Runtime for dynamic circuits last month that was caused by the use of the deprecated functionality here.  I've made #9706 to update the error message, and I'll look at removing all usage of these methods from Terra as well.

**Comment by seenivasanh** [comment]
@jakelishman 
It should be because of me. I posted a comment and deleted when I figured out the solution. 
I was struggling with finding the index of a qubit using QuantumCircuit.find_bit() because Qubit.index was giving Deprecation warning. After some trials, I figured how to do it. Basically, QuantumCircuit.find_bit(qubits).index worked for me. Here, qubits is the Qubit class in qiskit, which contains information on number of qubits, name of the qubit and the index. 
As @kdk mentioned, it is not clear how to do that. An example would be handy. 

Thanks for the PR https://github.com/Qiskit/qiskit-terra/pull/9706 as well. 
Seenivasan
