### ISSUE TITLE
Purpose of the three simulators is unclear

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-terra#913]
### Informations 
The tutorials mention three simulators available as part of QISKit: local, state vector and unitary simulators. However, the tutorials don’t detail their capabilities or limitations, so it is hard to determine which simulator best suits your application. 

### Suggested solution
Recommend an explanation of each simulators’ function with examples of use cases be collocated with the tutorials to streamline the user experience.

**Comment by ajavadia** [comment]
The 3 types of simulators are:
1- QASM simulator (name might change): it simulates a generic circuit for a number of shots, and returns counts. Similar to an experiment.
2- Statevector simulator: gives you the statevector(wavefunction) resulting from the evolution of the 0 state through that circuit. Takes only 1 shots. no measure/reset.
3- Unitary simulator: gives the unitary equivalent of a given circuit. only 1 shot. no measure/reset.

These are described in the Medium blog post that accompanied the 0.5 release:
https://medium.com/qiskit/program-quantum-computers-more-easily-with-qiskit-0-5-802d1e4a338d

The source files in Terra also contain docstrings that describe them. See simulator python files in `qiskit/backends/local/`.

Perhaps we can do a better job explaining the simulators in the tutorials as well. But I'm closing the issue here as not related to Terra.

**Comment by yaelbh** [comment]
A couple of tiny comments:
- The statevector simulator can also start from a state which is not the 0 state, as specified by the user.
- I think "no measure/reset" includes also "no noise".

**Comment by delapuente** [comment]
Should we add this information to our docs and point to the blogpost in the docs? If that's the case we could keep this open to track those efforts. What do you think @ajavadia ?

**Comment by ajavadia** [comment]
@delapuente sure but I would open just a single epic for documentation improvement, and put in there a list of things that need better explaining. Because I think there are multiple enhancements needed in the docs, and opening individual issues can become messy.
