### ISSUE TITLE
Unitaries equal to identity are not removed from circuit at optimization_level=3

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#9217]
### Environment

- **Qiskit Terra version**: latest
- **Python version**: 
- **Operating system**: 

### What is happening?

The following circuit is equal to the identity:
```python

qr1 = QuantumRegister(3, 'state')
qr2 = QuantumRegister(2, 'ancilla')
cr = ClassicalRegister(2, 'c')

qc2 = QuantumCircuit(qr1, qr2, cr)
qc2.h(qr1[0])
qc2.cx(qr1[0], qr1[1])
qc2.cx(qr1[1], qr1[2])

qc2.cx(qr1[1], qr1[2])
qc2.cx(qr1[0], qr1[1])
qc2.h(qr1[0])
```

At `optimization_level=2` one gets a empty circuit:

![image](https://user-images.githubusercontent.com/1249193/204908535-5fa18c9b-5660-4527-bc3d-58dc5ff29d6e.png)

At `optimization_level=3` one does not:

![image](https://user-images.githubusercontent.com/1249193/204908623-d0510302-2237-4e93-a773-0e821024dada.png)

What is left is a unitary that is equal to the identity (as it should be) but it is not removed from the circuit data.

### How can we reproduce the issue?

Transpile above example

### What should happen?

The circuit should be empty like at `optimization_level=2`

**Comment by mtreinish** [comment]
So I think the issue here is that you're not specifying a target or `basis_gates` in the transpile call. The 2q unitary synth optimization passes need a basis to determine how to synthesize the unitary and without that being specified it's skipping the synthesis stage after the circuit is collected into a single unitary block.

That being said it's probably not too much extra overhead to add a check either in the collection pass or in the synthesis pass that still checks for identity unitary removal even without a target specified. As this isn't the first time this exact behavior has been raised in an issue.

**Comment by nonhermitian** [comment]
The difference in behavior between optimization levels is the surprising part, and leaves one having to explain why the higher optimization level is also not an empty circuit; A tricky conversation when it is an implementation issue, and one that until now I was not even aware of.

**Comment by mtreinish** [comment]
https://github.com/Qiskit/qiskit-terra/pull/9222 should fix this issue, for 1q optimization it will try all euler basis the decomposer supports and use the result which results in the shortest 1q sequence. For 2q optimization (which is optimization level3 only) it will simplify identity unitary matricies and otherwise just add a UnitaryGate to the circuit if it's not an identity.
