### ISSUE TITLE
aer_simulator_statevector doesn't return a statevector when using execute

### ISSUE THREAD

**Issue by Techmaster21** [Qiskit/qiskit-terra#9317]
### Environment

- **Qiskit Terra version**:  0.22.2
- **Python version**:  3.9.15
- **Operating system**:  macOS 12.6.2

### What is happening?

When using the `aer_simulator_statevector` with `execute` there are no counts nor state vector returned in the results. This works if instead you use

When wrapping the same backend in a `QuantumInstance` and using its `execute` method, a state vector is returned as expected.

### How can we reproduce the issue?

Works:
```python
from qiskit import execute, BasicAer, QuantumCircuit
backend = BasicAer.get_backend('statevector_simulator')
execute(QuantumCircuit(1), backend).result().get_statevector()
```
Doesn't Work:
```python
from qiskit import execute, Aer, QuantumCircuit
backend = Aer.get_backend('aer_simulator_statevector')
execute(QuantumCircuit(1), backend).result().get_statevector()
```
Works:
```python
from qiskit import Aer, QuantumCircuit
from qiskit.utils import QuantumInstance
backend = Aer.get_backend('aer_simulator_statevector')
QuantumInstance(backend).execute(QuantumCircuit(1)).get_statevector()
```

### What should happen?

All examples given should work

**Comment by jakelishman** [comment]
This is expected behaviour - the implicit snapshotting of the statevector was removed quite some time ago, in part because it causes more problems when people want to make mid-circuit snapshots, and expanded the memory cost of results for the more common use-case of not needing statevectors (especially for large circuits).  `BasicAer` and `QuantumInstance` are largely unmaintained, and `QuantumInstance` is fully scheduled for removal.

You can make the statevector available by running `QuantumCircuit.save_statevector()` in the place you want to make the snapshot.
