### ISSUE TITLE
Calling `synth(registerless=False)` on a classical function synth labels the qubits wrongly

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#9363]
### Environment

- **Qiskit Terra version**:  0.23.0.dev0+dcd7bea
- **Python version**:  3.9

### What is happening?

In https://github.com/Qiskit/qiskit-terra/pull/9337#discussion_r1067055542 @Cryoris noticed that `classical_function` synthesis labels the qubits in the reversed order.

### How can we reproduce the issue?

:

```python
from qiskit.circuit.classicalfunction import classical_function
from qiskit.circuit.classicalfunction.types import Int1

@classical_function
def grover_oracle(a: Int1, b: Int1, c: Int1) -> Int1:
    return (a and b and not c)

quantum_circuit = grover_oracle.synth(registerless=False)
print(quantum_circuit.draw())
```
```
     c: ──■──
          │  
     b: ──■──
          │  
     a: ──o──
        ┌─┴─┐
return: ┤ X ├
        └───┘
```

### What should happen?

in that example, the open control is on `c`, not on `a`.

**Comment by 1ucian0** [comment]
I'm not sure here what's expected. It could be either:
```
     a: ──■──
          │  
     b: ──■──
          │  
     c: ──o──
        ┌─┴─┐
return: ┤ X ├
        └───┘
```
or
```
     c: ──o──
          │  
     b: ──■──
          │  
     a: ──■──
        ┌─┴─┐
return: ┤ X ├
        └───┘
```

Tweedledum seems to prefer the first option.

**Comment by jakelishman** [comment]
You could argue either way - `def oracle(q_0, q_1, q_2)` satisfies `*args` where `args[0] == q_0` and so on, so the indexing matches the actual usage, whereas `def oracle(q_2, q_1, q_0)` just looks kind of like how bitstrings are printed.  The former is probably better, because it matches the semantics when passing `qargs` in a list to things like `QuantumCircuit.append`.
