### ISSUE TITLE
Full support for control flow in `transpile`

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#9417]
### What should we add?

Over the course of the epic:
- #8630

we added support for control-flow to the transpiler at optimisation levels 0 and 1.  For full support, we need to bring the missing passes up-to-speed as well.  This epic tracks the other components to achieve that.

For the purposes of this issue, we particularly need `SabreSwap` upgrading.  For optimisation level 2, we need the optimisation passes `CommutationAnalysis` and `CommutativeCancellation`, and optimisation level 3 (and some less common transpiler options) make up the rest.  We do _not_ need to add support for control-flow to all of the scheduling passes right now, because Qiskit control-flow is only supported by IBM hardware at the moment, and scheduling this is handled by the IBM provider.

When these are updated, we should also make sure that the corresponding gated checks in the preset pass-manager constructors are corrected.

Sub-epics:
- [x] #9431
- [x] #9432

Tracked issues:
- [x] #9419 
- [x] #9421 
- [x] #9422
- [x] #9423
- [x] #9425 
- [x] #9426

Low priority related issues - these should not be prioritised, and are not required for this epic:
- [ ] #9429 
- [ ] #9430

**Comment by jlapeyre** [comment]
The current implementation of `ConsolidateBlocks` requires that information regarding nodes on the DAG persists across passes, using the usual properties mechanism. But the blocks of ops inside control flow ops (need a good name for that!) are `QuantumCircuit`s. If you convert them to `DAGCircuit`s each time you need to analyze or modify them in a pass, the relevant node ids will not be the same across passes. Trying to refer to the node ids from a previous pass would result in an error. There's also the issue of performance degradation from repeated conversion between circuits and dags. But that is a secondary concern. 

We might try something like this:
1.  Allow the bodies of control flow ops to be `DAGCircuit`s, rather than restricting them to `QuantumCircuit` as is currently the case. Maybe making `IfElseOp` a parametric type is reasonable. It seems Python seems to be evolving toward better support for this. But, I imagine there are some downsides. Or more simply, allow the two types in the bodies and do `isinstance` checks. This will add a bit of complexity and bug-proneness.
2. Modify `circuit_to_dag` to recursively convert control flow ops to use `DAGCircuit`.

Then these lower-level `DAG`s will have a persistent identity. And we can manipulate them at a lower level. Eg. within `DAGCircuit`. This should be cleaner than doing conversion and recursion into bodies repeatedly at higher levels.
