### ISSUE TITLE
Add Opflow Migration Guide

### ISSUE THREAD

**Issue by ElePT** [Qiskit/qiskit-terra#9484]
### What should we add?

To follow through with our plan to deprecate `qiskit.opflow`, we need a clear migration guide, and most likely a new documentation sub-section called ``migrations`` (@1ucian0).

I am currently working on this guide on a fork of the documentation repo, and will open a PR once the content is complete. In the meantime, you can track the progress of the current WIP document [here](https://github.com/ElePT/qiskit_sphinx_theme/blob/opflow-migration/docs/migrations/opflow_operator_logic.rst).

**Comment by jakelishman** [comment]
While we're still deploying the Terra documentation via the metapackage, this might need a little bit of extra infrastructure on that side as well because there's an assumption there that all the docs we want to display are stored in `docs/apidocs` in Terra (our build process is _suboptimal_ haha).  It won't be too hard to do if we need to, though.

**Comment by woodsp-ibm** [comment]
Related to #9176
