### ISSUE TITLE
Sampler gradient not returning consistent number of gradients

### ISSUE THREAD

**Issue by aletcher** [Qiskit/qiskit-terra#9508]
### Environment

- **Qiskit Terra version**: 0.23.0rc1
- **Python version**: 3.9.13
- **Operating system**: macOS 13.1

### What is happening?

When applied to a parameterised circuit with n >= 14 qubits, the sampler gradient does not always return the correct number of gradients. It should return 2ˆn gradients for each parameter in the circuit, but it sometimes returns fewer. I have only tested this with ParamShiftSamplerGradient and LinCombSamplerGradient on a single-layer RealAmplitudes circuit.

In the code below with fixed numpy seed for reproducibility, the first 10 calls to the sampler gradient correctly return 2ˆ14 = 16384 gradients for the zeroth parameter, but the 11th incorrectly returns 16376 gradients.

### How can we reproduce the issue?

```
import numpy as np
np.random.seed(42)

from qiskit.algorithms.gradients import ParamShiftSamplerGradient, LinCombSamplerGradient
from qiskit.circuit.library import RealAmplitudes
from qiskit.primitives import Sampler

num_qubits = 14

qc = RealAmplitudes(num_qubits, reps=1)
qc.measure_all()

sampler = Sampler()
sampler_gradient = ParamShiftSamplerGradient(sampler)
sampler_gradient = LinCombSamplerGradient(sampler)

def get_grads():
    weights = np.random.uniform(0, np.pi, qc.num_parameters)
    grad_job = sampler_gradient.run(circuits=[qc], parameter_values=[weights], parameters=[qc.parameters[:1]])
    # Get gradients for zeroth (and only) circuit and zeroth parameter
    grads = grad_job.result().gradients[0][0] 
    return grads

for _ in range(11):
    grads = get_grads()
    print(len(grads))
```

### What should happen?

Observed output:
```
16384
16384
16384
16384
16384
16384
16384
16384
16384
16384
16376 <--- not the right number!
```

Expected output:
```
16384
16384
16384
16384
16384
16384
16384
16384
16384
16384
16384
```

**Comment by Cryoris** [comment]
@a-matsuo do you have any idea why that could come up? Maybe something with the `ThreadPoolExecutor`? 🤔

**Comment by a-matsuo** [comment]
The issue is reproducible in my environment as well. I increased the number of repetitions from 11 to 100. Then I got  like this. It rarely happens, but the error always occurs at certain times i.e. 11, 62, and 77. 🤔 
<img width="319" alt="image (2)" src="https://user-images.githubusercontent.com/47442626/216299095-4f6962af-ab46-4aea-b76c-7b152b437122.png">

**Comment by jakelishman** [comment]
It's the input weights that matter - if you `np.random.seed(1)` for the `weights = np.random.uniform(...)` you get the wrong number every time.

**Comment by a-matsuo** [comment]
I think the sampler results with probability 0 (which are removed) are causing this and the behavior is as expected. I increased the number of repetitions from 11 to 100. Then I got  like this. It happens rarely, but it always happens at a certain time, i.e. 11, 62, and 77.
For example, when I checked the sampler results for instance no. 11, the number of sampler results was less than 16384. So the number of sampler gradient results will also be less than 16384 (It maintains the property of being sparse).

<img width="319" alt="image (2)" src="https://user-images.githubusercontent.com/47442626/216303930-6c44bda2-ac69-4a17-9aee-797015e6028a.png">

**Comment by Cryoris** [comment]
It turns out our assumption was wrong: the gradient dictionary does not include all `2^n` probability gradients, but only thosw which are nonzero. This is per design, as otherwise we'd always have an exponentially large dictionary, see also #9248 on the same topic 🙂 

So the length not being consistent just means that some of the probability gradients are zero. To handle that your code would need to be changed to work on dictionaries, or you could turn the dictionary into a sparse vector to keep the efficient representation.

**Comment by aletcher** [comment]
Thank you @a-matsuo and @Cryoris for clarifying! I didn't realise that the sampler only returned non-zero gradients. That makes sense.
