### ISSUE TITLE
follow to #948 drop CPP from the best simulator class name

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#957]
### What is the expected enhancement?
I don't want it showing cpp I would like it cpp to be the default and py added only if there is no cpp.

**Comment by dongreenberg** [comment]
I want to call out something related to this. I've run into an issue where I was setting my backend to "local_statevector_simulator" and did not realize that the simulator was failing gracefully to the python simulator because the cpp was not compiled correctly. It took me several days to figure out why my code was executing so slowly. Now I only set my backend to "local_statevector_simulator_cpp" so the backend will fail explicitly if there is an issue. I think other new users could run into this issue. I'm not sure what the solution is - maybe we execute your change above, but don't fail gracefully to the python simulator if the circuit volume is sufficiently large that the python simulator will be noticeably slower (>1000 gates?)?

**Comment by jaygambetta** [comment]
In Aer, we should tell the user that is using a slow one or something. I would rather not even have the python if the cpp always works. The Python should slowly go away as it does not have all the features. 

For now i want the default name to be without an extension.

**Comment by jaygambetta** [comment]
@ajavadia are you going to do this

**Comment by ajavadia** [comment]
@jaygambetta Yeah. I'll push a patch soon. 
@dongreenberg I think a version of #383 will be included in Aer, to determine rough runtime constraints based on user's local hardware. It is a good idea to provide a message based on user fallback as well.
