### ISSUE TITLE
load_qasm_file and load_qasm_string should be part of circuits

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#971]
### What is the expected behavior?
The load_qasm_* should be part of the circuit object and not in the wrapper

```circuit(qasm_file)```

or 

```circuit.load(qasm_file)```

**Comment by 1ucian0** [comment]
I do agree with this approach. Somebody against it?

**Comment by 1ucian0** [comment]
Something like `load_qasm_file` and  `load_qasm_string`?

**Comment by mtreinish** [comment]
So I'm starting to implement this now. Looking at how we'd do this we can parse the qasm and get an ast pretty easily. But when it comes to converting that ast to a circuit object it gets a bit more involved. We could either use the `Unroller()` with the backend set to `CircuitBackend` inside the new constructor methods. Or alternatively we could basically inline that code. (which would end up with a bunch of duplicated code) But I just want to make sure I'm not missing something obvious or there was another path to implement this because we'll need to loop over the ast from the Qasm parser and construct the circuit from that.

**Comment by mtreinish** [comment]
I threw together a commit to do this here: https://github.com/mtreinish/qiskit-core/commit/e50778baa9703be8e2bf097ba3103052946655c5 but it's blocked until #1152 merges because it depends on that refactor to work.

**Comment by jaygambetta** [comment]
the unroller is how I would do it as well. I want to rethink the unroller but this makes the most sense now

**Comment by jaygambetta** [comment]
Also, i have an initial implementation  for #1144 but it is the same code as what you have in this so i think let's get your pr in and then i make mine
