### ISSUE TITLE
Bad import of the VQE class when importing from algorithms

### ISSUE THREAD

**Issue by pfargas** [Qiskit/qiskit-terra#9894]
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

If you import `VQE` from qiskit.algorithms, it returns the deprecated version, found in minimum_eigen_solvers

### How can we reproduce the issue?

from qiskit.algorithms import VQE

### What should happen?

The import should get the VQE class found in minimum_eigensolvers, not minimum_eigen_solvers

**Comment by woodsp-ibm** [comment]
This is as intended since if the import was switched it would break a lot of existing code that used the older VQE that is based on using Quantum Instance. Also at the moment that VQE is pending deprecated, not yet deprecated, which should happen in this upcoming release. There is a migration guide, in progress, that covers this #9557 To use the new VQE, based on the new Estimator primitives, it has to be imported explicitly from the new location. At some future point we can consider having the import from qiskit.algorithms point to the new VQE, but its way to soon to do that.

**Comment by gorkamunoz** [comment]
Hi! Maybe it would be useful to have a warning when importing from `minimum_eigen_solvers` stating that it is deprecated and that the VQE from `minimum_eigensolvers` should be used instead?
